Repository ava-labs/avalanchego, pull requests merged in 2023-11, with the labels that each got.

#2258 Switch to using require.TestingT interface in SenderTest struct
  snow/engine/common/test_sender.go
Labels: testing

#2257 Cleanup `ipcs` `Socket` test
  ipcs/socket/socket_test.go
Labels: bug, testing

#2260 Require poll metrics to be registered
  snow/consensus/snowman/poll/set.go
  snow/consensus/snowman/poll/set_test.go
  snow/engine/snowman/transitive.go
Labels: consensus, monitoring, cleanup

#2253 Track all subnet validator sets in the validator manager
  snow/validators/logger.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/block/executor/standard_block_test.go
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
  vms/platformvm/txs/executor/advance_time_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/validators/manager.go
  vms/platformvm/validators/manager_benchmark_test.go
  vms/platformvm/vm.go
  vms/platformvm/vm_regression_test.go
Labels: vm

#2197 Remove Token constants information from keys
  x/merkledb/codec.go
  x/merkledb/codec_test.go
  x/merkledb/db.go
  x/merkledb/db_test.go
  x/merkledb/helpers_test.go
  x/merkledb/history.go
  x/merkledb/history_test.go
  x/merkledb/intermediate_node_db.go
  x/merkledb/intermediate_node_db_test.go
  x/merkledb/key.go
  x/merkledb/key_test.go
  x/merkledb/node.go
  x/merkledb/node_test.go
  x/merkledb/proof.go
  x/merkledb/proof_test.go
  x/merkledb/trie_test.go
  x/merkledb/trieview.go
  x/merkledb/value_node_db.go
  x/merkledb/value_node_db_test.go
  x/merkledb/view_iterator.go
  x/sync/client.go
  x/sync/client_test.go
  x/sync/g_db/db_client.go
  x/sync/g_db/db_server.go
  x/sync/manager.go
  x/sync/network_server_test.go
  x/sync/sync_test.go
Labels: merkledb

#2264 Remove unused `UnsortedEquals` function
  utils/compare/compare.go
  utils/compare/compare_test.go
Labels: cleanup

#2254 Document p2p package
  network/p2p/handler.go
  network/p2p/router.go
Labels: documentation, sdk

#2267 `merkledb` -- rename nit
  x/merkledb/proof.go
Labels: merkledb

#2268 `merkledb` -- fix nil check in test
  x/merkledb/trie_test.go
Labels: merkledb

#2266 Add read-only database flag (`--db-read-only`)
  config/config.go
  config/flags.go
  config/keys.go
  node/config.go
  node/node.go
Labels: storage

#2269 `merkledb` -- remove unneeded var declarations
  x/sync/client.go
Labels: merkledb

#1992 Add fuzz test for `NewIteratorWithStartAndPrefix`
  database/corruptabledb/db_test.go
  database/encdb/db_test.go
  database/leveldb/db_test.go
  database/memdb/db_test.go
  database/meterdb/db_test.go
  database/pebble/db_test.go
  database/prefixdb/db_test.go
  database/rpcdb/db_test.go
  database/test_database.go
  database/versiondb/db_test.go
Labels: testing, storage, ci

#2271 Return if element was deleted from `Hashmap`
  utils/linkedhashmap/linkedhashmap.go
  utils/linkedhashmap/linkedhashmap_test.go
  vms/avm/txs/mempool/mempool.go
Labels: cleanup

#2276 `mempool.NewMempool` -> `mempool.New`
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/txs/mempool/mempool.go
  vms/platformvm/txs/mempool/mempool_test.go
  vms/platformvm/vm.go
Labels: cleanup

#2265 e2e: Refactor suite setup and helpers to tests/fixture/e2e for reuse by coreth
  tests/e2e/banff/suites.go
  tests/e2e/c/dynamic_fees.go
  tests/e2e/c/interchain_workflow.go
  tests/e2e/e2e_test.go
  tests/e2e/faultinjection/duplicate_node_id.go
  tests/e2e/p/interchain_workflow.go
  tests/e2e/p/permissionless_subnets.go
  tests/e2e/p/staking_rewards.go
  tests/e2e/p/workflow.go
  tests/e2e/static-handlers/suites.go
  tests/e2e/x/interchain_workflow.go
  tests/e2e/x/transfer/virtuous.go
  tests/fixture/e2e/describe.go
  tests/fixture/e2e/env.go
  tests/fixture/e2e/flags.go
  tests/fixture/e2e/helpers.go
  tests/upgrade/upgrade_test.go
Labels: testing

#2278 Cleanup platformvm mempool errs
  vms/platformvm/txs/mempool/mempool.go
Labels: cleanup

#2274 MerkleDB:Naming and comments cleanup
  x/merkledb/cache.go
  x/merkledb/codec.go
  x/merkledb/db.go
  x/merkledb/history.go
  x/merkledb/key.go
  x/merkledb/proof.go
  x/merkledb/trieview.go
  x/sync/network_server.go
Labels: merkledb

#2279 Move `DropExpiredStakerTxs` to platformvm mempool
  vms/platformvm/block/builder/builder.go
  vms/platformvm/txs/mempool/mempool.go
Labels: cleanup

#1384 Remove Lazy Initialize on Node
  app/app.go
  main/main.go
  node/node.go
Labels: cleanup

#2106 Remove sentinel node from MerkleDB proofs
  x/merkledb/db.go
  x/merkledb/history_test.go
  x/merkledb/proof_test.go
  x/merkledb/trie_test.go
  x/merkledb/trieview.go
  x/sync/manager.go
Labels: merkledb

#2288 Embed `noop` handler for all unhandled messages
  vms/platformvm/block/builder/network.go
Labels: cleanup

#2277 `merkledb` -- Add `Clearer` interface
  proto/pb/sync/sync.pb.go
  proto/pb/sync/sync_grpc.pb.go
  proto/sync/sync.proto
  x/merkledb/db.go
  x/merkledb/db_test.go
  x/merkledb/intermediate_node_db.go
  x/merkledb/intermediate_node_db_test.go
  x/merkledb/mock_db.go
  x/merkledb/value_node_db.go
  x/merkledb/value_node_db_test.go
  x/sync/db.go
  x/sync/g_db/db_client.go
  x/sync/g_db/db_server.go
Labels: merkledb

#2285 Simplify get server creation
  chains/manager.go
  snow/engine/avalanche/bootstrap/bootstrapper_test.go
  snow/engine/avalanche/getter/getter.go
  snow/engine/avalanche/getter/getter_test.go
  snow/engine/common/config.go
  snow/engine/common/test_config.go
  snow/engine/snowman/bootstrap/bootstrapper_test.go
  snow/engine/snowman/getter/getter.go
  snow/engine/snowman/getter/getter_test.go
  snow/engine/snowman/syncer/state_syncer_test.go
  snow/engine/snowman/syncer/utils_test.go
  snow/engine/snowman/transitive_test.go
  vms/platformvm/vm_test.go
  x/merkledb/db_test.go
Labels: consensus, cleanup

#2292 Move management of platformvm preferred block to `executor.Manager`
  vms/platformvm/block/builder/builder.go
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/executor/manager.go
  vms/platformvm/block/executor/mock_manager.go
  vms/platformvm/service.go
  vms/platformvm/service_test.go
  vms/platformvm/vm.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
Labels: cleanup

#2275 e2e: More fixture refinement in support of coreth integration testing
  tests/e2e/ignore.go
  tests/fixture/e2e/helpers.go
  tests/fixture/testnet/local/network.go
Labels: testing

#2293 Add `VerifyTx` to `executor.Manager`
  vms/avm/block/executor/manager.go
  vms/platformvm/block/builder/builder.go
  vms/platformvm/block/executor/manager.go
  vms/platformvm/block/executor/mock_manager.go
Labels: cleanup

#2286 Simplify avalanche bootstrapping
  chains/manager.go
  node/node.go
  snow/engine/avalanche/bootstrap/bootstrapper.go
  snow/engine/avalanche/bootstrap/bootstrapper_test.go
  snow/engine/avalanche/bootstrap/config.go
  snow/engine/avalanche/getter/getter.go
  version/constants.go
Labels: consensus, cleanup

#2317 Replace unique slices with sets in the engine interface
  snow/engine/avalanche/getter/getter.go
  snow/engine/avalanche/getter/getter_test.go
  snow/engine/common/bootstrapper.go
  snow/engine/common/engine.go
  snow/engine/common/no_ops_handlers.go
  snow/engine/common/test_engine.go
  snow/engine/common/traced_engine.go
  snow/engine/snowman/getter/getter.go
  snow/engine/snowman/getter/getter_test.go
  snow/engine/snowman/syncer/state_syncer.go
  snow/engine/snowman/syncer/state_syncer_test.go
  snow/networking/handler/handler.go
  snow/networking/handler/handler_test.go
  snow/networking/handler/parser.go
  utils/sorting.go
  utils/sorting_test.go
  vms/platformvm/vm_test.go
Labels: consensus, cleanup

#2320 Use zap.Stringer rather than zap.Any
  snow/networking/handler/handler.go
Labels: monitoring, cleanup

#2310 Move `AddUnverifiedTx` logic to `network.IssueTx`
  vms/platformvm/block/builder/builder.go
  vms/platformvm/block/builder/network.go
Labels: cleanup

#2311 Remove `AddUnverifiedTx` from `Builder`
  vms/platformvm/block/builder/builder.go
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/block/builder/network.go
  vms/platformvm/block/builder/network_test.go
  vms/platformvm/service.go
  vms/platformvm/service_test.go
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
Labels: cleanup

#2252 Remove error from SDK AppGossip handler
  go.mod
  go.sum
  network/p2p/handler.go
  network/p2p/handler_test.go
  network/p2p/mocks/mock_handler.go
  network/p2p/router.go
  network/p2p/throttler_handler.go
  network/p2p/throttler_handler_test.go
Labels: networking, sdk

#2321 Rename AppRequestFailed to AppError
  proto/p2p/p2p.proto
  proto/pb/p2p/p2p.pb.go
Labels: networking

#2312 Remove `Network` interface from `Builder`
  vms/platformvm/block/builder/builder.go
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/builder/network.go
  vms/platformvm/block/builder/network_test.go
  vms/platformvm/service.go
  vms/platformvm/service_test.go
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/vm.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
Labels: cleanup

#2322 Update `error_code` to be int32 instead of uint32.
  proto/p2p/p2p.proto
  proto/pb/p2p/p2p.pb.go
Labels: networking

#2300 Refactor bootstrapper implementation into consensus
  snow/consensus/snowman/bootstrapper/majority.go
  snow/consensus/snowman/bootstrapper/majority_test.go
  snow/consensus/snowman/bootstrapper/minority.go
  snow/consensus/snowman/bootstrapper/minority_test.go
  snow/consensus/snowman/bootstrapper/noop.go
  snow/consensus/snowman/bootstrapper/noop_test.go
  snow/consensus/snowman/bootstrapper/poll.go
  snow/consensus/snowman/bootstrapper/poll_test.go
  snow/consensus/snowman/bootstrapper/requests.go
  snow/consensus/snowman/bootstrapper/sampler.go
  snow/consensus/snowman/bootstrapper/sampler_test.go
  snow/engine/common/bootstrapper.go
Labels: consensus, cleanup

#2291 Pchain - Cleanup NodeID generation in UTs
  tests/e2e/static-handlers/suites.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/block/executor/standard_block_test.go
  vms/platformvm/service_test.go
  vms/platformvm/txs/executor/advance_time_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/txs/executor/proposal_tx_executor_test.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/txs/validator_test.go
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
Labels: testing, cleanup

#2316 nit: loop --> variadic
  snow/engine/snowman/syncer/state_syncer.go
Labels: cleanup

#2325 Update zap dependency to v1.26.0
  go.mod
  go.sum
Labels: dependencies

#2326 Remove useless anon functions
  snow/engine/snowman/bootstrap/bootstrapper.go
  snow/networking/timeout/manager.go
Labels: cleanup

#2296 Move `network` implementation to separate package
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/builder/network_test.go
  vms/platformvm/network/main_test.go
  vms/platformvm/network/network.go
  vms/platformvm/network/network_test.go
  vms/platformvm/vm.go
Labels: cleanup

#2327 Unexport avalanche constant from common package
  snow/engine/avalanche/bootstrap/bootstrapper.go
  snow/engine/common/bootstrapper.go
Labels: consensus, cleanup

#2328 Remove `common.Config` functions
  snow/engine/common/config.go
  snow/engine/snowman/bootstrap/bootstrapper.go
  snow/engine/snowman/syncer/state_syncer.go
Labels: consensus, cleanup

#2329 Move engine startup into helper function
  snow/engine/snowman/bootstrap/bootstrapper.go
  snow/engine/snowman/syncer/state_syncer.go
Labels: cleanup

#2301 Remove bootstrapping retry config
  chains/manager.go
  config/config.go
  config/flags.go
  config/keys.go
  node/config.go
  node/node.go
  snow/engine/common/bootstrapper.go
  snow/engine/common/config.go
  snow/engine/snowman/bootstrap/bootstrapper.go
  snow/engine/snowman/bootstrap/bootstrapper_test.go
  snow/engine/snowman/syncer/state_syncer.go
  snow/engine/snowman/syncer/state_syncer_test.go
  vms/platformvm/vm_test.go
Labels: consensus, cleanup

#2331 Export snowman bootstrapper
  chains/manager.go
  snow/engine/snowman/bootstrap/bootstrapper.go
  snow/engine/snowman/bootstrap/bootstrapper_test.go
Labels: consensus, cleanup

#2330 Remove common.Config from syncer.Config
  chains/manager.go
  snow/engine/snowman/syncer/config.go
  snow/engine/snowman/syncer/state_syncer_test.go
  snow/engine/snowman/syncer/utils_test.go
Labels: consensus, cleanup

#2319 `platformvm.VM` -- replace `Config` field with `validators.Manager`
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/validators/manager_benchmark_test.go
  vms/platformvm/vm.go
  vms/platformvm/vm_regression_test.go
Labels: cleanup

#2347 Improve height monitoring
  snow/consensus/metrics/height.go
  snow/consensus/snowman/topological.go
Labels: consensus, monitoring

#2349 Cleanup snowman consensus metrics
  snow/consensus/metrics/height.go
  snow/consensus/metrics/latency.go
  snow/consensus/metrics/polls.go
  snow/consensus/metrics/timestamp.go
  snow/consensus/snowman/metrics.go
  snow/consensus/snowman/topological.go
Labels: monitoring, cleanup

#2354 Expand consensus health check
  snow/consensus/snowman/topological.go
Labels: consensus, monitoring, cleanup

#2355 Reduce the size of the OracleBlock interface
  snow/consensus/snowman/oracle_block.go
  vms/platformvm/vm_test.go
Labels: cleanup

#1536 Use linkedhashmap for P-Chain mempool
  vms/platformvm/block/builder/builder.go
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/txs/mempool/issuer.go
  vms/platformvm/txs/mempool/mempool.go
  vms/platformvm/txs/mempool/mempool_test.go
  vms/platformvm/txs/mempool/mock_mempool.go
  vms/platformvm/txs/mempool/remover.go
  vms/platformvm/txs/txheap/by_age.go
  vms/platformvm/txs/txheap/by_end_time.go
  vms/platformvm/txs/txheap/by_start_time.go
  vms/platformvm/txs/txheap/by_start_time_test.go
Labels: cleanup

#2361 Increase txs in pool metric when adding tx
  vms/platformvm/txs/mempool/mempool.go
Labels: bug, monitoring

#2353 Update versions for v1.10.16
  RELEASES.md
  go.mod
  go.sum
  version/compatibility.json
  version/constants.go
Labels: documentation

#2360 Remove Banff check from mempool verifier
  vms/platformvm/txs/executor/tx_mempool_verifier.go
Labels: cleanup

#2364 Document storage growth in readme
  README.md
Labels: documentation

#2366 Add metric for duration between block timestamp and acceptance time
  snow/consensus/snowman/metrics.go
  snow/consensus/snowman/topological.go
  snow/engine/snowman/bootstrap/block_job.go
Labels: consensus, monitoring, networking

#2373 `vms/platformvm`: Remove unused `withMetrics` txheap
  vms/platformvm/txs/txheap/with_metrics.go
Labels: cleanup

#2356 Move peerTracker from x/sync to network/p2p
  network/p2p/peer_tracker.go
  network/p2p/peer_tracker_test.go
  x/sync/network_client.go
Labels: networking

#2372 Logging avoid closing standard outputs
  utils/logging/log.go
Labels: monitoring

#2368 `vms/platformvm`: Adjust `Diff.Apply` signature
  vms/platformvm/state/diff.go
  vms/platformvm/state/diff_test.go
  vms/platformvm/state/mock_diff.go
Labels: cleanup

#2371 Add bls validator info to genesis
  genesis/config.go
  genesis/genesis.go
  genesis/unparsed_config.go
  vms/platformvm/api/static_service.go
  vms/platformvm/state/state.go
Labels: testing

#2370 `vms/platformvm`: Consolidate `state` pkg mocks
  scripts/mocks.mockgen.txt
  vms/platformvm/state/mock_chain.go
  vms/platformvm/state/mock_diff.go
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/mock_versions.go
Labels: cleanup

#2297 Remove common bootstrapper
  chains/manager.go
  snow/engine/avalanche/bootstrap/bootstrapper.go
  snow/engine/common/bootstrapable.go
  snow/engine/common/bootstrapper.go
  snow/engine/common/config.go
  snow/engine/common/test_bootstrapable.go
  snow/engine/common/test_bootstrapper.go
  snow/engine/common/test_config.go
  snow/engine/common/traced_bootstrapable_engine.go
  snow/engine/snowman/bootstrap/bootstrapper.go
  snow/engine/snowman/bootstrap/bootstrapper_test.go
  snow/engine/snowman/bootstrap/config.go
  snow/engine/snowman/config_test.go
  snow/engine/snowman/syncer/state_syncer.go
  snow/engine/snowman/syncer/state_syncer_test.go
  snow/engine/snowman/syncer/utils_test.go
  snow/engine/snowman/transitive_test.go
  snow/networking/handler/handler_test.go
  snow/networking/handler/health_test.go
  snow/networking/router/chain_router_test.go
  snow/networking/sender/sender_test.go
  vms/platformvm/vm_test.go
Labels: consensus, cleanup

#2381 `vms/avm`: Rename `states` pkg to `state`
  scripts/mocks.mockgen.txt
  vms/avm/block/builder/builder.go
  vms/avm/block/builder/builder_test.go
  vms/avm/block/executor/block.go
  vms/avm/block/executor/block_test.go
  vms/avm/block/executor/manager.go
  vms/avm/block/executor/manager_test.go
  vms/avm/block/executor/mock_manager.go
  vms/avm/service_test.go
  vms/avm/state/diff.go
  vms/avm/state/mock_state.go
  vms/avm/state/state.go
  vms/avm/state/state_test.go
  vms/avm/state/versions.go
  vms/avm/txs/executor/executor.go
  vms/avm/txs/executor/executor_test.go
  vms/avm/txs/executor/semantic_verifier.go
  vms/avm/txs/executor/semantic_verifier_test.go
  vms/avm/vm.go
Labels: cleanup

#2383 Implement generic bimap
  codec/hierarchycodec/codec.go
  codec/linearcodec/codec.go
  snow/engine/avalanche/bootstrap/bootstrapper.go
  snow/engine/common/fetcher.go
  snow/engine/common/request.go
  snow/engine/common/requests.go
  snow/engine/common/requests_test.go
  snow/engine/snowman/bootstrap/bootstrapper.go
  snow/engine/snowman/bootstrap/bootstrapper_test.go
  snow/engine/snowman/transitive.go
  utils/bimap/bimap.go
  utils/bimap/bimap_test.go
Labels: consensus, cleanup

#2384 Unexport RequestID from snowman engine
  snow/engine/snowman/transitive.go
Labels: consensus, cleanup

#2376 Add metric to track the stake weight of block providers
  snow/engine/snowman/issuer.go
  snow/engine/snowman/metrics.go
  snow/engine/snowman/transitive.go
  snow/engine/snowman/transitive_test.go
Labels: consensus, monitoring, networking

#2386 Add block source metrics to monitor gossip
  snow/engine/snowman/issuer.go
  snow/engine/snowman/metrics.go
  snow/engine/snowman/transitive.go
  snow/engine/snowman/transitive_test.go
Labels: consensus, monitoring

#2382 [WIP] P-Chain merkle DB -- smaller diff
  vms/platformvm/state/diff.go
  vms/platformvm/state/masked_iterator_test.go
  vms/platformvm/state/staker_test.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_load_ops.go
  vms/platformvm/state/state_test.go
  vms/platformvm/txs/executor/staker_tx_verification.go
  vms/platformvm/vm_regression_test.go
Labels: merkledb

#2389 Rename `D` to `Durango`
  node/node.go
  version/constants.go
  vms/platformvm/config/config.go
  vms/platformvm/txs/executor/staker_tx_verification.go
  vms/platformvm/txs/executor/standard_tx_executor.go
Labels: cleanup

#2367 Replace periodic push accepted gossip with pull preference gossip for block discovery
  chains/manager.go
  config/config.go
  config/flags.go
  config/keys.go
  node/config.go
  node/node.go
  node/overridden_manager.go
  snow/engine/snowman/transitive.go
  snow/engine/snowman/transitive_test.go
  snow/validators/manager.go
  snow/validators/set.go
  utils/constants/networking.go
Labels: consensus, networking

#2324 MerkleDB Remove ID from Node to reduce size and removal channel creation.
  x/merkledb/codec.go
  x/merkledb/codec_test.go
  x/merkledb/db.go
  x/merkledb/history_test.go
  x/merkledb/node.go
  x/merkledb/proof.go
  x/merkledb/trieview.go
Labels: merkledb

#2395 Remove method `CappedList` from `set.Set`
  snow/engine/avalanche/bootstrap/bootstrapper.go
  utils/set/set.go
  utils/set/set_test.go
Labels: cleanup

#2399 Periodically PullGossip only from connected validators
  chains/manager.go
  node/overridden_manager.go
  snow/engine/common/tracker/peers.go
  snow/engine/snowman/config.go
  snow/engine/snowman/config_test.go
  snow/engine/snowman/transitive.go
  snow/engine/snowman/transitive_test.go
  snow/validators/manager.go
  snow/validators/set.go
  utils/set/set.go
Labels: bug, consensus, networking

#2396 Update bootstrap IPs
  genesis/bootstrappers.json
Labels: networking

#2307 Rename `testnet` fixture to `tmpnet`
  .github/workflows/test.e2e.existing.yml
  .github/workflows/test.e2e.yml
  .github/workflows/test.upgrade.yml
  scripts/build_tmpnetctl.sh
  scripts/tests.e2e.existing.sh
  scripts/tests.e2e.persistent.sh
  scripts/tests.e2e.sh
  tests/e2e/README.md
  tests/e2e/c/dynamic_fees.go
  tests/e2e/faultinjection/duplicate_node_id.go
  tests/e2e/p/interchain_workflow.go
  tests/e2e/p/staking_rewards.go
  tests/e2e/p/workflow.go
  tests/fixture/e2e/env.go
  tests/fixture/e2e/flags.go
  tests/fixture/e2e/helpers.go
  tests/fixture/testnet/README.md
  tests/fixture/tmpnet/README.md
  tests/fixture/tmpnet/cmd/main.go
  tests/fixture/tmpnet/common.go
  tests/fixture/tmpnet/config.go
  tests/fixture/tmpnet/interfaces.go
  tests/fixture/tmpnet/local/README.md
  tests/fixture/tmpnet/local/config.go
  tests/fixture/tmpnet/local/network.go
  tests/fixture/tmpnet/local/network_test.go
  tests/fixture/tmpnet/local/node.go
  tests/fixture/tmpnet/local/node_test.go
Labels: testing

#2402 `vms/platformvm`: Move `GetRewardUTXOs`, `GetSubnets`, and `GetChains` to `State` interface
  vms/platformvm/state/diff.go
  vms/platformvm/state/diff_test.go
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/state.go
Labels: cleanup
