Repository ava-labs/avalanchego, pull requests merged in 2023-07, with the labels that each got.

#1684 `sync` -- add exponential backoff
  x/sync/client.go
Labels: merkledb

#1683 Mark preForkBlocks after the fork as Rejected
  vms/proposervm/pre_fork_block.go
  vms/proposervm/vm.go
  vms/proposervm/vm_byzantine_test.go
  vms/proposervm/vm_test.go
Labels: bug, vm

#1675 `merkledb` -- fix comment
  x/merkledb/history.go
Labels: merkledb

#1670 `MerkleDB` -- document codec
  x/merkledb/README.md
Labels: documentation

#1680 `sync` -- client cleanup
  x/sync/client.go
  x/sync/network_client.go
Labels: cleanup, merkledb

#1669 Update version to v1.10.4
  RELEASES.md
  version/compatibility.json
  version/constants.go
Labels: documentation

#1696 stop persisting rejected blocks on P-chain
  vms/platformvm/blocks/executor/acceptor.go
  vms/platformvm/blocks/executor/acceptor_test.go
  vms/platformvm/blocks/executor/rejector.go
  vms/platformvm/blocks/executor/rejector_test.go
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/state.go
Labels: vm

#1711 Ensure scripts/lint.sh failure when used with incompatible grep
  scripts/lint.sh
Labels: testing

#1695 sum peers clock skew into metric
  network/peer/metrics.go
  network/peer/peer.go
Labels: monitoring

#1699 Make AVM implement `block.HeightIndexedChainVM`
  chains/linearizable_vm.go
  chains/manager.go
  vms/avm/service.go
  vms/avm/service_test.go
  vms/avm/states/diff.go
  vms/avm/states/mock_states.go
  vms/avm/states/state.go
  vms/avm/states/state_test.go
  vms/avm/vm.go
Labels: vm

#1688 ProposerVM nits
  vms/proposervm/tree/tree.go
  vms/proposervm/tree/tree_test.go
Labels: documentation, vm, testing

#1703 Update snow consensus doc post X-chain linearization
  snow/README.md
Labels: documentation

#1718 `merkledb` / `sync` -- remove TODOs
  x/merkledb/db.go
  x/sync/manager.go
  x/sync/network_client.go
Labels: merkledb

#1721 remove cache TODOs
  x/merkledb/db.go
Labels: merkledb

#1704 Wallet issuance to return tx instead of tx id
  tests/e2e/banff/suites.go
  tests/e2e/p/permissionless_subnets.go
  tests/e2e/p/workflow.go
  tests/e2e/x/transfer/virtuous.go
  wallet/chain/p/wallet.go
  wallet/chain/p/wallet_with_options.go
  wallet/chain/x/wallet.go
  wallet/chain/x/wallet_with_options.go
  wallet/subnet/primary/example_test.go
  wallet/subnet/primary/examples/add-permissioned-subnet-validator/main.go
  wallet/subnet/primary/examples/add-primary-validator/main.go
  wallet/subnet/primary/examples/create-asset/main.go
  wallet/subnet/primary/examples/create-chain/main.go
  wallet/subnet/primary/examples/create-locked-stakeable/main.go
  wallet/subnet/primary/examples/create-subnet/main.go
  wallet/subnet/primary/examples/remove-subnet-validator/main.go
Labels: enhancement

#1727 Add support for providing tracing headers
  config/config.go
  config/flags.go
  config/keys.go
Labels: enhancement

#1724 Only return accepted blocks in `GetStatelessBlock`
  vms/platformvm/blocks/executor/backend.go
  vms/platformvm/blocks/executor/backend_test.go
  vms/platformvm/blocks/executor/block.go
  vms/platformvm/blocks/executor/block_test.go
  vms/platformvm/blocks/executor/manager_test.go
  vms/platformvm/blocks/executor/proposal_block_test.go
  vms/platformvm/blocks/executor/standard_block_test.go
  vms/platformvm/blocks/executor/verifier_test.go
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/state.go
  vms/platformvm/txs/tx.go
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/validators/manager.go
  vms/platformvm/validators/manager_test.go
Labels: vm

#1713 Proposermv fix goroutine leaks
  go.mod
  go.sum
  vms/proposervm/batched_vm_test.go
  vms/proposervm/main_test.go
  vms/proposervm/post_fork_block_test.go
  vms/proposervm/post_fork_option_test.go
  vms/proposervm/pre_fork_block_test.go
  vms/proposervm/scheduler/scheduler.go
  vms/proposervm/state_syncable_vm_test.go
  vms/proposervm/vm.go
  vms/proposervm/vm_byzantine_test.go
  vms/proposervm/vm_test.go
Labels: testing, cleanup

#1686 Update warp msg format
  chains/manager.go
  proto/pb/warp/message.pb.go
  proto/warp/message.proto
  vms/platformvm/warp/gwarp/client.go
  vms/platformvm/warp/gwarp/server.go
  vms/platformvm/warp/gwarp/signer_test.go
  vms/platformvm/warp/message_test.go
  vms/platformvm/warp/signature.go
  vms/platformvm/warp/signature_test.go
  vms/platformvm/warp/signer.go
  vms/platformvm/warp/signer_test.go
  vms/platformvm/warp/test_signer.go
  vms/platformvm/warp/unsigned_message.go
  vms/platformvm/warp/unsigned_message_test.go
Labels: warp

#1714 Cleanup anr scripts
  scripts/install_anr.sh
  scripts/tests.e2e.sh
  scripts/tests.upgrade.sh
Labels: testing, ci, cleanup

#1716 remove TrackBandwidth from NetworkClient
  x/sync/client.go
  x/sync/network_client.go
Labels: merkledb

#1734 e2e: Ensure e2e.test is built with portable BLST
  scripts/install_anr.sh
  scripts/tests.e2e.sh
  scripts/tests.upgrade.sh
Labels: bug, testing, ci

#1712 Remove deprecated configs
  config/config.go
  config/flags.go
  config/keys.go
  scripts/install_anr.sh
Labels: cleanup

#1737 upgrade: Increase all ANR timeouts to 2m to ensure CI reliability
  tests/upgrade/upgrade_test.go
Labels: testing

#1736 fix sync panic
  x/sync/manager.go
Labels: bug, merkledb

#1739 remove `vm.state` re-assignment in tests
  vms/platformvm/vm_regression_test.go
Labels: testing, cleanup

#1740 Expose BLS public keys from platform.getValidatorsAt
  vms/platformvm/client.go
  vms/platformvm/service.go
  vms/platformvm/service_test.go
Labels: enhancement, vm

#1744 Fix validator set diff tests
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/vm_regression_test.go
Labels: testing

#1745 Replace List() with Map() on validators.Set
  snow/engine/common/bootstrapper.go
  snow/engine/snowman/syncer/state_syncer.go
  snow/engine/snowman/syncer/state_syncer_test.go
  snow/networking/handler/health_test.go
  snow/validators/manager.go
  snow/validators/manager_test.go
  snow/validators/mock_set.go
  snow/validators/set.go
  snow/validators/set_test.go
  vms/platformvm/blocks/builder/helpers_test.go
  vms/platformvm/blocks/executor/helpers_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/validators/manager.go
  vms/platformvm/validators/manager_test.go
  vms/platformvm/vm_test.go
Labels: warp

#1677 vms/platformvm: configure state cache sizes #1522
  vms/platformvm/blocks/builder/helpers_test.go
  vms/platformvm/blocks/executor/helpers_test.go
  vms/platformvm/config/execution_config.go
  vms/platformvm/config/execution_config_test.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/vm.go
  vms/platformvm/vm_regression_test.go
Labels: vm

#1748 Support both `stateBlk`s and `Block`s in `blockDB`
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
Labels: vm

#1749 Add `DefaultExecutionConfig` var to `platformvm`
  vms/platformvm/config/execution_config.go
  vms/platformvm/config/execution_config_test.go
Labels: cleanup

#1758 Remove hanging TODO from prior change
  config/flags.go
Labels: cleanup

#1729 Write process context on node start to simplify test orchestration
  api/server/mock_server.go
  api/server/server.go
  config/config.go
  config/flags.go
  config/keys.go
  node/config.go
  node/node.go
Labels: testing, cleanup

#1756 x/sync: add locks for peerTracker
  x/sync/network_client.go
  x/sync/peer_tracker.go
Labels: merkledb

#1759 Add ids length constants
  ids/id.go
  ids/node_id.go
  ids/short.go
  indexer/indexer.go
  snow/engine/avalanche/state/state.go
  x/merkledb/codec.go
  x/sync/network_server.go
Labels: cleanup

#1763 [x/sync] Update target locking
  x/sync/manager.go
Labels: bug, merkledb

#1771 Export warp errors for external use
  vms/platformvm/warp/signature.go
  vms/platformvm/warp/signature_test.go
  vms/platformvm/warp/signer.go
  vms/platformvm/warp/test_signer.go
Labels: cleanup, warp

#1774 Remove unused networking constant
  utils/constants/networking.go
Labels: cleanup

#1773 Change the default value of `--network-allow-private-ips` to `false` for `mainnet` and `fuji`
  config/config.go
  config/flags.go
  network/test_network.go
  utils/constants/network_ids.go
  utils/constants/networking.go
Labels: networking

#1778 Remove context.TODO from tests
  snow/networking/handler/handler_test.go
  vms/proposervm/vm_test.go
Labels: testing, cleanup

#1752 Replace linkeddb iterator with native DB range queries
  database/helpers.go
  scripts/build_fuzz.sh
  scripts/mocks.mockgen.txt
  vms/platformvm/config/execution_config.go
  vms/platformvm/config/execution_config_test.go
  vms/platformvm/state/disk_staker_diff_iterator.go
  vms/platformvm/state/disk_staker_diff_iterator_test.go
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
  vms/platformvm/validators/manager.go
  vms/platformvm/validators/manager_benchmark_test.go
  vms/platformvm/validators/manager_test.go
Labels: vm, storage

#1781 Add support for measuring key size in caches
  cache/lru_sized_cache.go
  cache/lru_sized_cache_test.go
  cache/test_cacher.go
  vms/platformvm/state/state.go
Labels: sdk
