Repository ava-labs/avalanchego, pull requests merged in 2023-04, with the labels that each got.

#1279 use `require` in `snow/choices` tests
  snow/choices/status_test.go
Labels: testing, cleanup

#1273 add support for tracking delegatee rewards to validator metadata
  vms/platformvm/state/state.go
  vms/platformvm/state/validator_metadata.go
  vms/platformvm/state/validator_metadata_test.go
  vms/platformvm/state/validator_uptimes.go
  vms/platformvm/state/validator_uptimes_test.go
Labels: vm

#1283 Initialize UptimeCalculator in TestPeer
  network/peer/test_peer.go
Labels: bug, networking

#1287 Add Avalanche liveness health checks
  snow/consensus/avalanche/topological.go
  snow/consensus/snowstorm/directed.go
Labels: monitoring, incident response

#1290 Use `maps.Equal` in `set.Equals`
  utils/set/set.go
Labels: cleanup

#1291 return accrued delegator rewards in `GetCurrentValidators`
  vms/platformvm/api/static_service.go
  vms/platformvm/client_permissionless_validator.go
  vms/platformvm/service.go
  vms/platformvm/service_test.go
Labels: enhancement

#1278 Add zstd compression
  config/config.go
  config/flags.go
  config/keys.go
  go.mod
  go.sum
  message/creator.go
  message/inbound_msg_builder_test.go
  message/messages.go
  message/messages_benchmark_test.go
  message/messages_test.go
  message/outbound_msg_builder.go
  message/outbound_msg_builder_test.go
  network/config.go
  network/network_test.go
  network/peer/peer_test.go
  network/peer/test_peer.go
  network/test_network.go
  node/node.go
  proto/p2p/p2p.proto
  proto/pb/p2p/p2p.pb.go
  snow/networking/sender/sender_test.go
  utils/compression/compressor_test.go
  utils/compression/gzip_compressor.go
  utils/compression/gzip_compressor_test.go
  utils/compression/type.go
  utils/compression/type_test.go
  utils/compression/zstd_compressor.go
  utils/constants/networking.go
  vms/platformvm/vm_test.go
Labels: enhancement, networking

#1293 Parallelize gzip compression
  utils/compression/compressor_test.go
  utils/compression/gzip_compressor.go
Labels: networking, cleanup

#1300 Add zip bomb tests
  utils/compression/compressor_test.go
  utils/compression/gzip_zip_bomb.bin
  utils/compression/zstd_zip_bomb.bin
Labels: testing, networking

#1303 Gossip Avalanche frontier after the linearization
  snow/networking/handler/handler.go
Labels: bug, consensus, networking

#1301 Add fine grained metrics+logging for handling, processing, and grab l…
  snow/networking/handler/handler.go
  snow/networking/handler/metrics.go
Labels: monitoring

#1305 Persist stateless block in AVM state
  vms/avm/blocks/executor/block.go
  vms/avm/blocks/executor/block_test.go
Labels: bug, vm

#1306 Initialize FxID fields in GetBlock and GetBlockByHeight
  vms/avm/service.go
  vms/avm/service_test.go
Labels: bug, vm

#1304 Filterable Health Tags
  api/health/client.go
  api/health/client_test.go
  api/health/handler.go
  api/health/health.go
  api/health/health_test.go
  api/health/service.go
  api/health/service_test.go
  api/health/worker.go
  chains/manager.go
  node/node.go
Labels: monitoring, incident response

#1317 increase health await timeout
  api/health/health_test.go
Labels: testing

#1316 Expose GetEngineManager from the chain Handler
  snow/networking/handler/handler.go
  snow/networking/handler/mock_handler.go
Labels: consensus, testing

#1318 Add BLS benchmarks
  utils/crypto/bls/bls_benchmark_test.go
  utils/crypto/secp256k1/secp256k1_benchmark_test.go
Labels: benchmarking

#1322 Expose consensus-app-concurrency
  chains/manager.go
  config/config.go
  config/flags.go
  config/keys.go
  node/config.go
  node/node.go
  snow/networking/handler/handler.go
  snow/networking/handler/handler_test.go
  snow/networking/router/chain_router_test.go
  snow/networking/sender/sender_test.go
  utils/constants/networking.go
  vms/platformvm/vm_test.go
Labels: enhancement

#1310 Adjust Logic In Merkle DB History
  x/merkledb/history.go
Labels: merkledb

#1325 Cleanup goroutines on health.Stop
  api/health/health.go
  api/health/worker.go
Labels: monitoring, cleanup

#1326 Add benchmark for gRPC GetValidatorSet
  snow/validators/gvalidators/validator_state_test.go
Labels: sdk, benchmarking

#1333 Add checks for database being closed in merkledb; other nits
  x/merkledb/db.go
  x/merkledb/trieview.go
Labels: merkledb

#1329 Update linkedhashmap to only Rlock when possible
  utils/linkedhashmap/linkedhashmap.go
Labels: cleanup

#1341 Cleanup type assertions in the linkedHashmap
  utils/linkedhashmap/iterator.go
  utils/linkedhashmap/linkedhashmap.go
Labels: cleanup

#1349 Fix racy avm tx access
  vms/avm/network/network.go
Labels: bug, vm

#1354 Update Fuji beacon ips
  genesis/beacons.go
Labels: networking

#1364 Remove duplicate TLS verification
  staking/tls.go
  vms/proposervm/block/block.go
Labels: cleanup

#1355 Adjust Merkledb Trie invalidation locking
  x/merkledb/trieview.go
Labels: merkledb

#1344 Use require in Avalanche bootstrapping tests
  snow/engine/avalanche/bootstrap/bootstrapper_test.go
  snow/state.go
Labels: testing

#1269 Add Proof size limit to sync client
  x/sync/README.md
  x/sync/client.go
  x/sync/client_test.go
  x/sync/network_server.go
  x/sync/network_server_test.go
  x/sync/request.go
  x/sync/sync_test.go
  x/sync/syncmanager.go
Labels: merkledb

#1375 Add stake priority helpers
  vms/platformvm/txs/executor/staker_tx_verification.go
  vms/platformvm/txs/priorities.go
  vms/platformvm/txs/priorities_test.go
Labels: enhancement, cleanup

#1373 add contribution file
  CONTRIBUTING.md
Labels: documentation

#1374 Remove max sample value
  genesis/beacons.go
  go.mod
  go.sum
  network/network.go
  network/peer/set.go
  snow/consensus/snowball/network_test.go
  snow/consensus/snowman/network_test.go
  snow/consensus/snowstorm/network_test.go
  snow/engine/avalanche/transitive.go
  utils/sampler/rand.go
  utils/sampler/rand_test.go
  utils/sampler/uniform.go
  utils/sampler/uniform_benchmark_test.go
  utils/sampler/uniform_best.go
  utils/sampler/uniform_replacer.go
  utils/sampler/uniform_resample.go
  utils/sampler/uniform_test.go
  utils/sampler/weighted_benchmark_test.go
  utils/sampler/weighted_best.go
  utils/sampler/weighted_without_replacement_generic.go
  vms/avm/service_test.go
Labels: cleanup

#1323 Prefetch rpcdb iterator batches
  database/rpcdb/db_client.go
Labels: enhancement

#1378 Temp fix for flaky Sync Test
  x/sync/syncmanager.go
Labels: bug, merkledb

#1353 Update merkle cache to be FIFO instead of LRU
  x/merkledb/cache.go
  x/merkledb/cache_test.go
Labels: merkledb

#1343 Improve cost of BLS key serialization for gRPC
  snow/validators/gvalidators/validator_state_client.go
  snow/validators/gvalidators/validator_state_server.go
  snow/validators/gvalidators/validator_state_test.go
Labels: sdk, benchmarking

#1377 Add ValidatorsOnly flag to GetStake
  vms/platformvm/client.go
  vms/platformvm/service.go
  vms/platformvm/service_test.go
Labels: enhancement, vm

#1336 Use proto in `x/sync`
  proto/pb/sync/sync.pb.go
  proto/sync/sync.proto
  x/sync/client.go
  x/sync/client_test.go
  x/sync/codec.go
  x/sync/mock_client.go
  x/sync/network_server.go
  x/sync/network_server_test.go
  x/sync/sync_test.go
  x/sync/syncmanager.go
Labels: merkledb

#1392 Update incorrect fuji beacon IPs
  genesis/beacons.go
Labels: bug

#1393 Update `api/` error handling
  api/admin/client.go
  api/admin/client_test.go
  api/admin/service_test.go
  api/auth/auth.go
  api/auth/auth_test.go
  api/health/client_test.go
  api/info/service_test.go
  api/metrics/multi_gatherer_test.go
  api/metrics/optional_gatherer_test.go
  utils/logging/level.go
  utils/password/password.go
Labels: testing, cleanup

#1347 refactor concurrent work limiting in sync in `x/sync`
  x/sync/syncmanager.go
Labels: merkledb

#1348 Remove check for impossible condition in `x/sync`
  x/sync/network_client.go
Labels: merkledb

#1396 Improve `codec/` error handling
  codec/codec.go
  codec/hierarchycodec/codec.go
  codec/linearcodec/codec.go
  codec/manager.go
  codec/reflectcodec/struct_fielder.go
  codec/reflectcodec/type_codec.go
  codec/registry.go
  codec/test_codec.go
Labels: testing, cleanup

#1397 Improve `config/` error handling
  config/config.go
  config/config_test.go
  snow/consensus/avalanche/parameters.go
  snow/consensus/snowball/parameters.go
  subnets/config.go
  subnets/config_test.go
Labels: testing, cleanup

#1398 Improve `genesis/` error handling
  genesis/config.go
  genesis/genesis.go
  genesis/genesis_test.go
Labels: testing, cleanup

#1399 Improve various error handling locations
  database/leveldb/db.go
  database/manager/manager_test.go
  indexer/index.go
  indexer/index_test.go
  network/dialer/dialer_test.go
  network/network_test.go
  network/throttling/dial_throttler_test.go
  network/throttling/inbound_conn_throttler_test.go
  utils/metric/averager.go
  version/parser.go
  version/parser_test.go
Labels: testing, cleanup

#1400 Improve `utils/` error handling
  utils/buffer/bounded_nonblocking_queue_test.go
  utils/cb58/cb58.go
  utils/compression/compressor_test.go
  utils/compression/type_test.go
  utils/crypto/bls/public.go
  utils/crypto/bls/public_test.go
  utils/crypto/bls/signature.go
  utils/crypto/keychain/keychain_test.go
  utils/crypto/secp256k1/secp256k1.go
  utils/crypto/secp256k1/secp256k1_test.go
  utils/dynamicip/resolver.go
  utils/dynamicip/resolver_test.go
  utils/hashing/consistent/ring_test.go
  utils/profiler/profiler_test.go
  utils/sampler/uniform_replacer.go
  utils/sampler/uniform_resample.go
  utils/sampler/uniform_test.go
  utils/sampler/weighted.go
  utils/sampler/weighted_array.go
  utils/sampler/weighted_heap.go
  utils/sampler/weighted_linear.go
  utils/sampler/weighted_test.go
  utils/sampler/weighted_uniform.go
  utils/sampler/weighted_without_replacement_test.go
  utils/wrappers/packing.go
  utils/wrappers/packing_test.go
Labels: testing, cleanup

#1401 Improve consensus error handling
  snow/choices/status_test.go
  snow/engine/avalanche/vertex/builder_test.go
  snow/engine/avalanche/vertex/parser_test.go
  snow/engine/common/queue/jobs_test.go
  snow/uptime/manager_test.go
  snow/validators/gvalidators/validator_state_test.go
  snow/validators/set_test.go
  vms/avm/index_test.go
  vms/avm/service_test.go
  vms/components/chain/state.go
  vms/components/chain/state_test.go
  vms/components/index/index.go
  vms/components/keystore/user_test.go
  vms/components/message/message_test.go
  vms/proposervm/batched_vm_test.go
  vms/proposervm/block/block.go
  vms/proposervm/block/block_test.go
  vms/proposervm/block/build_test.go
  vms/proposervm/block/parse_test.go
  vms/proposervm/indexer/height_indexer_test.go
  vms/proposervm/summary/parse_test.go
  vms/registry/vm_registerer.go
  vms/registry/vm_registerer_test.go
  vms/rpcchainvm/state_syncable_vm_test.go
Labels: testing, cleanup

#1402 Improve secp256k1fx + merkledb error handling
  vms/secp256k1fx/fx_test.go
  vms/secp256k1fx/input.go
  vms/secp256k1fx/input_test.go
  vms/secp256k1fx/mint_operation_test.go
  vms/secp256k1fx/mint_output.go
  vms/secp256k1fx/mint_output_test.go
  vms/secp256k1fx/output_owners.go
  vms/secp256k1fx/output_owners_test.go
  vms/secp256k1fx/transfer_input.go
  vms/secp256k1fx/transfer_input_test.go
  vms/secp256k1fx/transfer_output.go
  vms/secp256k1fx/transfer_output_test.go
  x/merkledb/db_test.go
  x/merkledb/history_test.go
  x/merkledb/trie_test.go
Labels: testing, cleanup

#1346 Ban usage of require.Error
  .golangci.yml
  chains/atomic/test_shared_memory.go
  ids/aliases.go
  ids/test_aliases.go
  vms/platformvm/api/static_service.go
  vms/platformvm/api/static_service_test.go
  vms/platformvm/blocks/builder/builder.go
  vms/platformvm/blocks/builder/builder_test.go
  vms/platformvm/blocks/executor/acceptor.go
  vms/platformvm/blocks/executor/acceptor_test.go
  vms/platformvm/blocks/executor/manager_test.go
  vms/platformvm/blocks/executor/proposal_block_test.go
  vms/platformvm/blocks/executor/standard_block_test.go
  vms/platformvm/blocks/executor/verifier.go
  vms/platformvm/blocks/executor/verifier_test.go
  vms/platformvm/service_test.go
  vms/platformvm/signer/proof_of_possession_test.go
  vms/platformvm/state/diff_test.go
  vms/platformvm/state/state_test.go
  vms/platformvm/state/validator_metadata_test.go
  vms/platformvm/status/blockchain_status.go
  vms/platformvm/status/blockchain_status_test.go
  vms/platformvm/status/status_test.go
  vms/platformvm/txs/add_delegator_test.go
  vms/platformvm/txs/add_delegator_tx.go
  vms/platformvm/txs/add_permissionless_delegator_tx_test.go
  vms/platformvm/txs/add_permissionless_validator_tx_test.go
  vms/platformvm/txs/add_subnet_validator_test.go
  vms/platformvm/txs/add_validator_test.go
  vms/platformvm/txs/add_validator_tx.go
  vms/platformvm/txs/builder/builder.go
  vms/platformvm/txs/create_chain_test.go
  vms/platformvm/txs/executor/advance_time_test.go
  vms/platformvm/txs/executor/atomic_tx_executor.go
  vms/platformvm/txs/executor/create_chain_test.go
  vms/platformvm/txs/executor/export_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/txs/executor/import_test.go
  vms/platformvm/txs/executor/proposal_tx_executor.go
  vms/platformvm/txs/executor/proposal_tx_executor_test.go
  vms/platformvm/txs/executor/reward_validator_test.go
  vms/platformvm/txs/executor/staker_tx_verification.go
  vms/platformvm/txs/executor/staker_tx_verification_test.go
  vms/platformvm/txs/executor/standard_tx_executor.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/txs/executor/state_changes.go
  vms/platformvm/txs/executor/tx_mempool_verifier.go
  vms/platformvm/txs/remove_subnet_validator_tx.go
  vms/platformvm/txs/remove_subnet_validator_tx_test.go
  vms/platformvm/txs/transform_subnet_tx_test.go
  vms/platformvm/utxo/handler.go
  vms/platformvm/utxo/handler_test.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
  vms/platformvm/warp/message_test.go
  vms/platformvm/warp/test_signer.go
  vms/platformvm/warp/unsigned_message_test.go
Labels: testing, ci, cleanup

#1350 Remove slice capacity hint in `x/sync`
  x/sync/syncmanager.go
  x/sync/syncworkheap.go
  x/sync/syncworkheap_test.go
Labels: merkledb

#1351 Simplify `syncWorkHeap` less function in `x/sync`
  x/sync/syncworkheap.go
Labels: merkledb

#1404 Replace `switch` with `txs.Visitor` in X chain signer
  wallet/chain/x/signer.go
  wallet/chain/x/signer_visitor.go
Labels: cleanup

#1408 Include IDs in json marshalling
  vms/avm/blocks/standard_block.go
  vms/avm/service_test.go
  vms/avm/txs/tx.go
  vms/platformvm/blocks/common_block.go
  vms/platformvm/txs/tx.go
Labels: enhancement, vm

#1331 Adjust find next key logic in x/Sync
  x/sync/sync_test.go
  x/sync/syncmanager.go
Labels: merkledb

#1342 Remove bitmask from writeMsgLen
  network/peer/msg_length.go
  network/peer/msg_length_test.go
Labels: networking, cleanup

#1411 Require `txID`s in PeerList messages
  network/peer/peer.go
Labels: networking, cleanup

#1413 Allow dependent tx issuance over the wallet API
  vms/avm/wallet_service.go
Labels: vm

#1332 Add support for proto `message.Tx` decoding
  proto/message/tx.proto
  proto/pb/message/tx.pb.go
  vms/components/message/message.go
  vms/components/message/message_test.go
Labels: enhancement, networking

#1345 Remove avalanche bootstrapping -> avalanche consensus transition
  .github/workflows/test.e2e.yml
  chains/manager.go
  scripts/tests.e2e.sh
  snow/engine/avalanche/bootstrap/bootstrapper.go
  snow/engine/avalanche/bootstrap/bootstrapper_test.go
  snow/engine/avalanche/bootstrap/config.go
  snow/engine/avalanche/transitive_test.go
  snow/networking/handler/handler.go
  tests/e2e/e2e_test.go
  tests/e2e/x/transfer/virtuous.go
  tests/e2e/x/whitelist-vtx/suites.go
Labels: consensus, cleanup

#1417 Benchmark get canonical validator set
  vms/platformvm/warp/validator_test.go
Labels: sdk, benchmarking, warp

#1421 Simplify IP status calculation
  network/network.go
Labels: networking, cleanup

#1416 Update BLS signature ordering to avoid public key compression
  vms/platformvm/warp/signature_test.go
  vms/platformvm/warp/validator.go
  vms/platformvm/warp/validator_test.go
Labels: benchmarking, warp

#1359 Remove DAG based consensus
  chains/manager.go
  config/config.go
  config/config_test.go
  config/flags.go
  config/keys.go
  snow/consensus/avalanche/consensus.go
  snow/consensus/avalanche/consensus_test.go
  snow/consensus/avalanche/factory.go
  snow/consensus/avalanche/parameters.go
  snow/consensus/avalanche/parameters_test.go
  snow/consensus/avalanche/poll/early_term_no_traversal.go
  snow/consensus/avalanche/poll/early_term_no_traversal_test.go
  snow/consensus/avalanche/poll/interfaces.go
  snow/consensus/avalanche/poll/no_early_term.go
  snow/consensus/avalanche/poll/no_early_term_test.go
  snow/consensus/avalanche/poll/set.go
  snow/consensus/avalanche/poll/set_test.go
  snow/consensus/avalanche/test_vertex.go
  snow/consensus/avalanche/topological.go
  snow/consensus/avalanche/topological_test.go
  snow/consensus/avalanche/traced_consensus.go
  snow/consensus/avalanche/transaction_vertex.go
  snow/consensus/avalanche/vertex.go
  snow/consensus/snowstorm/acceptor.go
  snow/consensus/snowstorm/benchmark_test.go
  snow/consensus/snowstorm/consensus.go
  snow/consensus/snowstorm/consensus_test.go
  snow/consensus/snowstorm/directed.go
  snow/consensus/snowstorm/directed_test.go
  snow/consensus/snowstorm/factory.go
  snow/consensus/snowstorm/network_test.go
  snow/consensus/snowstorm/rejector.go
  snow/consensus/snowstorm/snowball.go
  snow/consensus/snowstorm/stringer.go
  snow/consensus/snowstorm/stringer_test.go
  snow/consensus/snowstorm/test_tx.go
  snow/consensus/snowstorm/tx.go
  snow/engine/avalanche/bootstrap/bootstrapper.go
  snow/engine/avalanche/config.go
  snow/engine/avalanche/config_test.go
  snow/engine/avalanche/engine.go
  snow/engine/avalanche/issuer.go
  snow/engine/avalanche/metrics.go
  snow/engine/avalanche/state/serializer.go
  snow/engine/avalanche/state/unique_vertex.go
  snow/engine/avalanche/state/unique_vertex_test.go
  snow/engine/avalanche/test_engine.go
  snow/engine/avalanche/traced_engine.go
  snow/engine/avalanche/transitive.go
  snow/engine/avalanche/transitive_test.go
  snow/engine/avalanche/vertex/builder.go
  snow/engine/avalanche/vertex/test_builder.go
  snow/engine/avalanche/voter.go
  snow/engine/avalanche/voter_test.go
  snow/engine/common/no_ops_handlers.go
  subnets/config.go
  subnets/config_test.go
  vms/avm/unique_tx.go
Labels: consensus, cleanup

#1419 Remove IssueStopVertex message
  snow/engine/common/message.go
  vms/avm/client.go
  vms/avm/service.go
  vms/avm/vm.go
Labels: consensus, vm, cleanup

#1432 Fix msgHandlingTime
  snow/networking/handler/handler.go
Labels: bug, monitoring, incident response

#1385 Change ChangeProofs to only have one list of key/value change instead of key/values and deleted
  x/merkledb/codec.go
  x/merkledb/codec_test.go
  x/merkledb/db.go
  x/merkledb/db_test.go
  x/merkledb/proof.go
  x/merkledb/proof_test.go
  x/sync/client.go
  x/sync/client_test.go
  x/sync/network_server.go
  x/sync/network_server_test.go
  x/sync/syncmanager.go
Labels: cleanup, merkledb

#1289 Update AMI generation workflow
  .github/packer/roles/public-ami/defaults/main.yml
  .github/packer/roles/public-ami/tasks/main.yml
  .github/packer/roles/public-ami/templates/C/config.json.j2
  .github/packer/ubuntu-jammy-x86_64-public-ami.json
  .github/workflows/amichange.json
  .github/workflows/build-public-ami.yml
  .github/workflows/update-ami.py
Labels: ci

#1437 Support `height` as a string in `avm.getBlockByHeight`
  api/common_args_responses.go
  vms/avm/client.go
  vms/avm/service.go
  vms/avm/service_test.go
Labels: bug, vm

#1442 Defer parser initialization to Start
  chains/manager.go
  snow/engine/avalanche/bootstrap/bootstrapper.go
  snow/engine/avalanche/bootstrap/bootstrapper_test.go
  snow/engine/snowman/bootstrap/block_job.go
  snow/engine/snowman/bootstrap/bootstrapper.go
  snow/engine/snowman/bootstrap/bootstrapper_test.go
  vms/platformvm/vm_test.go
Labels: bug, consensus

#1446 Cleanup proposervm ancestors packing
  vms/proposervm/batched_vm.go
  vms/proposervm/batched_vm_test.go
Labels: vm, cleanup
