Repository ava-labs/avalanchego, pull requests merged in 2023-09, with the labels that each got.

#1959 `merkledb` -- remove unneeded return values
  x/merkledb/db.go
  x/merkledb/node.go
  x/merkledb/node_test.go
  x/merkledb/trieview.go
Labels: cleanup, merkledb

#1962 `sync` -- reduce test sizes
  x/sync/network_server_test.go
  x/sync/sync_test.go
Labels: testing, merkledb

#1960 `merkledb` -- limit number of goroutines calculating node IDs
  x/merkledb/db.go
  x/merkledb/trieview.go
Labels: cleanup, merkledb

#1958 Add gossip package to p2p SDK
  network/p2p/gossip/bloom.go
  network/p2p/gossip/bloom_test.go
  network/p2p/gossip/gossip.go
  network/p2p/gossip/gossip_test.go
  network/p2p/gossip/gossipable.go
  network/p2p/gossip/handler.go
  network/p2p/gossip/test_gossip.go
  proto/pb/sdk/sdk.pb.go
  proto/sdk/sdk.proto
Labels: networking, sdk

#1955 Improve state sync logging
  snow/engine/snowman/syncer/state_syncer.go
Labels: monitoring

#1826 Update golang to 1.20.8
  .github/workflows/auto-generated-checker.yml
  .github/workflows/build-and-test.yml
  .github/workflows/build-linux-binaries.yml
  .github/workflows/build-macos-release.yml
  .github/workflows/build-public-ami.yml
  .github/workflows/build-ubuntu-amd64-release.yml
  .github/workflows/build-ubuntu-arm64-release.yml
  .github/workflows/build-win-release.yml
  .github/workflows/fuzz.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test.e2e.persistent.yml
  .github/workflows/test.e2e.yml
  .github/workflows/test.upgrade.yml
  .golangci.yml
  CONTRIBUTING.md
  Dockerfile
  README.md
  config/config.go
  config/flags.go
  database/leveldb/db.go
  genesis/config.go
  go.mod
  proto/Dockerfile.buf
  scripts/build_avalanche.sh
  snow/engine/snowman/transitive.go
  snow/networking/handler/health.go
  tests/fixture/testnet/local/network.go
  utils/cb58/cb58.go
  utils/metric/averager.go
  vms/components/avax/utxo_id.go
  vms/platformvm/txs/executor/staker_tx_verification.go
  vms/platformvm/txs/executor/subnet_tx_verification.go
  vms/platformvm/warp/signature.go
  vms/platformvm/warp/validator.go
  vms/proposervm/block/block.go
  vms/rpcchainvm/runtime/subprocess/runtime.go
  x/sync/client.go
  x/sync/network_client.go
  x/sync/network_server.go
Labels: ci

#1975 Use odd-numbered request ids for SDK
  network/p2p/client.go
  network/p2p/router.go
  network/p2p/router_test.go
Labels: networking, sdk

#1978 update iterator invariant
  database/iterator.go
Labels: documentation

#1981 Document common usage of requestIDs for snow senders
  snow/engine/common/sender.go
Labels: documentation

#1941 e2e: Diagnose and fix flakes
  tests/colors.go
  tests/e2e/banff/suites.go
  tests/e2e/c/interchain_workflow.go
  tests/e2e/e2e.go
  tests/e2e/p/permissionless_subnets.go
  tests/e2e/p/workflow.go
  tests/e2e/static-handlers/suites.go
  tests/e2e/x/interchain_workflow.go
  tests/e2e/x/transfer/virtuous.go
  tests/fixture/testnet/config.go
  tests/fixture/testnet/local/config.go
  tests/fixture/testnet/local/network.go
  wallet/chain/c/wallet.go
  wallet/chain/p/wallet.go
  wallet/chain/x/wallet.go
  wallet/subnet/primary/common/options.go
Labels: bug, testing, ci

#1954 `merkledb` -- `db_test.go` cleanup
  database/test_database.go
  x/merkledb/db_test.go
  x/merkledb/proof_test.go
Labels: testing, merkledb

#1963 `merkledb` -- make config fields uints
  x/merkledb/db.go
  x/merkledb/db_test.go
  x/merkledb/history_test.go
Labels: cleanup, merkledb

#1988 Only gracefully exit rpcchainvm server after Shutdown
  vms/rpcchainvm/vm.go
  vms/rpcchainvm/vm_server.go
Labels: incident response

#1977 Add contexts to SDK callbacks
  network/p2p/client.go
  network/p2p/gossip/gossip.go
  network/p2p/router.go
  network/p2p/router_test.go
Labels: sdk

#1995 Change max response size to target response size
  network/p2p/gossip/gossip_test.go
  network/p2p/gossip/handler.go
Labels: networking

#1997 Add sdk gossip handler metrics
  network/p2p/gossip/gossip.go
  network/p2p/gossip/gossip_test.go
  network/p2p/gossip/handler.go
Labels: monitoring, networking, sdk

#2000 Add p2p SDK Router metrics
  network/p2p/client.go
  network/p2p/gossip/gossip_test.go
  network/p2p/peers_test.go
  network/p2p/router.go
  network/p2p/router_test.go
Labels: monitoring, networking, sdk

#1990 Merkledb Attempt to reduce test runtime
  x/merkledb/codec_test.go
  x/merkledb/db_test.go
  x/merkledb/helpers_test.go
  x/merkledb/history_test.go
  x/merkledb/proof.go
  x/merkledb/proof_test.go
Labels: testing, ci, merkledb

#2001 longer timeout on windows UT
  .github/workflows/build-and-test.yml
  scripts/build_test.sh
Labels: testing, ci

#2008 `sync` -- log tweaks
  x/sync/manager.go
Labels: merkledb

#2015 Add Validator Gossiper
  network/p2p/gossip/gossip.go
  network/p2p/gossip/gossip_test.go
Labels: networking, sdk

#2018 database: comment that Get returns ErrNotFound if key is not present
  database/database.go
Labels: documentation

#2022 Return `height` from `GetCurrentSupply`
  vms/platformvm/client.go
  vms/platformvm/service.go
Labels: vm

#2023 simplify platformvm `GetHeight` function
  vms/platformvm/service.go
Labels: cleanup

#2019 Merkle db fix range proof commit bug
  proto/pb/sync/sync.pb.go
  proto/sync/sync.proto
  x/merkledb/db.go
  x/merkledb/db_test.go
  x/merkledb/mock_db.go
  x/sync/g_db/db_client.go
  x/sync/g_db/db_server.go
  x/sync/manager.go
  x/sync/sync_test.go
Labels: bug, merkledb

#2027 Add `bag.Of` helper
  snow/consensus/snowball/flat_test.go
  snow/consensus/snowball/tree_test.go
  snow/consensus/snowman/consensus_test.go
  snow/consensus/snowman/poll/early_term_no_traversal_test.go
  snow/consensus/snowman/poll/no_early_term_test.go
  snow/consensus/snowman/poll/set_test.go
  snow/engine/snowman/transitive.go
  utils/bag/bag.go
  utils/bag/bag_test.go
Labels: consensus, testing, cleanup

#2029 Cleanup early poll termination logic
  snow/consensus/snowman/poll/early_term_no_traversal.go
  snow/consensus/snowman/poll/early_term_no_traversal_test.go
  snow/consensus/snowman/poll/no_early_term_test.go
  snow/consensus/snowman/poll/set_test.go
Labels: consensus, testing, cleanup

#2030 fix typo
  vms/platformvm/validators/manager.go
Labels: documentation, cleanup

#1987 Merkle db intermediate node key compression
  x/merkledb/db.go
  x/merkledb/intermediate_node_db.go
  x/merkledb/intermediate_node_db_test.go
Labels: merkledb

#2021 Improve RPC Chain version mismatch error message
  vms/rpcchainvm/runtime/runtime.go
  vms/rpcchainvm/runtime/subprocess/initializer.go
Labels: documentation

#2024 Move subnet owner lookup to platformvm state
  vms/platformvm/service.go
  vms/platformvm/state/diff.go
  vms/platformvm/state/diff_test.go
  vms/platformvm/state/mock_chain.go
  vms/platformvm/state/mock_diff.go
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/state.go
  vms/platformvm/txs/executor/create_chain_test.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/txs/executor/subnet_tx_verification.go
  vms/platformvm/utxo/handler.go
Labels: vm

#1991 Fix fuzz tests; add iterator fuzz test
  codec/hierarchycodec/codec_test.go
  codec/linearcodec/codec_test.go
  codec/test_codec.go
  database/corruptabledb/db_test.go
  database/encdb/db_test.go
  database/leveldb/db_test.go
  database/memdb/db_test.go
  database/meterdb/db_test.go
  database/prefixdb/db_test.go
  database/rpcdb/db_test.go
  database/test_database.go
  database/versiondb/db_test.go
Labels: testing

#2014 Refactor subnet validator primary network requirements
  vms/platformvm/txs/executor/staker_tx_verification.go
Labels: vm, cleanup

#1973 Rename events to event
  snow/engine/snowman/transitive.go
  snow/event/blockable.go
  snow/event/blocker.go
  snow/event/blocker_test.go
Labels: cleanup

#2013 add `IsCortinaActivated` helper
  vms/platformvm/config/config.go
  vms/platformvm/txs/executor/proposal_tx_executor.go
Labels: vm, cleanup

#2035 Fix P-chain Import
  vms/platformvm/validator_set_property_test.go
Labels: testing, cleanup

#1970 Rename avm/blocks package to avm/block
  scripts/mocks.mockgen.txt
  vms/avm/block/block.go
  vms/avm/block/block_test.go
  vms/avm/block/builder/builder.go
  vms/avm/block/builder/builder_test.go
  vms/avm/block/executor/block.go
  vms/avm/block/executor/block_test.go
  vms/avm/block/executor/manager.go
  vms/avm/block/executor/manager_test.go
  vms/avm/block/executor/mock_manager.go
  vms/avm/block/mock_block.go
  vms/avm/block/parser.go
  vms/avm/block/standard_block.go
  vms/avm/environment_test.go
  vms/avm/metrics/metrics.go
  vms/avm/metrics/mock_metrics.go
  vms/avm/network/network.go
  vms/avm/network/network_test.go
  vms/avm/service_test.go
  vms/avm/states/diff.go
  vms/avm/states/mock_states.go
  vms/avm/states/state.go
  vms/avm/states/state_test.go
  vms/avm/txs/executor/executor_test.go
  vms/avm/vm.go
  wallet/chain/x/constants.go
Labels: cleanup

#2039 `merkledb` -- encode lengths as uvarints
  x/merkledb/README.md
  x/merkledb/codec.go
  x/merkledb/codec_test.go
Labels: merkledb

#2041 MerkleDB Remove GetNodeFromParent
  x/merkledb/trieview.go
Labels: merkledb

#1891 RewardValidatorTx cleanup
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/reward/calculator.go
  vms/platformvm/reward/calculator_test.go
  vms/platformvm/txs/executor/proposal_tx_executor.go
  vms/platformvm/txs/executor/staker_tx_verification.go
  vms/platformvm/txs/executor/staker_tx_verification_helpers.go
Labels: continuous staking

#2003 Cancel stale SH actions
  .github/workflows/build-and-test.yml
Labels: ci

#1909 e2e: Switch assertion library from gomega to testify
  tests/e2e/banff/suites.go
  tests/e2e/p/permissionless_subnets.go
  tests/e2e/p/workflow.go
  tests/e2e/static-handlers/suites.go
  tests/e2e/x/transfer/virtuous.go
  wallet/chain/p/wallet.go
Labels: testing

#1935 e2e: Add bootstrap checks to migrated kurtosis tests
  tests/e2e/README.md
  tests/e2e/c/interchain_workflow.go
  tests/e2e/e2e.go
  tests/e2e/faultinjection/duplicate_node_id.go
  tests/e2e/x/interchain_workflow.go
Labels: testing, e2e-migrate-kurtosis

#2047 Add `GetTransformSubnetTx` helper
  vms/platformvm/txs/executor/proposal_tx_executor.go
  vms/platformvm/txs/executor/staker_tx_verification_helpers.go
  vms/platformvm/txs/executor/state_changes.go
Labels: cleanup

#2046 Add readme for the staking/local folder
  staking/local/README.md
Labels: documentation

#2048 use `IsCortinaActivated` helper
  vms/platformvm/txs/executor/proposal_tx_executor.go
Labels: cleanup

#2049 add `D` upgrade boilerplate
  node/node.go
  version/constants.go
  vms/avm/states/state_test.go
  vms/platformvm/config/config.go
Labels: vm

#1882 e2e: Ensure interchain workflow coverage for the P-Chain
  tests/e2e/c/interchain_workflow.go
  tests/e2e/e2e.go
  tests/e2e/p/interchain_workflow.go
  tests/e2e/x/interchain_workflow.go
  tests/fixture/testnet/config.go
  tests/fixture/testnet/local/config.go
Labels: testing, e2e-migrate-kurtosis

#1910 e2e: Switch to using default timed context everywhere
  tests/e2e/banff/suites.go
  tests/e2e/e2e.go
  tests/e2e/faultinjection/duplicate_node_id.go
  tests/e2e/p/permissionless_subnets.go
  tests/e2e/p/workflow.go
  tests/e2e/static-handlers/suites.go
  tests/e2e/x/transfer/virtuous.go
Labels: testing

#2053 Remove indentation + confusing comment
  snow/consensus/snowball/tree.go
Labels: documentation, cleanup

#2055 Delete ErrDelegatorSubset
  vms/platformvm/state/state.go
Labels: cleanup

#2058 Fix default validator start time
  tests/e2e/e2e.go
Labels: testing

#1767 e2e: Migrate staking rewards test from kurtosis
  tests/e2e/p/staking_rewards.go
Labels: testing, e2e-migrate-kurtosis

#2036 Fix LRU documentation comment
  cache/lru_cache.go
Labels: documentation

#1893 trace: provide appName and version from Config
  config/config.go
  trace/tracer.go
Labels: monitoring

#2063 Update perms.WriteFile to write atomically
  go.mod
  go.sum
  node/node.go
  utils/perms/write_file.go
Labels: testing

#2076 e2e: Bump validator start time diff to reduce flake potential
  tests/e2e/e2e.go
Labels: testing

#2080 Add `usestdlibvars` linter
  .golangci.yml
  tests/fixture/test_data_server.go
  tests/http.go
  utils/dynamicip/ifconfig_resolver.go
  utils/rpc/json.go
Labels: ci, cleanup

#1907 e2e: Cleanup test labeling
  .github/workflows/test.e2e.persistent.yml
  .github/workflows/test.e2e.yml
  scripts/tests.e2e.persistent.sh
  scripts/tests.e2e.sh
  tests/e2e/README.md
  tests/e2e/banff/suites.go
  tests/e2e/describe.go
  tests/e2e/e2e_test.go
  tests/e2e/p/interchain_workflow.go
  tests/e2e/p/permissionless_subnets.go
  tests/e2e/p/workflow.go
  tests/e2e/static-handlers/suites.go
  tests/e2e/x/interchain_workflow.go
  tests/e2e/x/transfer/virtuous.go
  tests/fixture/testnet/local/network.go
Labels: testing, e2e-migrate-kurtosis

#2087 Add `dupword` linter
  .golangci.yml
  api/keystore/keystore.go
  chains/atomic/state.go
  database/test_database.go
  network/config.go
  snow/consensus/snowman/topological.go
  snow/engine/common/bootstrapper.go
  snow/networking/handler/message_queue_metrics.go
  utils/crypto/bls/secret.go
  vms/components/index/index.go
  vms/platformvm/txs/mempool/mempool.go
Labels: documentation, cleanup

#1792 e2e: Migrate dynamic fees test from kurtosis
  tests/e2e/c/dynamic_fees.go
  tests/e2e/c/hashing.sol
  tests/e2e/c/hashing_contract.go
  tests/e2e/c/interchain_workflow.go
  tests/e2e/e2e.go
  tests/e2e/e2e_test.go
Labels: testing, e2e-migrate-kurtosis

#2082 Update `golangci-lint` to `v1.54.2`
  .golangci.yml
  ids/id_test.go
  scripts/lint.sh
  utils/timer/adaptive_timeout_manager_test.go
  vms/avm/txs/import_tx.go
  vms/avm/vm.go
  vms/components/avax/base_tx.go
  vms/components/avax/utxo_id_test.go
  vms/platformvm/genesis/genesis.go
  vms/platformvm/service.go
  vms/platformvm/txs/executor/standard_tx_executor.go
  vms/platformvm/utxo/handler.go
  wallet/chain/x/builder.go
Labels: ci

#2091 Add last accepted height to the snowman interface
  snow/consensus/snowman/consensus.go
  snow/consensus/snowman/consensus_test.go
  snow/consensus/snowman/topological.go
  snow/engine/snowman/transitive.go
Labels: consensus, bubble votes

#2075 MerkleDB Compact Path Bytes Nits
  x/merkledb/codec.go
  x/merkledb/db.go
  x/merkledb/path.go
  x/sync/client.go
  x/sync/manager.go
Labels: cleanup, merkledb

#2068 Delete kurtosis CI jobs
  .github/workflows/run-kurtosis-tests-basic.yml
  .github/workflows/run-kurtosis-tests-full.yml
  .github/workflows/run_e2e_tests.sh
  .kurtosis/kurtosis.sh
Labels: testing, e2e-migrate-kurtosis

#2069 e2e: Ensure all Issue* calls use the default context
  tests/e2e/p/interchain_workflow.go
  tests/e2e/p/staking_rewards.go
Labels: testing, e2e-migrate-kurtosis

#2093 Remove Finalized from the consensus interface
  snow/consensus/snowman/consensus.go
  snow/consensus/snowman/consensus_test.go
  snow/consensus/snowman/network_test.go
  snow/consensus/snowman/topological.go
  snow/engine/snowman/transitive_test.go
  snow/engine/snowman/voter.go
Labels: consensus

#2089 Remove embedding of `verify.Verifiable` in `FxCredential`
  vms/avm/block/builder/builder_test.go
  vms/avm/fxs/fx.go
  vms/avm/tx_init.go
  vms/avm/txs/executor/semantic_verifier.go
  vms/avm/txs/executor/syntactic_verifier_test.go
  vms/avm/txs/tx.go
  vms/avm/vm_test.go
  wallet/chain/x/signer_visitor.go
Labels: cleanup

#2094 Clarify decidable interface simple default parameter tests
  snow/choices/decidable.go
  snow/consensus/snowman/consensus_test.go
  snow/consensus/snowman/topological.go
Labels: documentation, consensus

#2095 snow/consensus/snowman/poll: remove "unused" no early term poller
  snow/consensus/snowman/poll/no_early_term.go
  snow/consensus/snowman/poll/no_early_term_test.go
  snow/consensus/snowman/poll/set_test.go
Labels: consensus, cleanup

#2097 Cleanup `.golangci.yml`
  .golangci.yml
Labels: ci

#2099 Refactor `ancestor.Tree`
  snow/engine/snowman/ancestor/tree.go
  snow/engine/snowman/ancestor/tree_test.go
  snow/engine/snowman/ancestor_tree.go
  snow/engine/snowman/ancestor_tree_test.go
  snow/engine/snowman/memory_block.go
  snow/engine/snowman/transitive.go
  snow/engine/snowman/voter.go
Labels: consensus, cleanup

#2084 Add `tagalign` linter
  .golangci.yml
  codec/test_codec.go
  snow/consensus/snowball/parameters.go
  snow/engine/avalanche/vertex/stateless_vertex.go
  subnets/config.go
  vms/avm/txs/initial_state.go
  vms/avm/txs/operation.go
  vms/components/avax/transferables.go
Labels: ci, cleanup

#2101 Fix flaky BuildBlockIsIdempotent test
  vms/proposervm/vm_test.go
Labels: testing, cleanup

#2061 Make `network.dial` honor context cancellation.
  network/network.go
  network/network_test.go
Labels: bug, networking

#2092 Add preference lookups by height to the consensus interface
  snow/consensus/snowman/consensus.go
  snow/consensus/snowman/consensus_test.go
  snow/consensus/snowman/topological.go
Labels: consensus, bubble votes

#2051 Add additional validator set metrics
  snow/engine/common/tracker/peers.go
  snow/engine/common/tracker/peers_test.go
Labels: monitoring

#2104 Remove `snowball.Initialize` and `snowball.Factory`
  snow/consensus/snowball/consensus.go
  snow/consensus/snowball/consensus_performance_test.go
  snow/consensus/snowball/consensus_reversibility_test.go
  snow/consensus/snowball/consensus_test.go
  snow/consensus/snowball/factory.go
  snow/consensus/snowball/flat.go
  snow/consensus/snowball/flat_test.go
  snow/consensus/snowball/network_test.go
  snow/consensus/snowball/tree.go
  snow/consensus/snowball/tree_test.go
  snow/consensus/snowman/snowman_block.go
Labels: consensus, cleanup

#2105 Remove initialize functions from the snowball package
  snow/consensus/snowball/binary_slush.go
  snow/consensus/snowball/binary_snowball.go
  snow/consensus/snowball/binary_snowball_test.go
  snow/consensus/snowball/binary_snowflake.go
  snow/consensus/snowball/binary_snowflake_test.go
  snow/consensus/snowball/consensus.go
  snow/consensus/snowball/flat.go
  snow/consensus/snowball/nnary_slush.go
  snow/consensus/snowball/nnary_snowball.go
  snow/consensus/snowball/nnary_snowball_test.go
  snow/consensus/snowball/nnary_snowflake.go
  snow/consensus/snowball/nnary_snowflake_test.go
  snow/consensus/snowball/tree.go
  snow/consensus/snowball/unary_snowball.go
  snow/consensus/snowball/unary_snowball_test.go
  snow/consensus/snowball/unary_snowflake.go
  snow/consensus/snowball/unary_snowflake_test.go
Labels: consensus, cleanup

#2112 Remove `genesis.State`
  vms/platformvm/genesis/genesis.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
Labels: vm, cleanup

#2031 add `SetSubnetOwner` to `Chain` interface
  vms/platformvm/config/execution_config.go
  vms/platformvm/config/execution_config_test.go
  vms/platformvm/state/diff.go
  vms/platformvm/state/diff_test.go
  vms/platformvm/state/mock_chain.go
  vms/platformvm/state/mock_diff.go
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
  vms/platformvm/txs/executor/create_chain_test.go
  vms/platformvm/txs/executor/standard_tx_executor.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
Labels: vm

#2100 Move vote bubbling before poll termination
  snow/engine/snowman/transitive.go
  snow/engine/snowman/voter.go
Labels: consensus, cleanup, bubble votes

#1887 testing: Switch upgrade test to testnet fixture
  .github/workflows/test.upgrade.yml
  go.mod
  go.sum
  scripts/install_anr.sh
  scripts/tests.upgrade.sh
  tests/e2e/e2e.go
  tests/fixture/testnet/local/network.go
  tests/upgrade/upgrade_test.go
Labels: testing

#2113 Reduce archivedb key lengths by 1 byte
  x/archivedb/batch.go
  x/archivedb/db_test.go
  x/archivedb/key.go
  x/archivedb/key_test.go
  x/archivedb/prefix_test.go
  x/archivedb/reader.go
Labels: storage, cleanup

#2118 Cleanup uptime manager constructor
  network/network_test.go
  snow/uptime/manager.go
  snow/uptime/manager_test.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/vm.go
  vms/platformvm/vm_test.go
Labels: vm, testing, cleanup
