Repository ava-labs/avalanchego, pull requests merged in 2023-08, with the labels that each got.

#1766 Evict blocks based on size
  snow/engine/snowman/transitive.go
  utils/constants/memory.go
  vms/components/chain/state.go
  vms/components/chain/state_test.go
  vms/platformvm/state/state.go
  vms/proposervm/state/block_state.go
  vms/proposervm/vm.go
  vms/proposervm/vm_test.go
  vms/rpcchainvm/vm_client.go
Labels: consensus, vm, sdk

#1785 Add proposervm state metrics
  vms/proposervm/vm.go
Labels: monitoring

#1799 Add p2p sdk
  network/p2p/client.go
  network/p2p/handler.go
  network/p2p/mocks/mock_handler.go
  network/p2p/router.go
  network/p2p/router_test.go
  network/peer/ip.go
  scripts/mocks.mockgen.txt
  staking/verification.go
  utils/sampler/uniform_resample.go
  utils/set/sampleable_set.go
  utils/set/sampleable_set_test.go
  vms/proposervm/block/block.go
Labels: networking, sdk

#1803 Removes calls to ctrl.Finish
  api/admin/service_test.go
  api/info/service_test.go
  database/test_database.go
  indexer/indexer_test.go
  network/throttling/inbound_resource_throttler_test.go
  network/throttling/outbound_msg_throttler_test.go
  snow/engine/snowman/getter/getter_test.go
  snow/networking/handler/handler_test.go
  snow/networking/handler/message_queue_test.go
  snow/networking/router/chain_router_test.go
  snow/networking/sender/sender_test.go
  snow/networking/tracker/targeter_test.go
  snow/uptime/locked_calculator_test.go
  snow/validators/gvalidators/validator_state_test.go
  utils/crypto/keychain/keychain_test.go
  utils/hashing/consistent/ring_test.go
  vms/avm/blocks/builder/builder_test.go
  vms/avm/blocks/executor/block_test.go
  vms/avm/blocks/executor/manager_test.go
  vms/avm/network/network_test.go
  vms/avm/service_test.go
  vms/avm/txs/executor/semantic_verifier_test.go
  vms/components/verify/subnet_test.go
  vms/platformvm/blocks/builder/builder_test.go
  vms/platformvm/blocks/executor/acceptor_test.go
  vms/platformvm/blocks/executor/backend_test.go
  vms/platformvm/blocks/executor/block_test.go
  vms/platformvm/blocks/executor/manager_test.go
  vms/platformvm/blocks/executor/proposal_block_test.go
  vms/platformvm/blocks/executor/rejector_test.go
  vms/platformvm/blocks/executor/standard_block_test.go
  vms/platformvm/blocks/executor/verifier_test.go
  vms/platformvm/stakeable/stakeable_lock_test.go
  vms/platformvm/state/diff_test.go
  vms/platformvm/state/staker_test.go
  vms/platformvm/txs/add_permissionless_delegator_tx_test.go
  vms/platformvm/txs/add_permissionless_validator_tx_test.go
  vms/platformvm/txs/executor/export_test.go
  vms/platformvm/txs/executor/staker_tx_verification_test.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/txs/remove_subnet_validator_tx_test.go
  vms/platformvm/txs/transform_subnet_tx_test.go
  vms/platformvm/warp/signature_test.go
  vms/platformvm/warp/validator_test.go
  vms/proposervm/block_test.go
  vms/proposervm/pre_fork_block_test.go
  vms/proposervm/vm_test.go
  vms/registry/vm_getter_test.go
  vms/registry/vm_registerer_test.go
  vms/registry/vm_registry_test.go
  vms/rpcchainvm/batched_vm_test.go
  vms/rpcchainvm/state_syncable_vm_test.go
  vms/rpcchainvm/vm_test.go
  vms/rpcchainvm/with_context_vm_test.go
  x/sync/client_test.go
  x/sync/network_server_test.go
  x/sync/sync_test.go
Labels: cleanup

#1786 e2e: Remove unnecessary transaction status checking
  tests/e2e/p/permissionless_subnets.go
  tests/e2e/p/workflow.go
Labels: testing

#1801 fix end proof verification
  x/merkledb/proof.go
  x/merkledb/proof_test.go
Labels: bug, merkledb

#1787 `sync` -- re-add network client metrics
  x/sync/client_test.go
  x/sync/network_client.go
  x/sync/peer_tracker.go
Labels: merkledb

#1700 e2e: Add local network fixture
  .github/workflows/test.e2e.persistent.yml
  config/flags.go
  go.mod
  go.sum
  node/node.go
  scripts/build_test.sh
  scripts/build_testnetctl.sh
  scripts/tests.e2e.persistent.sh
  tests/fixture/testnet/README.md
  tests/fixture/testnet/cmd/main.go
  tests/fixture/testnet/config.go
  tests/fixture/testnet/interfaces.go
  tests/fixture/testnet/local/README.md
  tests/fixture/testnet/local/config.go
  tests/fixture/testnet/local/network.go
  tests/fixture/testnet/local/network_test.go
  tests/fixture/testnet/local/node.go
  tests/fixture/testnet/local/node_test.go
Labels: testing, q3

#1822 Fix test flake in TestProposalTxsInMempool
  vms/platformvm/txs/mempool/mempool_test.go
Labels: testing, cleanup

#1788 `sync` -- remove todo
  x/sync/response_handler.go
Labels: merkledb

#1810 `merkledb` -- clarify/improve change proof invariants
  x/merkledb/proof.go
Labels: documentation, merkledb

#1825 Update maintainer of the debian packages
  .github/workflows/debian/template/control
Labels: ci

#1746 Make platformvm implement `block.HeightIndexedChainVM`
  vms/platformvm/vm.go
Labels: vm

#1747 Add P-chain `GetBlockByHeight` API method
  vms/platformvm/client.go
  vms/platformvm/service.go
  vms/platformvm/service_test.go
Labels: vm

#1690 `sync` -- add handling for fatal error
  x/sync/client.go
  x/sync/client_test.go
  x/sync/mock_network_client.go
  x/sync/network_client.go
Labels: merkledb

#1832 Add error logs for unexpected proposervm BuildBlock failures
  vms/proposervm/block.go
  vms/proposervm/post_fork_option.go
  vms/proposervm/pre_fork_block.go
  vms/proposervm/vm.go
Labels: vm, monitoring, incident response

#1833 Fix subnet validator set public key initialization
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/validators/manager.go
  vms/platformvm/vm_regression_test.go
Labels: bug, vm, incident response

#1835 Document PendingTxs + BuildBlock consensus engine requirement
  snow/engine/common/message.go
Labels: documentation, incident response

#1769 Add Primary Network Lite Sync Option
  chains/manager.go
  config/config.go
  config/flags.go
  config/keys.go
  node/config.go
  node/node.go
  snow/engine/snowman/config.go
  snow/engine/snowman/transitive.go
  vms/platformvm/blocks/builder/builder.go
  vms/platformvm/blocks/builder/network.go
  vms/platformvm/blocks/executor/manager.go
  vms/platformvm/blocks/executor/rejector.go
  vms/platformvm/blocks/executor/rejector_test.go
  vms/platformvm/config/config.go
  vms/platformvm/txs/executor/standard_tx_executor.go
  vms/platformvm/vm.go
Labels: consensus, vm, networking

#1836 Check P-chain ShouldPrune during Initialize
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/state.go
  vms/platformvm/vm.go
Labels: vm

#1789 `merkledb` -- verify range proof in fuzz test; fix bound error
  x/merkledb/proof.go
  x/merkledb/proof_test.go
Labels: merkledb

#1839 Update default compression type to zstd
  utils/constants/networking.go
Labels: networking

#1829 `corruptabledb` -- corrupt on iterator error
  database/corruptabledb/db.go
  database/corruptabledb/db_test.go
  database/mock_iterator.go
  scripts/mocks.mockgen.txt
Labels: storage

#1790 Add support for Maps to the reflect_codec
  codec/reflectcodec/type_codec.go
  codec/test_codec.go
Labels: sdk

#1843 Make linter fail if `github.com/golang/mock/gomock` is used
  .golangci.yml
Labels: ci

#1816 Firewoodize merkle db Part 1: Make Views ReadOnly
  x/merkledb/db.go
  x/merkledb/db_test.go
  x/merkledb/proof.go
  x/merkledb/proof_test.go
  x/merkledb/trie.go
  x/merkledb/trie_test.go
  x/merkledb/trieview.go
  x/merkledb/view_iterator_test.go
  x/sync/client_test.go
  x/sync/network_server_test.go
Labels: merkledb

#1851 E2E tests -- use appropriate timeouts
  tests/e2e/p/permissionless_subnets.go
Labels: ci

#1709 e2e: Switch to testnet fixture
  config/flags.go
  scripts/tests.e2e.persistent.sh
  scripts/tests.e2e.sh
  tests/e2e/README.md
  tests/e2e/banff/suites.go
  tests/e2e/describe.go
  tests/e2e/e2e.go
  tests/e2e/e2e_test.go
  tests/e2e/p/permissionless_subnets.go
  tests/e2e/p/workflow.go
  tests/e2e/ping/suites.go
  tests/e2e/static-handlers/suites.go
  tests/e2e/x/transfer/virtuous.go
  tests/fixture/test_data_server.go
  tests/fixture/test_data_server_test.go
  tests/fixture/testnet/local/README.md
  tests/fixture/testnet/local/network.go
  tests/fixture/testnet/local/node.go
  tests/http.go
  tests/keys.go
  tests/keys_test.go
  tests/test.insecure.secp256k1.keys
  utils/zero.go
Labels: testing, e2e-migrate-kurtosis

#1809 `secp256k1` -- add fuzz tests
  utils/crypto/secp256k1/secp256k1_test.go
Labels: testing

#1846 Add fuzz test for complex codec unmarshalling
  codec/hierarchycodec/codec_test.go
  codec/linearcodec/codec_test.go
  codec/test_codec.go
Labels: testing

#1849 Simplify exported interface of the primary wallet
  tests/e2e/banff/suites.go
  tests/e2e/p/permissionless_subnets.go
  tests/e2e/p/workflow.go
  tests/e2e/x/transfer/virtuous.go
  wallet/subnet/primary/example_test.go
  wallet/subnet/primary/examples/add-permissioned-subnet-validator/main.go
  wallet/subnet/primary/examples/add-primary-validator/main.go
  wallet/subnet/primary/examples/create-asset/main.go
  wallet/subnet/primary/examples/create-chain/main.go
  wallet/subnet/primary/examples/create-locked-stakeable/main.go
  wallet/subnet/primary/examples/create-subnet/main.go
  wallet/subnet/primary/examples/remove-subnet-validator/main.go
  wallet/subnet/primary/wallet.go
Labels: sdk, cleanup

#1861 Remove history btree
  x/merkledb/history.go
  x/merkledb/history_test.go
Labels: cleanup, merkledb

#1854 `merkledb` -- Remove `CommitToParent`
  x/merkledb/trie.go
  x/merkledb/trieview.go
Labels: merkledb

#1862 `merkledb` -- remove other history btree
  x/merkledb/db.go
  x/merkledb/history.go
  x/merkledb/path.go
Labels: cleanup, merkledb

#1852 `merkledb` -- add path fuzz test
  x/merkledb/path_test.go
Labels: testing

#1834 fix range proof verification case
  x/merkledb/proof.go
  x/merkledb/proof_test.go
  x/sync/client_test.go
Labels: cleanup, merkledb

#1780 Warp readme
  vms/platformvm/warp/README.md
Labels: documentation

#1863 CODEOWNERS: add marun to tests
  .github/CODEOWNERS
Labels: ci

#1828 Add CI check that auto-generated code is up to date
  .github/workflows/auto-generated-checker.yml
  .github/workflows/check-clean-branch.sh
  README.md
  proto/Dockerfile.buf
Labels: ci

#1772 `sync` -- change proof request can return range proof
  proto/pb/sync/sync.pb.go
  proto/pb/sync/sync_grpc.pb.go
  proto/sync/sync.proto
  x/merkledb/db.go
  x/merkledb/history.go
  x/merkledb/history_test.go
  x/merkledb/proof.go
  x/merkledb/proof_test.go
  x/sync/README.md
  x/sync/client.go
  x/sync/client_test.go
  x/sync/g_db/db_client.go
  x/sync/g_db/db_server.go
  x/sync/manager.go
  x/sync/mock_client.go
  x/sync/network_server.go
  x/sync/network_server_test.go
  x/sync/sync_test.go
Labels: merkledb

#1875 GetCanonicalValidatorSet minimal ValidatorState iface
  vms/platformvm/warp/validator.go
Labels: warp

#1874 `sync` -- handle fatal error
  x/sync/client.go
  x/sync/client_test.go
  x/sync/network_client.go
  x/sync/network_server.go
  x/sync/network_server_test.go
Labels: merkledb

#1872 `merkledb` -- use `Maybe` for start bounds
  proto/pb/sync/sync.pb.go
  proto/sync/sync.proto
  utils/maybe/maybe.go
  utils/maybe/maybe_test.go
  x/merkledb/db.go
  x/merkledb/db_test.go
  x/merkledb/history.go
  x/merkledb/history_test.go
  x/merkledb/mock_db.go
  x/merkledb/proof.go
  x/merkledb/proof_test.go
  x/merkledb/trie.go
  x/merkledb/trieview.go
  x/sync/client.go
  x/sync/client_test.go
  x/sync/g_db/db_client.go
  x/sync/g_db/db_server.go
  x/sync/manager.go
  x/sync/network_server.go
  x/sync/network_server_test.go
  x/sync/sync_test.go
  x/sync/workheap.go
  x/sync/workheap_test.go
Labels: merkledb

#1870 e2e: Refactor keychain and wallet creation to test helpers
  tests/e2e/banff/suites.go
  tests/e2e/e2e.go
  tests/e2e/e2e_test.go
  tests/e2e/p/permissionless_subnets.go
  tests/e2e/p/workflow.go
  tests/e2e/x/transfer/virtuous.go
Labels: testing, cleanup

#1881 Update account nonce on exportTx accept
  wallet/chain/c/backend.go
Labels: bug

#1879 `sync` -- add workheap test
  x/sync/workheap_test.go
Labels: testing, merkledb

#1885 `merkledb` -- commit to db only
  x/merkledb/db.go
  x/merkledb/trie.go
  x/merkledb/trie_test.go
  x/merkledb/trieview.go
Labels: merkledb

#1865 Remove node/value lock from trieview
  x/merkledb/README.md
  x/merkledb/db.go
  x/merkledb/db_test.go
  x/merkledb/mock_db.go
  x/merkledb/proof_test.go
  x/merkledb/trie.go
  x/merkledb/trie_test.go
  x/merkledb/trieview.go
  x/merkledb/view_iterator_test.go
  x/sync/client_test.go
  x/sync/network_server_test.go
Labels: merkledb

#1892 remove old todo
  utils/bag/bag.go
Labels: cleanup

#1895 Fix race in TestHandlerDispatchInternal
  snow/networking/handler/handler_test.go
Labels: testing, cleanup

#1897 e2e: Bump permissionless subnets timeouts
  tests/e2e/p/permissionless_subnets.go
Labels: testing

#1899 `merkledb` -- codec remove err checks
  x/merkledb/codec.go
  x/merkledb/codec_test.go
  x/merkledb/db.go
  x/merkledb/node.go
  x/merkledb/node_test.go
Labels: cleanup

#1898 Merkle db fix new return type
  x/merkledb/db.go
  x/merkledb/db_test.go
  x/merkledb/history_test.go
  x/merkledb/metrics_test.go
Labels: merkledb

#1877 Add SDK Sampling interface
  network/p2p/client.go
  network/p2p/node_sampler.go
  network/p2p/peers.go
  network/p2p/peers_test.go
  network/p2p/router.go
  network/p2p/router_test.go
  network/p2p/validators.go
  network/p2p/validators_test.go
Labels: sdk

#1903 Add NoOpHandler implementation to SDK
  network/p2p/handler.go
Labels: sdk

#1908 Remove unused scripts
  Dockerfile
  go.mod
  scripts/build_avalanche.sh
  scripts/build_coreth.sh
  scripts/build_image.sh
  scripts/build_local_dep_image.sh
  scripts/build_local_image.sh
  scripts/constants.sh
  scripts/local.Dockerfile
Labels: cleanup

#1904 `merkledb` -- codec nits/cleanup
  x/merkledb/codec.go
  x/merkledb/codec_test.go
Labels: cleanup, merkledb

#1900 `merkledb` -- preallocate `bytes.Buffer` in codec
  x/merkledb/codec.go
Labels: merkledb

#1915 Proposervm height index repair fix
  vms/proposervm/vm.go
  vms/proposervm/vm_regression_test.go
Labels: bug

#1919 `merkledb` -- move and rename methods
  x/merkledb/db.go
  x/merkledb/proof_test.go
  x/merkledb/trie_test.go
Labels: cleanup, merkledb

#1896 Remove optional height indexing interface
  .github/workflows/auto-generated-checker.yml
  .github/workflows/buf-lint.yml
  .github/workflows/buf-push.yml
  README.md
  chains/linearizable_vm.go
  go.mod
  go.sum
  proto/Dockerfile.buf
  proto/pb/vm/vm.pb.go
  proto/vm/vm.proto
  scripts/protobuf_codegen.sh
  snow/engine/avalanche/vertex/mock_vm.go
  snow/engine/snowman/block/height_indexed_vm.go
  snow/engine/snowman/block/mocks/chain_vm.go
  snow/engine/snowman/block/test_height_indexed_vm.go
  snow/engine/snowman/block/test_vm.go
  snow/engine/snowman/block/vm.go
  vms/avm/vm.go
  vms/metervm/block_metrics.go
  vms/metervm/block_vm.go
  vms/metervm/height_indexed_vm.go
  vms/platformvm/vm.go
  vms/proposervm/batched_vm_test.go
  vms/proposervm/height_indexed_vm.go
  vms/proposervm/state_syncable_vm_test.go
  vms/proposervm/vm.go
  vms/proposervm/vm_regression_test.go
  vms/proposervm/vm_test.go
  vms/rpcchainvm/errors.go
  vms/rpcchainvm/vm_client.go
  vms/rpcchainvm/vm_server.go
  vms/tracedvm/block_vm.go
  vms/tracedvm/height_indexed_vm.go
Labels: vm, cleanup

#1922 Fix code owners file
  .github/CODEOWNERS
Labels: ci, cleanup

#1923 Drop invalid TLS certs during initial handshake
  chains/manager.go
  ids/node_id.go
  network/certs_test.go
  network/network_test.go
  network/peer/ip.go
  network/peer/peer.go
  network/peer/peer_test.go
  network/peer/upgrader.go
  node/node.go
  staking/asn1.go
  staking/certificate.go
  staking/parse.go
  staking/verification.go
  staking/verify.go
  tests/fixture/testnet/config.go
  utils/ips/claimed_ip_port.go
  vms/proposervm/batched_vm_test.go
  vms/proposervm/block/block.go
  vms/proposervm/block/build.go
  vms/proposervm/block/build_test.go
  vms/proposervm/block/parse_test.go
  vms/proposervm/block_test.go
  vms/proposervm/post_fork_option_test.go
  vms/proposervm/state/block_state_test.go
  vms/proposervm/state_syncable_vm_test.go
  vms/proposervm/vm.go
  vms/proposervm/vm_regression_test.go
  vms/proposervm/vm_test.go
Labels: networking

#1924 Restricted tls metrics
  network/metrics.go
  network/network.go
  network/peer/test_peer.go
  network/peer/upgrader.go
Labels: monitoring, networking

#1856 e2e: Save network data for each test run as an uploaded artifact
  .github/workflows/test.e2e.persistent.yml
  .github/workflows/test.e2e.yml
  scripts/tests.e2e.persistent.sh
  tests/e2e/e2e_test.go
Labels: testing, e2e-migrate-kurtosis

#1871 e2e: Ensure interchain workflow coverage for X-Chain and C-Chain
  tests/e2e/c/interchain_workflow.go
  tests/e2e/describe.go
  tests/e2e/e2e.go
  tests/e2e/e2e_test.go
  tests/e2e/x/interchain_workflow.go
  tests/e2e/x/transfer/virtuous.go
  tests/fixture/testnet/config.go
Labels: testing, e2e-migrate-kurtosis

#1927 MerkleDB Adjust New View function(s)
  x/merkledb/db.go
  x/merkledb/db_test.go
  x/merkledb/mock_db.go
  x/merkledb/proof.go
  x/merkledb/proof_test.go
  x/merkledb/trie.go
  x/merkledb/trie_test.go
  x/merkledb/trieview.go
  x/merkledb/view_iterator_test.go
  x/sync/client_test.go
  x/sync/network_server_test.go
Labels: merkledb

#1573 e2e: Migrate duplicate node id test from kurtosis
  .github/workflows/test.e2e.persistent.yml
  .github/workflows/test.e2e.yml
  scripts/tests.e2e.sh
  tests/e2e/e2e.go
  tests/e2e/e2e_test.go
  tests/e2e/faultinjection/duplicate_node_id.go
  tests/fixture/testnet/common.go
  tests/fixture/testnet/interfaces.go
  tests/fixture/testnet/local/README.md
  tests/fixture/testnet/local/config.go
  tests/fixture/testnet/local/network.go
  tests/fixture/testnet/local/node.go
Labels: testing, e2e-migrate-kurtosis

#1933 Add tracing levels to merkledb
  trace/noop.go
  trace/tracer.go
  x/merkledb/db.go
  x/merkledb/db_test.go
  x/merkledb/proof.go
  x/merkledb/tracer.go
  x/merkledb/trieview.go
  x/sync/client_test.go
  x/sync/sync_test.go
Labels: monitoring

#1930 e2e: Ensure testnet network dir is archived on failed test run
  .github/workflows/test.e2e.persistent.yml
  .github/workflows/test.e2e.yml
Labels: testing

#1934 Merkle db cleanup view creation
  x/merkledb/db.go
  x/merkledb/db_test.go
  x/merkledb/proof.go
  x/merkledb/trie_test.go
  x/merkledb/trieview.go
Labels: merkledb

#1917 Implement SDK handler to drop messages from non-validators
  network/p2p/handler.go
  network/p2p/handler_test.go
  network/p2p/validators.go
Labels: sdk

#1940 Remove thread pool
  snow/networking/handler/handler.go
  snow/networking/worker/pool.go
Labels: networking, cleanup

#1918 Merkledb split node storage into value and intermediate
  database/helpers.go
  x/merkledb/README.md
  x/merkledb/batch.go
  x/merkledb/cache.go
  x/merkledb/cache_test.go
  x/merkledb/codec.go
  x/merkledb/db.go
  x/merkledb/db_test.go
  x/merkledb/intermediate_node_db.go
  x/merkledb/intermediate_node_db_test.go
  x/merkledb/iterator.go
  x/merkledb/metrics.go
  x/merkledb/metrics_test.go
  x/merkledb/mock_db.go
  x/merkledb/node.go
  x/merkledb/node_test.go
  x/merkledb/proof.go
  x/merkledb/trie.go
  x/merkledb/trie_test.go
  x/merkledb/trieview.go
  x/merkledb/value_node_db.go
  x/merkledb/value_node_db_test.go
  x/sync/client_test.go
Labels: merkledb

#1943 `merkledb` -- remove unneeded codec test helper
  x/merkledb/codec_test.go
Labels: testing

#1944 `merkledb` -- add codec test and move helper
  x/merkledb/codec_test.go
  x/merkledb/proof_test.go
Labels: testing, merkledb

#1905 Add throttler implementation to SDK
  network/p2p/throttler.go
  network/p2p/throttler_test.go
Labels: sdk

#1906 Add Throttled Handler implementation to SDK
  network/p2p/throttler_handler.go
  network/p2p/throttler_handler_test.go
Labels: sdk

#1951 Rename `node.marshal` to `node.bytes`
  x/merkledb/db.go
  x/merkledb/intermediate_node_db.go
  x/merkledb/node.go
  x/merkledb/node_test.go
  x/merkledb/value_node_db.go
Labels: cleanup, merkledb

#1928 e2e: Switch to a default network node count of 2
  tests/fixture/testnet/config.go
Labels: testing

#1950 MerkleDB Improve Node Size Calculation
  x/merkledb/db.go
  x/merkledb/intermediate_node_db.go
  x/merkledb/intermediate_node_db_test.go
  x/merkledb/node.go
Labels: merkledb
