Repository ava-labs/avalanchego, pull requests merged in 2023-06, with the labels that each got.

#1565 Randomize unit test execution order to identify unwanted dependency
  scripts/build_test.sh
Labels: testing

#1564 use `http.Error` instead of separately writing error code and message
  api/server/server.go
  api/server/server_test.go
Labels: testing, cleanup

#1566 Adding allowed http hosts flag
  api/server/allowed_hosts.go
  api/server/allowed_hosts_test.go
  api/server/server.go
  config/config.go
  config/flags.go
  config/keys.go
  node/config.go
  node/node.go
Labels: enhancement, networking

#1541 `x/sync` -- Use proto for sending Change Proofs
  x/merkledb/codec.go
  x/merkledb/codec_test.go
  x/merkledb/db.go
  x/merkledb/node.go
  x/merkledb/proof.go
  x/merkledb/proof_test.go
  x/sync/client.go
  x/sync/client_test.go
  x/sync/network_server.go
  x/sync/network_server_test.go
Labels: merkledb

#1568 Reduce number of test iterations
  x/merkledb/db_test.go
  x/merkledb/history_test.go
  x/merkledb/trie_test.go
Labels: testing, merkledb

#1410 Re-add upgrade tests
  .github/workflows/test.upgrade.yml
Labels: testing

#1412 Remove lists from Chits messages
  message/inbound_msg_builder.go
  message/inbound_msg_builder_test.go
  message/messages_test.go
  message/mock_outbound_message_builder.go
  message/outbound_msg_builder.go
  proto/p2p/p2p.proto
  proto/pb/p2p/p2p.pb.go
  snow/engine/common/engine.go
  snow/engine/common/mock_sender.go
  snow/engine/common/no_ops_handlers.go
  snow/engine/common/sender.go
  snow/engine/common/test_engine.go
  snow/engine/common/test_sender.go
  snow/engine/common/traced_engine.go
  snow/engine/common/tracker/accepted.go
  snow/engine/common/tracker/accepted_test.go
  snow/engine/snowman/transitive.go
  snow/engine/snowman/transitive_test.go
  snow/networking/handler/handler.go
  snow/networking/handler/handler_test.go
  snow/networking/router/chain_router_test.go
  snow/networking/sender/sender.go
  snow/networking/sender/traced_sender.go
Labels: consensus, networking, cleanup

#1487 Add more X-chain tests
  codec/manager.go
  codec/test_codec.go
  vms/avm/blocks/block_test.go
  vms/avm/txs/executor/executor_test.go
  vms/avm/txs/executor/semantic_verifier_test.go
Labels: testing

#1570 fix typo
  snow/README.md
Labels: documentation

#1571 Reduce the number of test health checks
  api/health/health_test.go
Labels: testing

#1572 Fix proposervm.GetAncestors test flake
  vms/platformvm/blocks/executor/proposal_block_test.go
  vms/platformvm/state/validator_metadata_test.go
  vms/platformvm/txs/executor/staker_tx_verification_test.go
  vms/proposervm/batched_vm_test.go
Labels: testing, cleanup

#1576 `x/sync` -- Add `SyncableDB` proto server/client
  x/sync/syncable_db_client.go
  x/sync/syncable_db_server.go
Labels: merkledb

#1586 `MerkleDB` -- add eviction batch size config
  x/merkledb/db.go
  x/merkledb/db_test.go
  x/sync/client_test.go
  x/sync/sync_test.go
Labels: merkledb

#1589 `MerkleDB` -- fix `onEvictCache.Flush`
  x/merkledb/cache.go
Labels: merkledb

#1591 Revert P-Chain height index
  vms/avm/service.go
  vms/avm/service_test.go
  vms/avm/states/diff.go
  vms/avm/states/mock_states.go
  vms/avm/states/state.go
  vms/avm/states/state_test.go
  vms/platformvm/client.go
  vms/platformvm/service.go
  vms/platformvm/service_test.go
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/state.go
Labels: bug, vm

#1559 `x/sync` -- Add `SyncableDB` proto
  proto/pb/sync/sync.pb.go
  proto/pb/sync/sync_grpc.pb.go
  proto/sync/sync.proto
  x/merkledb/proof.go
  x/merkledb/proof_test.go
  x/sync/client.go
  x/sync/client_test.go
  x/sync/gsyncable_db/syncable_db_client.go
  x/sync/gsyncable_db/syncable_db_server.go
  x/sync/mock_client.go
  x/sync/network_server.go
  x/sync/network_server_test.go
  x/sync/sync_test.go
  x/sync/syncmanager.go
Labels: merkledb

#1580 Clarify break on error during ancestors lookup
  snow/engine/snowman/block/batched_vm.go
  snow/engine/snowman/block/batched_vm_test.go
  snow/engine/snowman/getter/getter.go
  vms/rpcchainvm/vm_server.go
Labels: documentation, monitoring

#1594 Pchain bls diffs fix cleanup
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/validators/manager.go
Labels: cleanup

#1584 Pchain bls key diff fix
  go.mod
  go.sum
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/validators/manager.go
  vms/platformvm/validators/manager_test.go
  vms/platformvm/vm_regression_test.go
Labels: bug, vm

#1596 add helper function
  api/health/worker.go
Labels: cleanup

#1599 Cleanup fx interface compliance
  scripts/mocks.mockgen.txt
  vms/avm/state_test.go
  vms/avm/txs/initial_state_test.go
  vms/components/avax/mock_transferable_out.go
  vms/components/avax/test_verifiable.go
  vms/components/verify/verification.go
  vms/nftfx/mint_output.go
  vms/nftfx/transfer_output.go
  vms/platformvm/blocks/codec.go
  vms/platformvm/fx/fx.go
  vms/platformvm/fx/mock_fx.go
  vms/platformvm/txs/codec.go
  vms/propertyfx/mint_output.go
  vms/propertyfx/owned_output.go
  vms/secp256k1fx/mint_output.go
  vms/secp256k1fx/mint_output_test.go
  vms/secp256k1fx/output_owners.go
  vms/secp256k1fx/output_owners_test.go
  vms/secp256k1fx/transfer_output.go
Labels: cleanup

#1579 Separate health checks by tags
  api/health/README.md
  api/health/health.go
  api/health/health_test.go
  api/health/metrics.go
  api/health/worker.go
  chains/manager.go
  node/node.go
Labels: monitoring

#1358 Separate subnet stake connected health and metrics from P-chain
  chains/manager.go
  config/config.go
  config/config_test.go
  config/flags.go
  node/config.go
  node/node.go
  snow/consensus/snowball/parameters.go
  snow/consensus/snowball/parameters_test.go
  snow/engine/common/tracker/peers.go
  snow/networking/handler/handler.go
  snow/networking/handler/handler_test.go
  snow/networking/handler/health.go
  snow/networking/handler/health_test.go
  snow/networking/router/chain_router_test.go
  snow/networking/sender/sender_test.go
  subnets/config.go
  utils/constants/networking.go
  vms/platformvm/blocks/builder/helpers_test.go
  vms/platformvm/config/config.go
  vms/platformvm/health.go
  vms/platformvm/health_test.go
  vms/platformvm/metrics/metrics.go
  vms/platformvm/validators/manager_test.go
  vms/platformvm/vm.go
  vms/platformvm/vm_test.go
Labels: vm, monitoring, incident response

#1533 Merkle db iterator
  x/merkledb/db.go
  x/merkledb/mock_db.go
  x/merkledb/trie.go
  x/merkledb/trieview.go
  x/merkledb/view_iterator.go
  x/merkledb/view_iterator_test.go
Labels: merkledb

#1585 Fix unreadable message errors
  message/internal_msg_builder.go
  message/messages.go
  message/messages_test.go
  message/ops.go
  snow/networking/handler/handler.go
Labels: bug, monitoring

#1592 Log unexpected errors during GetValidatorSet
  vms/platformvm/validators/manager.go
  vms/platformvm/validators/manager_test.go
  vms/platformvm/vm.go
Labels: monitoring

#1582 `merkleDB` -- add inner heap type to syncWorkHeap
  x/sync/syncworkheap.go
  x/sync/syncworkheap_test.go
Labels: merkledb

#1600 `sync` -- explain algorithm in readme
  x/sync/README.md
Labels: documentation, merkledb

#1608 Rename license header file to avoid unintended license indexing
  header.yml
  scripts/lint.sh
  scripts/mock.gen.sh
Labels: documentation

#1607 `merkledb` and `sync` -- use time based rand seed
  x/merkledb/db_test.go
  x/merkledb/history_test.go
  x/merkledb/proof_test.go
  x/merkledb/view_iterator_test.go
  x/sync/client_test.go
  x/sync/network_server_test.go
  x/sync/sync_test.go
Labels: cleanup, merkledb

#1610 snow/engine/snowman: instantiate voter after issuer
  snow/engine/snowman/transitive.go
Labels: cleanup

#1619 Remove old networking metric
  network/metrics.go
Labels: networking, cleanup

#1620 Fix --http-host flag to support IPv6
  api/server/server.go
Labels: bug, networking

#1613 e2e: Support testing on MacOS without requiring firewall exceptions
  config/config.go
  config/flags.go
  config/keys.go
  node/config.go
  node/node.go
Labels: enhancement, networking

#1622 Reduce resource log level
  utils/resource/usage.go
Labels: monitoring

#1624 `sync` -- fix `TestFindNextKeyRandom`
  x/sync/sync_test.go
Labels: merkledb

#1506 Improve `database/` tests with `require`
  database/benchmark_database.go
  database/corruptabledb/db_test.go
  database/encdb/db_test.go
  database/leveldb/db_test.go
  database/linkeddb/linkeddb_test.go
  database/manager/manager_test.go
  database/meterdb/db_test.go
  database/rpcdb/db_test.go
  database/versiondb/db_test.go
Labels: testing, cleanup

#1453 Ban usage of `t.Fatal` and `t.Error`
  .golangci.yml
  cache/lru_cache_benchmark_test.go
  cache/unique_cache_test.go
  chains/atomic/gsharedmemory/shared_memory_test.go
  chains/atomic/memory_test.go
  config/config_test.go
  genesis/genesis_test.go
  ids/aliases_test.go
  ids/bits_test.go
  ids/galiasreader/alias_reader_test.go
  ids/id_test.go
  ids/node_id.go
  ids/node_id_test.go
  ids/test_aliases.go
  indexer/index_test.go
  ipcs/socket/socket_test.go
  message/messages_test.go
  network/certs_test.go
  network/network_test.go
  network/peer/peer_test.go
  network/throttling/dial_throttler_test.go
  network/throttling/inbound_conn_throttler_test.go
  network/throttling/inbound_conn_upgrade_throttler_test.go
  network/throttling/inbound_msg_buffer_throttler_test.go
  network/throttling/inbound_msg_byte_throttler_test.go
  pubsub/filter_test.go
  snow/engine/snowman/transitive_test.go
  utils/beacon/set_test.go
  utils/cb58/cb58.go
  utils/cb58/cb58_test.go
  utils/compression/compressor_test.go
  utils/compression/type_test.go
  utils/constants/network_ids.go
  utils/constants/network_ids_test.go
  utils/crypto/bls/bls_benchmark_test.go
  utils/filesystem/rename_test.go
  utils/formatting/encoding_benchmark_test.go
  utils/formatting/encoding_test.go
  utils/formatting/int_format_test.go
  utils/hashing/consistent/ring_test.go
  utils/ips/ip_test.go
  utils/json/float32_test.go
  utils/logging/log_test.go
  utils/math/continuous_averager_test.go
  utils/math/meter/meter_test.go
  utils/sampler/uniform_test.go
  utils/sampler/weighted_test.go
  utils/sampler/weighted_without_replacement_benchmark_test.go
  utils/sampler/weighted_without_replacement_test.go
  utils/set/bits_64_test.go
  utils/set/set_test.go
  utils/timer/adaptive_timeout_manager.go
  utils/timer/adaptive_timeout_manager_test.go
  utils/timer/mockable/clock_test.go
  utils/window/window_test.go
  version/application_test.go
  version/compatibility_test.go
Labels: testing, cleanup

#1630 chore: fix typo in binary_snowflake.go
  snow/consensus/snowball/binary_snowflake.go
Labels: cleanup

#1606 Discriminate window fit err msg from overdelegated error msg
  vms/platformvm/txs/executor/proposal_tx_executor.go
  vms/platformvm/txs/executor/proposal_tx_executor_test.go
  vms/platformvm/txs/executor/staker_tx_verification.go
  vms/platformvm/txs/executor/staker_tx_verification_test.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/txs/validator.go
  vms/platformvm/txs/validator_test.go
Labels: vm, cleanup

#1388 Remove MaxConnectionAge gRPC StreamID overflow mitigation
  go.mod
  go.sum
  vms/rpcchainvm/grpcutils/server.go
Labels: dependencies, sdk, stability

#1635 add fuzzing action
  .github/workflows/fuzz.yml
Labels: testing

#1632 Remove dagState and GetUTXOFromID
  vms/avm/dag_state.go
  vms/avm/index_test.go
  vms/avm/service_test.go
  vms/avm/states/diff.go
  vms/avm/states/mock_states.go
  vms/avm/states/state.go
  vms/avm/txs/executor/semantic_verifier.go
  vms/avm/txs/executor/semantic_verifier_test.go
  vms/avm/unique_tx.go
  vms/avm/vm.go
  vms/avm/vm_regression_test.go
  vms/avm/vm_test.go
Labels: vm, cleanup

#1631 Update all AVM tests for post-linearization
  vms/avm/environment_test.go
  vms/avm/index_test.go
  vms/avm/service_test.go
  vms/avm/state_test.go
  vms/avm/static_service_test.go
  vms/avm/vm_benchmark_test.go
  vms/avm/vm_regression_test.go
  vms/avm/vm_test.go
  vms/avm/wallet_service_test.go
  vms/platformvm/vm_test.go
Labels: vm, testing, cleanup

#1641 Remove PendingTxs from the DAGVM interface
  snow/engine/avalanche/vertex/mock_vm.go
  snow/engine/avalanche/vertex/test_vm.go
  snow/engine/avalanche/vertex/vm.go
  vms/avm/vm.go
  vms/metervm/vertex_metrics.go
  vms/metervm/vertex_vm.go
  vms/tracedvm/vertex_vm.go
Labels: cleanup

#1642 Remove GetTx from the DAGVM interface
  indexer/indexer_test.go
  snow/engine/avalanche/vertex/mock_vm.go
  snow/engine/avalanche/vertex/test_vm.go
  snow/engine/avalanche/vertex/vm.go
  vms/avm/vm.go
  vms/avm/vm_test.go
  vms/metervm/vertex_metrics.go
  vms/metervm/vertex_vm.go
  vms/tracedvm/vertex_vm.go
Labels: cleanup

#1650 [x/merkledb] Remove useless `err` check
  x/merkledb/trieview.go
Labels: cleanup

#1649 [x/merkledb] Trailing whitespace removal on README
  x/merkledb/README.md
Labels: cleanup

#1643 Remove unneeded functions from UniqueTx
  snow/consensus/snowstorm/test_tx.go
  snow/consensus/snowstorm/tx.go
  snow/engine/avalanche/bootstrap/bootstrapper_test.go
  vms/avm/unique_tx.go
  vms/avm/vm.go
Labels: vm, cleanup

#1654 Simplify tx verification
  vms/avm/unique_tx.go
  vms/avm/vm.go
  vms/avm/wallet_service.go
Labels: vm, cleanup

#1653 `merkledb` -- fix `findNextKey`
  x/sync/sync_test.go
  x/sync/syncmanager.go
Labels: bug, merkledb

#1656 Cleanup X-chain UniqueTx Dependencies
  snow/consensus/snowstorm/test_tx.go
  snow/consensus/snowstorm/tx.go
  snow/engine/avalanche/bootstrap/bootstrapper_test.go
  snow/engine/avalanche/bootstrap/tx_job.go
  vms/avm/txs/base_tx_test.go
  vms/avm/txs/import_tx.go
  vms/avm/txs/mock_unsigned_tx.go
  vms/avm/txs/operation_tx.go
  vms/avm/txs/tx.go
  vms/avm/unique_tx.go
  vms/components/avax/base_tx.go
Labels: vm, cleanup

#1427 Prune X-chain State
  cache/empty_cache.go
  utils/timer/eta.go
  vms/avm/states/mock_states.go
  vms/avm/states/state.go
  vms/avm/vm.go
  vms/avm/vm_test.go
Labels: vm, incident response

#1103 Support building docker image on ARM64
  Dockerfile
  scripts/build_local_image.sh
  scripts/constants.sh
Labels: bug, ci, lifecycle/stale

#1660 remove goreleaser
  .github/workflows/build.yml
  .goreleaser.yml
Labels: ci

#1663 Improve metrics error message
  api/metrics/multi_gatherer.go
  api/metrics/optional_gatherer.go
Labels: monitoring, incident response

#1662 Remove X-chain UniqueTx
  vms/avm/chain_state.go
  vms/avm/service.go
  vms/avm/state_test.go
  vms/avm/states/mock_states.go
  vms/avm/states/state.go
  vms/avm/tx.go
  vms/avm/unique_tx.go
  vms/avm/vm.go
  vms/avm/vm_test.go
Labels: vm, cleanup

#1658 Add state checksums
  ids/id.go
  ids/id_test.go
  vms/avm/blocks/builder/builder_test.go
  vms/avm/blocks/executor/block.go
  vms/avm/blocks/executor/block_test.go
  vms/avm/states/mock_states.go
  vms/avm/states/state.go
  vms/avm/states/state_test.go
  vms/avm/txs/executor/executor_test.go
  vms/avm/vm.go
  vms/components/avax/utxo_fetching_test.go
  vms/components/avax/utxo_state.go
  vms/components/avax/utxo_state_test.go
  vms/platformvm/blocks/builder/helpers_test.go
  vms/platformvm/blocks/executor/acceptor.go
  vms/platformvm/blocks/executor/acceptor_test.go
  vms/platformvm/blocks/executor/helpers_test.go
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/vm.go
  vms/platformvm/vm_regression_test.go
Labels: enhancement, vm, monitoring, storage

#1638 Modify proposervm window
  utils/window/window.go
  utils/window/window_test.go
  vms/platformvm/validators/manager.go
Labels: enhancement, vm, warp

#1665 sorting nit
  utils/sorting.go
Labels: cleanup

#1629 `merkledb` -- rewrite and test range proof invariants; fix proof generation/veriifcation bugs
  x/merkledb/db.go
  x/merkledb/db_test.go
  x/merkledb/proof.go
  x/merkledb/proof_test.go
  x/merkledb/trieview.go
Labels: bug, merkledb

#1667 Add minimum proposer window length
  utils/window/window.go
  utils/window/window_test.go
  vms/platformvm/validators/manager.go
Labels: stability

#1636 CI -- only run fuzz tests on ubuntu
  .github/workflows/build-and-test.yml
  .github/workflows/build_and_test.sh
Labels: testing, ci

#1671 `MerkleDB` -- remove codec version
  x/merkledb/codec.go
  x/merkledb/codec_test.go
  x/merkledb/db.go
  x/merkledb/node.go
Labels: merkledb

#1590 `MerkleDB` -- use default config in all tests
  x/merkledb/db.go
  x/merkledb/db_test.go
  x/merkledb/history_test.go
  x/merkledb/metrics.go
  x/merkledb/metrics_test.go
  x/merkledb/proof.go
  x/merkledb/proof_test.go
  x/merkledb/trie_test.go
Labels: merkledb

#1672 `sync` -- reduce stuttering
  proto/pb/sync/sync.pb.go
  proto/pb/sync/sync_grpc.pb.go
  proto/sync/sync.proto
  x/sync/client.go
  x/sync/client_test.go
  x/sync/db.go
  x/sync/g_db/db_client.go
  x/sync/g_db/db_server.go
  x/sync/manager.go
  x/sync/mock_client.go
  x/sync/network_server.go
  x/sync/sync_test.go
  x/sync/workheap.go
  x/sync/workheap_test.go
Labels: cleanup

#1673 `Sync` -- unexport field
  x/sync/manager.go
  x/sync/sync_test.go
  x/sync/workheap.go
  x/sync/workheap_test.go
Labels: cleanup

#1674 `sync` -- nits and cleanup
  x/sync/manager.go
  x/sync/network_server.go
Labels: cleanup, merkledb

#1676 `sync` -- remove unused code
  x/sync/request.go
Labels: cleanup
