Repository ava-labs/avalanchego, pull requests merged in 2023-05, with the labels that each got.

#1449 style nits in vm clients
  vms/avm/client.go
  vms/platformvm/client.go
Labels: cleanup

#1461 utils/logging: add "Enabled" method to remove redundant verbo logs
  snow/engine/snowman/syncer/state_syncer.go
  snow/networking/sender/sender.go
  utils/logging/log.go
  utils/logging/logger.go
  utils/logging/mock_logger.go
  utils/logging/test_log.go
Labels: monitoring, cleanup

#1459 remove zstd check
  config/config.go
Labels: cleanup

#1458 use `require.IsType` for type assertions in tests
  api/auth/auth_test.go
  database/manager/manager_test.go
  indexer/indexer_test.go
  message/inbound_msg_builder_test.go
  message/messages_test.go
  network/throttling/bandwidth_throttler_test.go
  network/throttling/inbound_resource_throttler_test.go
  snow/consensus/snowball/unary_snowball_test.go
  snow/consensus/snowball/unary_snowflake_test.go
  snow/engine/avalanche/getter/getter_test.go
  snow/engine/snowman/bootstrap/bootstrapper_test.go
  snow/engine/snowman/getter/getter_test.go
  snow/engine/snowman/syncer/utils_test.go
  snow/networking/sender/sender_test.go
  snow/networking/tracker/resource_tracker_test.go
  snow/networking/tracker/targeter_test.go
  utils/buffer/unbounded_deque_test.go
  utils/dynamicip/updater_test.go
  utils/window/window_test.go
  vms/avm/blocks/block_test.go
  vms/avm/blocks/builder/builder_test.go
  vms/avm/network/network_test.go
  vms/components/chain/state_test.go
  vms/components/message/message_test.go
  vms/components/message/tx_test.go
  vms/platformvm/blocks/builder/builder_test.go
  vms/platformvm/blocks/executor/manager_test.go
  vms/platformvm/blocks/parse_test.go
  vms/platformvm/service_test.go
  vms/platformvm/txs/executor/reward_validator_test.go
  vms/platformvm/vm_test.go
  vms/proposervm/batched_vm_test.go
  vms/proposervm/post_fork_block_test.go
  vms/proposervm/post_fork_option_test.go
  vms/proposervm/pre_fork_block_test.go
  vms/proposervm/vm_byzantine_test.go
  vms/proposervm/vm_test.go
  vms/rpcchainvm/batched_vm_test.go
  vms/secp256k1fx/keychain_test.go
  x/merkledb/db_test.go
  x/merkledb/trie_test.go
Labels: testing, cleanup

#1470 ban `require.NotEqualValues`
  .golangci.yml
  network/peer/ip_signer_test.go
  utils/sampler/uniform_test.go
Labels: testing, cleanup

#1471 use `require` in `api` and `utils/password` packages
  api/admin/client_test.go
  api/admin/service_test.go
  api/auth/auth_test.go
  api/health/health_test.go
  api/health/service_test.go
  api/info/service_test.go
  api/keystore/keystore.go
  api/keystore/service_test.go
  api/metrics/multi_gatherer_test.go
  api/metrics/optional_gatherer_test.go
  api/server/router.go
  api/server/router_test.go
  utils/password/hash_test.go
  utils/password/password.go
  utils/password/password_test.go
Labels: testing, cleanup

#1464 use "golang.org/x/term" as "golang.org/x/crypto/ssh/terminal" is deprecated
  go.mod
  go.sum
  utils/logging/format.go
Labels: cleanup

#1484 chains: move "msgChan" closer to the first use (readability)
  chains/manager.go
Labels: cleanup

#1486 ban function params for `require.ErrorIs`
  codec/test_codec.go
  scripts/lint.sh
  snow/choices/status_test.go
  snow/consensus/snowman/consensus_test.go
  vms/platformvm/blocks/executor/standard_block_test.go
  vms/platformvm/signer/proof_of_possession_test.go
  vms/platformvm/txs/add_delegator_test.go
  vms/platformvm/txs/add_subnet_validator_test.go
  vms/platformvm/txs/add_validator_test.go
  vms/platformvm/txs/executor/reward_validator_test.go
  vms/platformvm/txs/subnet_validator_test.go
  vms/proposervm/state_syncable_vm_test.go
  vms/registry/vm_registerer_test.go
  vms/secp256k1fx/credential_test.go
  vms/secp256k1fx/fx_test.go
  vms/secp256k1fx/input_test.go
  vms/secp256k1fx/mint_operation_test.go
  vms/secp256k1fx/mint_output_test.go
  vms/secp256k1fx/output_owners_test.go
  vms/secp256k1fx/transfer_input_test.go
  vms/secp256k1fx/transfer_output_test.go
Labels: testing, cleanup

#1492 fix license header test
  LICENSE.header
  ipcs/socket/socket_unix.go
  ipcs/socket/socket_windows.go
  license.yml
  scripts/lint.sh
  scripts/mock.gen.sh
  snow/engine/snowman/block/height_indexed_vm.go
  utils/linkedhashmap/iterator.go
  utils/linkedhashmap/linkedhashmap.go
  utils/storage/storage_unix.go
  utils/storage/storage_windows.go
  vms/rpcchainvm/runtime/subprocess/linux_stopper.go
  vms/rpcchainvm/runtime/subprocess/non_linux_stopper.go
Labels: bug, ci, cleanup

#1493 use blank identifier for interface compliance
  scripts/lint.sh
  vms/avm/txs/mempool/mempool.go
  vms/rpcchainvm/gruntime/runtime_server.go
  x/merkledb/batch.go
  x/merkledb/db.go
  x/merkledb/iterator.go
  x/merkledb/metrics.go
  x/merkledb/trieview.go
  x/sync/client.go
  x/sync/metrics.go
  x/sync/network_client.go
  x/sync/response_handler.go
  x/sync/sync_test.go
  x/sync/syncworkheap.go
Labels: ci, cleanup

#1481 codec: remove "SetMaxSize" from "Manager", remove unnecessary lock
  codec/manager.go
  codec/mock_manager.go
Labels: cleanup

#1495 ban `require.Equal` when testing for `0`
  codec/test_codec.go
  database/manager/manager_test.go
  database/test_database.go
  scripts/lint.sh
  snow/engine/common/requests_test.go
  snow/networking/benchlist/benchlist_test.go
  snow/networking/router/chain_router_test.go
  utils/bag/bag_test.go
  utils/bag/unique_bag_test.go
  utils/beacon/set_test.go
  utils/buffer/bounded_nonblocking_queue_test.go
  utils/buffer/unbounded_deque_test.go
  utils/linkedhashmap/linkedhashmap_test.go
  utils/math/continuous_averager_test.go
  utils/math/safe_math_test.go
  utils/sampler/weighted_test.go
  utils/sorting_test.go
  utils/window/window_test.go
  vms/avm/service_test.go
  vms/secp256k1fx/keychain_test.go
  x/merkledb/cache_test.go
  x/merkledb/path_test.go
  x/merkledb/trie_test.go
  x/sync/sync_test.go
  x/sync/syncworkheap_test.go
Labels: testing

#1509 Remove comment referencing old IP based tracking
  network/network.go
Labels: documentation, networking, cleanup

#1496 ban usage of `require.Len` when testing for length `0`
  indexer/indexer_test.go
  network/throttling/bandwidth_throttler_test.go
  network/throttling/inbound_msg_buffer_throttler_test.go
  network/throttling/inbound_msg_byte_throttler_test.go
  network/throttling/outbound_msg_throttler_test.go
  scripts/lint.sh
  snow/consensus/snowman/poll/set_test.go
  snow/engine/snowman/block/batched_vm_test.go
  snow/networking/benchlist/benchlist_test.go
  snow/networking/handler/message_queue_test.go
  utils/bag/bag_test.go
  utils/sampler/weighted_without_replacement_test.go
  utils/set/set_test.go
  utils/sorting_test.go
  vms/avm/service_test.go
  vms/components/chain/state_test.go
  x/merkledb/cache_test.go
  x/merkledb/history_test.go
  x/sync/syncworkheap_test.go
Labels: testing

#1497 ban usage of `require.Equal` when testing for length
  codec/test_codec.go
  database/manager/manager_test.go
  scripts/lint.sh
  snow/engine/common/queue/jobs_test.go
  utils/buffer/unbounded_deque_test.go
  utils/sampler/rand_test.go
  utils/set/set_test.go
  vms/platformvm/service_test.go
  vms/platformvm/txs/executor/import_test.go
  vms/platformvm/vm_test.go
  vms/platformvm/warp/validator_test.go
  x/merkledb/history_test.go
  x/merkledb/node_test.go
  x/merkledb/proof_test.go
  x/merkledb/trie_test.go
Labels: testing

#1498 ban usage of `nil` in require functions
  api/keystore/service_test.go
  database/test_database.go
  scripts/lint.sh
  snow/engine/snowman/syncer/utils_test.go
  vms/avm/txs/mempool/mempool_test.go
  vms/platformvm/blocks/builder/network_test.go
  vms/platformvm/txs/executor/create_subnet_test.go
  vms/platformvm/txs/mempool/mempool_test.go
Labels: testing

#1517 Sized LRU cache
  cache/cache.go
  cache/lru_cache.go
  cache/lru_cache_test.go
  cache/lru_sized_cache.go
  cache/lru_sized_cache_test.go
  cache/metercacher/cache.go
  cache/metercacher/cache_test.go
  cache/metercacher/metrics.go
  cache/test_cacher.go
  vms/platformvm/service_test.go
  vms/platformvm/state/state.go
  vms/platformvm/txs/tx.go
Labels: vm

#1444 engine/snowman: clean up some comments in "bubbleVotes" unit tests
  snow/engine/snowman/transitive_test.go
Labels: documentation, consensus, testing, cleanup

#1504 snow/networking/sender: add missing verbo check
  snow/engine/avalanche/bootstrap/bootstrapper.go
  snow/engine/snowman/transitive.go
  snow/networking/handler/handler.go
  snow/networking/sender/sender.go
Labels: monitoring, cleanup

#1518 Delete duplicate test var definitions
  vms/platformvm/blocks/builder/helpers_test.go
  vms/platformvm/blocks/executor/helpers_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/vm_test.go
Labels: testing, cleanup

#1526 Fix incorrect test refactor
  cache/test_cacher.go
Labels: testing

#1284 Pchain validators repackaging
  snow/validators/manager.go
  vms/platformvm/blocks/builder/helpers_test.go
  vms/platformvm/blocks/executor/acceptor.go
  vms/platformvm/blocks/executor/acceptor_test.go
  vms/platformvm/blocks/executor/helpers_test.go
  vms/platformvm/blocks/executor/manager.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/validators/manager.go
  vms/platformvm/validators/manager_test.go
  vms/platformvm/validators/test_manager.go
  vms/platformvm/vm.go
  vms/platformvm/vm_test.go
Labels: vm, cleanup

#1370 Config overhaul
  chains/manager.go
  config/config.go
  config/flags.go
  config/keys.go
  node/config.go
  node/node.go
  utils/constants/networking.go
Labels: cleanup

#1362 Deprecate uptimes in pong message
  message/messages_test.go
  message/mock_outbound_message_builder.go
  message/outbound_msg_builder.go
  network/peer/message_queue_test.go
  network/peer/peer.go
  proto/p2p/p2p.proto
  proto/pb/p2p/p2p.pb.go
Labels: networking, cleanup

#1334 Add CPU cycles and number of disk read/write metrics by pid
  node/node.go
  utils/resource/metrics.go
  utils/resource/usage.go
  vms/registry/vm_getter_test.go
Labels: monitoring

#1543 Fetch process resource stats as best-effort
  node/node.go
  utils/resource/usage.go
  vms/registry/vm_getter_test.go
Labels: bug, monitoring

#1513 Add serialization tests for transactions added in Banff
  vms/platformvm/txs/add_permissionless_delegator_tx_test.go
  vms/platformvm/txs/add_permissionless_validator_tx_test.go
  vms/platformvm/txs/remove_subnet_validator_tx_test.go
  vms/platformvm/txs/transform_subnet_tx_test.go
Labels: documentation, testing

#1545 Log chain shutdown duration
  snow/networking/handler/handler.go
  snow/networking/handler/mock_handler.go
  snow/networking/router/chain_router.go
  snow/networking/router/chain_router_test.go
Labels: monitoring

#1552 Bump Protobuf and tooling and add section to proto docs outlining buf publishing
  .github/workflows/buf-lint.yml
  go.mod
  go.sum
  proto/README.md
  proto/pb/aliasreader/aliasreader.pb.go
  proto/pb/aliasreader/aliasreader_grpc.pb.go
  proto/pb/appsender/appsender.pb.go
  proto/pb/appsender/appsender_grpc.pb.go
  proto/pb/http/http.pb.go
  proto/pb/http/http_grpc.pb.go
  proto/pb/http/responsewriter/responsewriter.pb.go
  proto/pb/http/responsewriter/responsewriter_grpc.pb.go
  proto/pb/io/reader/reader.pb.go
  proto/pb/io/reader/reader_grpc.pb.go
  proto/pb/io/writer/writer.pb.go
  proto/pb/io/writer/writer_grpc.pb.go
  proto/pb/keystore/keystore.pb.go
  proto/pb/keystore/keystore_grpc.pb.go
  proto/pb/message/tx.pb.go
  proto/pb/messenger/messenger.pb.go
  proto/pb/messenger/messenger_grpc.pb.go
  proto/pb/net/conn/conn.pb.go
  proto/pb/net/conn/conn_grpc.pb.go
  proto/pb/p2p/p2p.pb.go
  proto/pb/rpcdb/rpcdb.pb.go
  proto/pb/rpcdb/rpcdb_grpc.pb.go
  proto/pb/sharedmemory/sharedmemory.pb.go
  proto/pb/sharedmemory/sharedmemory_grpc.pb.go
  proto/pb/sync/sync.pb.go
  proto/pb/validatorstate/validator_state.pb.go
  proto/pb/validatorstate/validator_state_grpc.pb.go
  proto/pb/vm/runtime/runtime.pb.go
  proto/pb/vm/runtime/runtime_grpc.pb.go
  proto/pb/vm/vm.pb.go
  proto/pb/vm/vm_grpc.pb.go
  proto/pb/warp/message.pb.go
  proto/pb/warp/message_grpc.pb.go
  proto/sync/sync.proto
  scripts/protobuf_codegen.sh
  x/sync/client.go
  x/sync/client_test.go
  x/sync/network_server.go
  x/sync/network_server_test.go
  x/sync/sync_test.go
  x/sync/syncmanager.go
Labels: bug, documentation

#1554 Minor pchain UTs cleanup
  vms/platformvm/blocks/builder/helpers_test.go
  vms/platformvm/blocks/executor/helpers_test.go
  vms/platformvm/txs/executor/helpers_test.go
Labels: testing

#1443 Add workflow to mark stale issues and PRs
  .github/workflows/stale.yml
Labels: ci

#1555 `x/sync` / `x/merkledb` -- add `SyncableDB` interface
  x/merkledb/db.go
  x/merkledb/trie.go
  x/sync/client.go
  x/sync/client_test.go
  x/sync/mock_client.go
  x/sync/network_server.go
  x/sync/sync_test.go
  x/sync/syncable_db.go
  x/sync/syncmanager.go
Labels: merkledb

#1546 `x/sync` -- Remove `EncodeProof`, `DecodeProof`, helpers
  x/merkledb/codec.go
  x/merkledb/codec_test.go
  x/merkledb/proof_test.go
Labels: merkledb

#1439 Rename beacon to boostrapper, define bootstrappers in JSON file for cross-language compatiblity
  config/config.go
  config/flags.go
  genesis/beacons.go
  genesis/bootstrappers.go
  genesis/bootstrappers.json
  genesis/bootstrappers_test.go
  network/example_test.go
  node/config.go
  node/node.go
  utils/ips/ip_port.go
  utils/ips/ip_test.go
Labels: cleanup

#1447 add P-chain height indexing
  vms/avm/service.go
  vms/avm/service_test.go
  vms/avm/states/diff.go
  vms/avm/states/mock_states.go
  vms/avm/states/state.go
  vms/avm/states/state_test.go
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/state.go
Labels: vm

#1448 Add P-chain `GetBlockByHeight` API method
  vms/platformvm/client.go
  vms/platformvm/service.go
  vms/platformvm/service_test.go
Labels: vm

#1537 `x/sync` -- use for sending Range Proofs
  proto/pb/sync/sync.pb.go
  proto/sync/sync.proto
  utils/hashing/hashing.go
  x/merkledb/codec.go
  x/merkledb/codec_test.go
  x/merkledb/proof.go
  x/merkledb/proof_test.go
  x/sync/client.go
  x/sync/client_test.go
  x/sync/network_server.go
  x/sync/network_server_test.go
Labels: merkledb

#1560 Add test to ensure that database packing produces sorted values
  database/helpers_test.go
  utils/sorting.go
  utils/sorting_test.go
Labels: testing, storage
