Repository ava-labs/avalanchego, pull requests merged in 2023-10, with the labels that each got.

#2115 Fix consensus engine interface comments
  snow/engine/common/engine.go
Labels: documentation

#2129 Standardize consensus variable names in tests
  snow/engine/common/test_sender.go
  snow/engine/snowman/bootstrap/bootstrapper_test.go
Labels: consensus, testing, cleanup

#2130 Prevent bytesNeeded overflow
  x/merkledb/codec_test.go
  x/merkledb/path.go
Labels: bug, storage, merkledb

#2045 Migrate xsvm from github.com/ava-labs/xsvm
  scripts/build_xsvm.sh
  vms/example/xsvm/README.md
  vms/example/xsvm/api/client.go
  vms/example/xsvm/api/server.go
  vms/example/xsvm/block/block.go
  vms/example/xsvm/block/codec.go
  vms/example/xsvm/builder/builder.go
  vms/example/xsvm/chain/block.go
  vms/example/xsvm/chain/chain.go
  vms/example/xsvm/cmd/account/cmd.go
  vms/example/xsvm/cmd/account/flags.go
  vms/example/xsvm/cmd/chain/cmd.go
  vms/example/xsvm/cmd/chain/create/cmd.go
  vms/example/xsvm/cmd/chain/create/flags.go
  vms/example/xsvm/cmd/chain/genesis/cmd.go
  vms/example/xsvm/cmd/chain/genesis/flags.go
  vms/example/xsvm/cmd/issue/cmd.go
  vms/example/xsvm/cmd/issue/export/cmd.go
  vms/example/xsvm/cmd/issue/export/flags.go
  vms/example/xsvm/cmd/issue/importtx/cmd.go
  vms/example/xsvm/cmd/issue/importtx/flags.go
  vms/example/xsvm/cmd/issue/transfer/cmd.go
  vms/example/xsvm/cmd/issue/transfer/flags.go
  vms/example/xsvm/cmd/run/cmd.go
  vms/example/xsvm/cmd/version/cmd.go
  vms/example/xsvm/cmd/xsvm/main.go
  vms/example/xsvm/constants.go
  vms/example/xsvm/execute/block.go
  vms/example/xsvm/execute/expects_context.go
  vms/example/xsvm/execute/genesis.go
  vms/example/xsvm/execute/tx.go
  vms/example/xsvm/factory.go
  vms/example/xsvm/genesis/codec.go
  vms/example/xsvm/genesis/genesis.go
  vms/example/xsvm/genesis/genesis_test.go
  vms/example/xsvm/state/keys.go
  vms/example/xsvm/state/storage.go
  vms/example/xsvm/tx/codec.go
  vms/example/xsvm/tx/export.go
  vms/example/xsvm/tx/import.go
  vms/example/xsvm/tx/payload.go
  vms/example/xsvm/tx/transfer.go
  vms/example/xsvm/tx/tx.go
  vms/example/xsvm/tx/unsigned.go
  vms/example/xsvm/tx/visitor.go
  vms/example/xsvm/vm.go
Labels: warp, e2e-subnets

#2132 Fix handling of wg in the networking dial test
  network/network_test.go
Labels: bug, testing, networking

#2133 Update go.mod and add update check
  .github/workflows/auto-generated-checker.yml
  go.mod
Labels: testing, ci

#2123 RPCChainVM fail-fast health RPCs
  vms/rpcchainvm/factory.go
  vms/rpcchainvm/grpcutils/client_test.go
  vms/rpcchainvm/state_syncable_vm_test.go
  vms/rpcchainvm/vm_client.go
Labels: incident response

#2128 MerkleDB allow warming node cache
  x/merkledb/db.go
Labels: merkledb

#2138 Add vote bubbling metrics
  snow/engine/snowman/metrics.go
  snow/engine/snowman/voter.go
Labels: consensus, monitoring

#2141 Reduce log level of an error during Prune
  vms/avm/vm.go
Labels: monitoring

#2140 Exit chain creation routine before shutting down chain router
  chains/manager.go
Labels: bug

#2142 Merkle db fix type cast bug
  x/sync/manager.go
Labels: merkledb

#2116 Add Warp Payload Types
  vms/platformvm/warp/payload/README.md
  vms/platformvm/warp/payload/addressed_call.go
  vms/platformvm/warp/payload/addressed_call_test.go
  vms/platformvm/warp/payload/codec.go
  vms/platformvm/warp/payload/hash.go
  vms/platformvm/warp/payload/hash_test.go
  vms/platformvm/warp/payload/payload.go
  vms/platformvm/warp/payload/payload_test.go
Labels: sdk, warp

#2102 Add height voting for chits
  message/inbound_msg_builder.go
  message/inbound_msg_builder_test.go
  message/mock_outbound_message_builder.go
  message/outbound_msg_builder.go
  proto/p2p/p2p.proto
  proto/pb/p2p/p2p.pb.go
  snow/engine/common/engine.go
  snow/engine/common/no_ops_handlers.go
  snow/engine/common/sender.go
  snow/engine/common/test_engine.go
  snow/engine/common/test_sender.go
  snow/engine/common/traced_engine.go
  snow/engine/snowman/metrics.go
  snow/engine/snowman/transitive.go
  snow/engine/snowman/transitive_test.go
  snow/engine/snowman/voter.go
  snow/networking/handler/handler.go
  snow/networking/handler/handler_test.go
  snow/networking/handler/message_queue_test.go
  snow/networking/router/chain_router_test.go
  snow/networking/sender/sender.go
  snow/networking/sender/sender_test.go
  snow/networking/sender/traced_sender.go
Labels: consensus, networking, bubble votes

#2135 Add Heap Queue
  utils/heap/queue.go
  utils/heap/queue_test.go
  vms/platformvm/state/merged_iterator.go
  vms/platformvm/state/staker_diff_iterator.go
Labels: cleanup

#2145 Add additional payload.Hash examples
  vms/platformvm/warp/payload/README.md
Labels: documentation

#2125 Split Alpha into AlphaPreference and AlphaConfidence
  config/config.go
  config/config_test.go
  config/flags.go
  config/keys.go
  snow/consensus/snowball/binary_snowball.go
  snow/consensus/snowball/binary_snowball_test.go
  snow/consensus/snowball/binary_snowflake.go
  snow/consensus/snowball/binary_snowflake_test.go
  snow/consensus/snowball/consensus.go
  snow/consensus/snowball/consensus_performance_test.go
  snow/consensus/snowball/consensus_reversibility_test.go
  snow/consensus/snowball/flat.go
  snow/consensus/snowball/flat_test.go
  snow/consensus/snowball/nnary_snowball.go
  snow/consensus/snowball/nnary_snowball_test.go
  snow/consensus/snowball/nnary_snowflake.go
  snow/consensus/snowball/nnary_snowflake_test.go
  snow/consensus/snowball/parameters.go
  snow/consensus/snowball/parameters_test.go
  snow/consensus/snowball/tree.go
  snow/consensus/snowball/tree_test.go
  snow/consensus/snowball/unary_snowball.go
  snow/consensus/snowball/unary_snowball_test.go
  snow/consensus/snowman/consensus_test.go
  snow/consensus/snowman/poll/early_term_no_traversal.go
  snow/consensus/snowman/poll/early_term_no_traversal_test.go
  snow/consensus/snowman/poll/set_test.go
  snow/consensus/snowman/topological.go
  snow/engine/snowman/config_test.go
  snow/engine/snowman/transitive.go
  snow/engine/snowman/transitive_test.go
  snow/networking/handler/health_test.go
  subnets/config_test.go
  vms/platformvm/vm_test.go
Labels: enhancement, consensus

#2158 Fix typo in block formation logic documentation
  vms/platformvm/docs/block_formation_logic.md
Labels: documentation

#2153 Marshal blocks and transactions inside API calls
  api/common_args_responses.go
  vms/avm/service.go
  vms/avm/service_test.go
  vms/platformvm/service.go
  vms/platformvm/service_test.go
Labels: consensus, vm, cleanup

#2149 Remove lock options from the info api
  api/info/service.go
  node/node.go
Labels: consensus, cleanup

#2154 Remove write lock option from the avm static API
  vms/avm/vm.go
Labels: consensus, vm, cleanup

#2155 Remove write lock option from the avm wallet API
  vms/avm/vm.go
  vms/avm/wallet_service.go
  vms/avm/wallet_service_test.go
Labels: consensus, vm, cleanup

#2161 Fix json marshalling of Sets
  utils/set/set.go
  utils/set/set_test.go
Labels: bug, monitoring

#2162 Rename `removeSubnetValidatorValidation` to `verifyRemoveSubnetValidatorTx`
  vms/platformvm/txs/executor/staker_tx_verification.go
  vms/platformvm/txs/executor/standard_tx_executor.go
Labels: vm, cleanup

#2151 Remove lock options from the IPCs api
  api/ipcs/service.go
  node/node.go
Labels: consensus, cleanup

#2152 Remove write lock option from the xsvm API
  vms/example/xsvm/api/server.go
  vms/example/xsvm/vm.go
Labels: consensus, vm, cleanup

#2150 Remove lock options from the admin API
  api/admin/service.go
  node/node.go
Labels: consensus, cleanup

#2163 Remove aliasing of `math` standard lib
  .golangci.yml
  network/network.go
  snow/engine/common/bootstrapper.go
  snow/engine/snowman/syncer/state_syncer.go
  snow/engine/snowman/syncer/state_syncer_test.go
  snow/validators/set_test.go
  utils/sampler/weighted_test.go
  utils/sampler/weighted_without_replacement_test.go
  vms/avm/states/state.go
  vms/avm/txs/executor/syntactic_verifier_test.go
  vms/platformvm/service.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
  vms/platformvm/txs/add_permissionless_delegator_tx_test.go
  vms/platformvm/txs/add_permissionless_validator_tx_test.go
  vms/platformvm/txs/executor/staker_tx_verification.go
  vms/platformvm/utxo/handler_test.go
  x/sync/peer_tracker.go
Labels: cleanup

#2157 Remove write lock option from the platformvm API
  vms/platformvm/service.go
  vms/platformvm/service_test.go
  vms/platformvm/vm.go
Labels: consensus, vm, cleanup

#2156 Remove write lock option from the avm rpc API
  vms/avm/service.go
  vms/avm/service_test.go
  vms/avm/vm.go
Labels: consensus, vm, cleanup

#2165 Remove context lock from API VM interface
  api/server/middleware_handler.go
  api/server/mock_server.go
  api/server/server.go
  go.mod
  go.sum
  indexer/indexer.go
  indexer/indexer_test.go
  node/node.go
  proto/pb/vm/vm.pb.go
  proto/vm/vm.proto
  snow/engine/avalanche/vertex/mock_vm.go
  snow/engine/common/http_handler.go
  snow/engine/common/test_vm.go
  snow/engine/common/vm.go
  snow/engine/snowman/block/mocks/chain_vm.go
  vms/avm/vm.go
  vms/example/xsvm/vm.go
  vms/platformvm/vm.go
  vms/registry/vm_registerer.go
  vms/registry/vm_registerer_test.go
  vms/rpcchainvm/vm_client.go
  vms/rpcchainvm/vm_server.go
Labels: consensus, vm, cleanup

#2164 Use set.Of rather than set.Add
  genesis/genesis.go
  message/ops.go
  network/network_test.go
  node/node.go
  snow/engine/avalanche/getter/getter.go
  snow/engine/avalanche/getter/getter_test.go
  snow/engine/common/queue/jobs_test.go
  snow/engine/snowman/getter/getter_test.go
  snow/engine/snowman/transitive_test.go
  snow/event/blocker_test.go
  snow/networking/router/chain_router_test.go
  snow/networking/sender/sender_test.go
  snow/validators/set_test.go
  vms/avm/vm_benchmark_test.go
  vms/components/avax/utxo_fetching_test.go
  vms/platformvm/txs/executor/reward_validator_test.go
  vms/platformvm/vm_test.go
  wallet/subnet/primary/examples/get-p-chain-balance/main.go
  wallet/subnet/primary/examples/get-x-chain-balance/main.go
Labels: cleanup

#2167 [x/merkledb] `Prefetcher` interface
  x/merkledb/db.go
  x/merkledb/mock_db.go
Labels: storage

#2037 Validator Diffs: docs and UTs cleanup
  vms/platformvm/docs/validators_versioning.md
  vms/platformvm/validator_set_property_test.go
Labels: warp

#2117 Fix some P-chain UTs
  vms/platformvm/vm_test.go
Labels: vm, testing, cleanup

#2184 Update cgo usage
  scripts/constants.sh
  scripts/mock.gen.sh
Labels: ci

#2168 Deprecate IPC configs
  config/config.go
Labels: cleanup

#2181 Update P2P proto docs
  proto/p2p/p2p.proto
  proto/pb/p2p/p2p.pb.go
Labels: documentation, networking

#2195 Deprecate keystore config
  config/config.go
Labels: cleanup

#2194 Add tests for BanffBlock serialization
  vms/platformvm/block/serialization_test.go
Labels: testing

#2179 Move Shutdown lock from Handler into Engines
  snow/engine/avalanche/bootstrap/bootstrapper.go
  snow/engine/snowman/bootstrap/bootstrapper.go
  snow/engine/snowman/syncer/state_syncer.go
  snow/engine/snowman/transitive.go
  snow/networking/handler/handler.go
Labels: bug, consensus

#2173 Move HealthCheck lock from Handler into Engines
  snow/engine/avalanche/bootstrap/bootstrapper.go
  snow/engine/snowman/bootstrap/bootstrapper.go
  snow/engine/snowman/syncer/state_syncer.go
  snow/engine/snowman/transitive.go
  snow/networking/handler/health.go
Labels: consensus

#2137 Implement Heap Map
  snow/engine/avalanche/bootstrap/bootstrapper.go
  snow/engine/avalanche/vertex/heap.go
  snow/engine/avalanche/vertex/heap_test.go
  snow/networking/benchlist/benchlist.go
  snow/networking/benchlist/benchlist_test.go
  utils/heap/map.go
  utils/heap/map_test.go
  utils/math/averager_heap.go
  utils/math/averager_heap_test.go
  utils/timer/adaptive_timeout_manager.go
  vms/platformvm/txs/txheap/by_age.go
  vms/platformvm/txs/txheap/by_end_time.go
  vms/platformvm/txs/txheap/by_end_time_test.go
  vms/platformvm/txs/txheap/by_start_time.go
  vms/platformvm/txs/txheap/heap.go
  x/sync/peer_tracker.go
Labels: cleanup

#2182 Move selectStartGear lock from Handler into Engines
  snow/engine/avalanche/bootstrap/bootstrapper.go
  snow/engine/common/bootstrapable.go
  snow/engine/common/test_bootstrapable.go
  snow/engine/common/traced_bootstrapable_engine.go
  snow/engine/snowman/bootstrap/bootstrapper.go
  snow/engine/snowman/syncer/state_syncer.go
  snow/networking/handler/handler.go
Labels: consensus

#2203 Update local network readme
  README.md
Labels: documentation

#1510 Use custom codec for validator metadata
  api/keystore/codec.go
  codec/linearcodec/codec.go
  codec/linearcodec/codec_test.go
  vms/platformvm/state/metadata_codec.go
  vms/platformvm/state/metadata_delegator.go
  vms/platformvm/state/metadata_validator.go
  vms/platformvm/state/metadata_validator_test.go
  vms/platformvm/state/state.go
Labels: vm, continuous staking

#2205 Add RSA max key length test
  staking/large_rsa_key.cert
  staking/large_rsa_key.sig
  staking/verify_test.go
Labels: testing

#2204 Remove duplicate networking check
  network/network.go
Labels: networking, cleanup

#2209 Update TestDialContext to use ManuallyTrack
  network/network_test.go
Labels: networking

#2198 Remove contains from validator manager interface
  chains/manager.go
  network/network.go
  network/peer/peer.go
  node/beacon_manager.go
  snow/engine/common/bootstrapper.go
  snow/engine/snowman/bootstrap/bootstrapper.go
  snow/engine/snowman/syncer/state_syncer.go
  snow/networking/handler/handler.go
  snow/validators/manager.go
  snow/validators/manager_test.go
  snow/validators/overridden_manager.go
  snow/validators/set.go
  snow/validators/set_test.go
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/block/executor/standard_block_test.go
  vms/platformvm/service.go
  vms/platformvm/txs/executor/advance_time_test.go
  vms/platformvm/vm_test.go
Labels: cleanup

#2199 Move the overridden manager into the node
  chains/manager.go
  node/node.go
  node/overridden_manager.go
  node/overridden_manager_test.go
  snow/networking/benchlist/manager.go
Labels: networking, cleanup

#2213 Remove `aggregate` struct
  utils/wrappers/errors.go
Labels: cleanup

#2215 Add log for ungraceful shutdown on startup
  node/node.go
Labels: monitoring, incident response

#1999 Add pebble database implementation
  database/iterator.go
  database/pebble/batch.go
  database/pebble/batch_test.go
  database/pebble/db.go
  database/pebble/db_test.go
  database/pebble/iterator.go
  database/test_database.go
  go.mod
  go.sum
Labels: storage

#2178 Add `TransferSubnetOwnershipTx`
  vms/platformvm/block/codec.go
  vms/platformvm/metrics/tx_metrics.go
  vms/platformvm/txs/builder/builder.go
  vms/platformvm/txs/builder/mock_builder.go
  vms/platformvm/txs/codec.go
  vms/platformvm/txs/executor/atomic_tx_executor.go
  vms/platformvm/txs/executor/proposal_tx_executor.go
  vms/platformvm/txs/executor/staker_tx_verification.go
  vms/platformvm/txs/executor/standard_tx_executor.go
  vms/platformvm/txs/executor/tx_mempool_verifier.go
  vms/platformvm/txs/mempool/issuer.go
  vms/platformvm/txs/mempool/remover.go
  vms/platformvm/txs/transfer_subnet_ownership_tx.go
  vms/platformvm/txs/transfer_subnet_ownership_tx_test.go
  vms/platformvm/txs/visitor.go
  vms/platformvm/vm_test.go
  wallet/chain/p/backend_visitor.go
  wallet/chain/p/signer_visitor.go
Labels: enhancement, vm

#2219 Revert networking AllowConnection change
  network/network.go
  network/network_test.go
Labels: bug, networking

#2221 Fix unexpected unlock
  snow/networking/handler/handler.go
  snow/networking/handler/handler_test.go
Labels: bug, consensus

#2224 Improve logging for block verification failure
  snow/engine/snowman/transitive.go
  vms/proposervm/block.go
  vms/proposervm/pre_fork_block.go
Labels: monitoring, incident response

#2201 Reduce allocations on insert and remove
  x/merkledb/db.go
  x/merkledb/trie_test.go
  x/merkledb/trieview.go
Labels: merkledb

#2218 `merkledb` -- shift nit
  x/merkledb/key.go
Labels: cleanup, merkledb

#2228 Update `golangci-lint` to `v1.55.1`
  .golangci.yml
  api/auth/auth_test.go
  config/config_test.go
  ids/id_test.go
  scripts/lint.sh
  snow/consensus/snowball/tree_test.go
  utils/timer/adaptive_timeout_manager_test.go
  vms/avm/txs/import_tx.go
  vms/avm/vm.go
  vms/components/avax/base_tx.go
  vms/components/avax/utxo_id_test.go
  vms/platformvm/service.go
  vms/platformvm/txs/executor/standard_tx_executor.go
  vms/platformvm/utxo/handler.go
  wallet/chain/x/builder.go
Labels: ci

#2227 Add json marshal tests to existing serialization tests in `platformvm/txs` pkg
  vms/platformvm/txs/add_permissionless_delegator_tx_test.go
  vms/platformvm/txs/base_tx_test.go
  vms/platformvm/txs/remove_subnet_validator_tx_test.go
  vms/platformvm/txs/transform_subnet_tx_test.go
Labels: testing

#2222 Move all blst function usage to `bls` pkg
  snow/validators/gvalidators/validator_state_client.go
  snow/validators/gvalidators/validator_state_server.go
  snow/validators/gvalidators/validator_state_test.go
  tests/fixture/testnet/config.go
  utils/crypto/bls/public.go
  utils/crypto/bls/secret.go
  vms/platformvm/state/state.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/warp/signature_test.go
  vms/platformvm/warp/validator.go
  vms/platformvm/warp/validator_test.go
Labels: cleanup

#2217 `merkledb` -- don't pass `BranchFactor` to `encodeDBNode`
  x/merkledb/codec.go
  x/merkledb/codec_test.go
  x/merkledb/node.go
Labels: cleanup, merkledb

#2212 Add `utils.Err` helper
  api/server/metrics.go
  database/leveldb/metrics.go
  genesis/config.go
  indexer/index.go
  ipcs/eventsocket.go
  network/metrics.go
  network/network.go
  network/p2p/gossip/gossip.go
  network/p2p/gossip/handler.go
  network/peer/gossip_tracker_metrics.go
  network/throttling/inbound_resource_throttler.go
  network/throttling/outbound_msg_throttler.go
  node/node.go
  snow/consensus/metrics/polls.go
  snow/engine/avalanche/bootstrap/metrics.go
  snow/engine/common/queue/jobs.go
  snow/engine/common/queue/state.go
  snow/engine/common/tracker/peers.go
  snow/engine/snowman/bootstrap/metrics.go
  snow/networking/router/chain_router_metrics.go
  snow/networking/tracker/resource_tracker.go
  utils/error.go
  utils/metric/api_interceptor.go
  utils/resource/metrics.go
  utils/timer/adaptive_timeout_manager.go
  vms/avm/block/parser.go
  vms/avm/states/state.go
  vms/avm/txs/parser.go
  vms/avm/vm.go
  vms/components/keystore/codec.go
  vms/components/message/codec.go
  vms/example/xsvm/execute/tx.go
  vms/example/xsvm/tx/codec.go
  vms/nftfx/fx.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/codec.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/metrics/metrics.go
  vms/platformvm/service.go
  vms/platformvm/state/state.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/vm.go
  vms/platformvm/warp/codec.go
  vms/platformvm/warp/payload/codec.go
  vms/propertyfx/fx.go
  vms/proposervm/block/codec.go
  vms/secp256k1fx/fx.go
  x/merkledb/metrics.go
  x/sync/metrics.go
  x/sync/peer_tracker.go
Labels: cleanup

#2229 Enable `perfsprint` linter
  .golangci.yml
  api/keystore/service_test.go
  genesis/genesis_test.go
  node/node.go
  tests/fixture/testnet/local/network.go
  utils/crypto/bls/bls_benchmark_test.go
  utils/ips/ip_port.go
  utils/ips/ip_test.go
  utils/sampler/rand_test.go
  utils/set/bits.go
  vms/platformvm/warp/validator_test.go
Labels: ci

#2223 Trim down size of secp256k1 `Factory` struct
  genesis/genesis_local.go
  go.mod
  go.sum
  tests/e2e/c/dynamic_fees.go
  tests/e2e/c/interchain_workflow.go
  tests/e2e/p/interchain_workflow.go
  tests/e2e/p/staking_rewards.go
  tests/e2e/static-handlers/suites.go
  tests/e2e/x/interchain_workflow.go
  tests/fixture/test_data_server_test.go
  tests/fixture/testnet/local/network.go
  utils/crypto/ledger/ledger_test.go
  utils/crypto/secp256k1/rfc6979_test.go
  utils/crypto/secp256k1/secp256k1.go
  utils/crypto/secp256k1/secp256k1_benchmark_test.go
  utils/crypto/secp256k1/secp256k1_test.go
  utils/crypto/secp256k1/test_keys.go
  vms/avm/environment_test.go
  vms/avm/service_test.go
  vms/components/keystore/user.go
  vms/components/keystore/user_test.go
  vms/example/xsvm/tx/tx.go
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/service_test.go
  vms/platformvm/txs/executor/create_chain_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/txs/executor/import_test.go
  vms/platformvm/txs/executor/proposal_tx_executor_test.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
  vms/secp256k1fx/fx.go
  vms/secp256k1fx/keychain.go
  vms/secp256k1fx/keychain_test.go
Labels: cleanup

#2233 Fix test typos
  vms/platformvm/txs/remove_subnet_validator_tx_test.go
  vms/platformvm/txs/transfer_subnet_ownership_tx_test.go
Labels: cleanup

#2111 P2P AppRequestFailed protobuf definition
  proto/p2p/p2p.proto
  proto/pb/p2p/p2p.pb.go
Labels: networking

#2238 Remove error from Router AppGossip
  network/p2p/handler.go
  network/p2p/router.go
Labels: networking, cleanup

#2236 Document host and port behavior in help text
  config/flags.go
Labels: documentation

#2239 Remove `database.Manager`
  api/keystore/keystore.go
  api/keystore/service.go
  api/keystore/service_test.go
  chains/linearizable_vm.go
  chains/manager.go
  database/manager/manager.go
  database/manager/manager_test.go
  database/manager/versioned_database.go
  go.mod
  go.sum
  node/node.go
  proto/pb/vm/vm.pb.go
  proto/vm/vm.proto
  snow/engine/avalanche/vertex/mock_vm.go
  snow/engine/common/test_vm.go
  snow/engine/common/vm.go
  snow/engine/snowman/block/mocks/chain_vm.go
  vms/avm/block/builder/builder_test.go
  vms/avm/environment_test.go
  vms/avm/txs/executor/semantic_verifier_test.go
  vms/avm/vm.go
  vms/avm/vm_test.go
  vms/example/xsvm/vm.go
  vms/metervm/block_vm.go
  vms/metervm/vertex_vm.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/service_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/vm.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
  vms/proposervm/batched_vm_test.go
  vms/proposervm/post_fork_option_test.go
  vms/proposervm/state_syncable_vm_test.go
  vms/proposervm/vm.go
  vms/proposervm/vm_regression_test.go
  vms/proposervm/vm_test.go
  vms/rpcchainvm/batched_vm_test.go
  vms/rpcchainvm/state_syncable_vm_test.go
  vms/rpcchainvm/vm_client.go
  vms/rpcchainvm/vm_server.go
  vms/rpcchainvm/with_context_vm_test.go
  vms/tracedvm/block_vm.go
  vms/tracedvm/vertex_vm.go
Labels: storage, cleanup

#2232 Add `BaseTx` support to platformvm
  vms/platformvm/metrics/tx_metrics.go
  vms/platformvm/txs/base_tx.go
  vms/platformvm/txs/base_tx_test.go
  vms/platformvm/txs/builder/builder.go
  vms/platformvm/txs/builder/mock_builder.go
  vms/platformvm/txs/codec.go
  vms/platformvm/txs/executor/atomic_tx_executor.go
  vms/platformvm/txs/executor/proposal_tx_executor.go
  vms/platformvm/txs/executor/standard_tx_executor.go
  vms/platformvm/txs/executor/tx_mempool_verifier.go
  vms/platformvm/txs/mempool/issuer.go
  vms/platformvm/txs/mempool/remover.go
  vms/platformvm/txs/visitor.go
  vms/platformvm/vm_test.go
  wallet/chain/p/backend_visitor.go
  wallet/chain/p/signer_visitor.go
Labels: enhancement, vm

#2244 Add `pebble` as valid value for `--db-type`.
  config/flags.go
  database/pebble/db.go
  database/pebble/db_test.go
  node/node.go
Labels: storage
