Repository ava-labs/avalanchego, pull requests merged in 2023-12, with the labels that each got.

#2397 P-Chain merkledb -- don't merkleize last accepted block ID
  vms/platformvm/state/state.go
Labels: merkledb

#2403 Add more descriptive formatted error
  chains/atomic/state.go
Labels: monitoring, incident response

#2394 Update versions for v1.10.17
  RELEASES.md
  go.mod
  go.sum
  version/compatibility.json
  version/constants.go
Labels: documentation

#2390 testing: Update to latest version of ginkgo
  go.mod
  go.sum
  scripts/tests.e2e.sh
  scripts/tests.upgrade.sh
Labels: dependencies, testing

#2406 `vms/platformvm`: Cleanup block builder tests
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/block/builder/helpers_test.go
Labels: testing

#2335 Drop Pending Stakers 0 - De-duplicate staking tx verification
  tests/e2e/p/staking_rewards.go
  vms/platformvm/block/builder/builder.go
  vms/platformvm/state/staker_test.go
  vms/platformvm/state/state.go
  vms/platformvm/txs/executor/staker_tx_verification.go
  vms/platformvm/txs/executor/standard_tx_executor.go
  vms/platformvm/txs/executor/tx_mempool_verifier.go
Labels: cleanup

#2419 `vms/platformvm`: Initialize txs in `Transactions` field for `BanffProposalBlock`
  vms/platformvm/block/proposal_block.go
  vms/platformvm/block/standard_block.go
Labels: cleanup

#2410 `vms/platformvm`: Move `VerifyUniqueInputs` from `verifier` to `backend`
  vms/avm/block/executor/manager.go
  vms/platformvm/block/executor/backend.go
  vms/platformvm/block/executor/verifier.go
Labels: cleanup

#2334 Fix duplicated bootstrapper engine termination
  snow/engine/snowman/bootstrap/bootstrapper.go
  snow/engine/snowman/bootstrap/bootstrapper_test.go
Labels: bug, consensus

#2414 allow user of `build_fuzz.sh` to specify a directory to fuzz in
  scripts/build_fuzz.sh
Labels: testing

#2424 Update slices dependency to use Compare
  api/metrics/multi_gatherer.go
  chains/atomic/state.go
  codec/reflectcodec/type_codec.go
  genesis/config.go
  genesis/config_test.go
  go.mod
  go.sum
  ids/id.go
  ids/id_test.go
  ids/node_id.go
  ids/node_id_test.go
  ids/short.go
  snow/consensus/snowman/test_block.go
  utils/sampler/weighted_array.go
  utils/sampler/weighted_array_test.go
  utils/sampler/weighted_heap.go
  utils/sampler/weighted_heap_test.go
  utils/sampler/weighted_linear.go
  utils/sampler/weighted_linear_test.go
  utils/set/sampleable_set.go
  utils/set/set.go
  utils/sorting.go
  utils/sorting_test.go
  vms/avm/genesis.go
  vms/avm/genesis_test.go
  vms/avm/txs/initial_state.go
  vms/avm/txs/initial_state_test.go
  vms/avm/txs/operation.go
  vms/components/avax/transferables.go
  vms/components/avax/utxo_id.go
  vms/components/avax/utxo_id_test.go
  vms/platformvm/api/static_service.go
  vms/platformvm/api/static_service_test.go
  vms/platformvm/warp/signature_test.go
  vms/platformvm/warp/validator.go
  vms/proposervm/proposer/validators.go
  vms/proposervm/proposer/validators_test.go
  x/archivedb/key_test.go
  x/merkledb/key.go
  x/merkledb/view_iterator.go
  x/sync/sync_test.go
  x/sync/workheap_test.go
Labels: dependencies, cleanup

#2398 P-Chain merkledb -- include txs in merkleized state
  vms/platformvm/state/state.go
  vms/platformvm/state/state_helpers.go
  vms/platformvm/state/state_helpers_test.go
Labels: merkledb

#2422 `vms/platformvm`: Cleanup some block tests
  vms/platformvm/block/parse_test.go
  vms/platformvm/block/proposal_block_test.go
Labels: testing, cleanup

#2404 ProposerVM Extend windows 0 - Cleanup
  chains/manager.go
  vms/proposervm/batched_vm_test.go
  vms/proposervm/block.go
  vms/proposervm/block_test.go
  vms/proposervm/config.go
  vms/proposervm/height_indexed_vm.go
  vms/proposervm/post_fork_block_test.go
  vms/proposervm/post_fork_option_test.go
  vms/proposervm/pre_fork_block.go
  vms/proposervm/pre_fork_block_test.go
  vms/proposervm/state_syncable_vm_test.go
  vms/proposervm/vm.go
  vms/proposervm/vm_regression_test.go
  vms/proposervm/vm_test.go
Labels: cleanup

#2427 Update minimum golang version to v1.20.12
  .github/workflows/auto-generated-checker.yml
  .github/workflows/build-linux-binaries.yml
  .github/workflows/build-macos-release.yml
  .github/workflows/build-public-ami.yml
  .github/workflows/build-ubuntu-amd64-release.yml
  .github/workflows/build-ubuntu-arm64-release.yml
  .github/workflows/build-win-release.yml
  .github/workflows/fuzz.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test.e2e.existing.yml
  .github/workflows/test.e2e.yml
  .github/workflows/test.unit.yml
  .github/workflows/test.upgrade.yml
  CONTRIBUTING.md
  Dockerfile
  README.md
  proto/Dockerfile.buf
  scripts/build_avalanche.sh
Labels: dependencies

#2429 Fix platformvm.SetPreference
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/block/executor/manager.go
  vms/platformvm/block/executor/manager_test.go
Labels: bug, vm

#2434 Restrict GOPROXY
  scripts/constants.sh
Labels: ci

#2433 Make `messageQueue.msgAndCtxs` a circular buffer
  snow/networking/handler/message_queue.go
Labels: cleanup

#2412 ProposerVM Extend windows 1 - UTs Cleanup
  vms/proposervm/batched_vm_test.go
  vms/proposervm/block_test.go
  vms/proposervm/post_fork_block_test.go
  vms/proposervm/post_fork_option_test.go
  vms/proposervm/pre_fork_block_test.go
  vms/proposervm/proposer/windower_test.go
  vms/proposervm/state_syncable_vm_test.go
  vms/proposervm/vm_byzantine_test.go
  vms/proposervm/vm_test.go
Labels: testing, cleanup

#2438 Change seed from int64 to uint64
  snow/consensus/snowball/consensus_performance_test.go
  snow/consensus/snowball/consensus_reversibility_test.go
  snow/consensus/snowball/tree_test.go
  snow/consensus/snowman/consensus_test.go
  utils/sampler/rand.go
  utils/sampler/uniform.go
  utils/sampler/uniform_replacer.go
  utils/sampler/uniform_resample.go
  utils/sampler/weighted_without_replacement.go
  utils/sampler/weighted_without_replacement_generic.go
  vms/proposervm/proposer/windower.go
Labels: cleanup

#2441 Remove usage of timer.Timer in node
  node/beacon_manager.go
  node/beacon_manager_test.go
  node/node.go
Labels: cleanup

#2440 Remove staged timer again
  utils/timer/staged_timer.go
  utils/timer/staged_timer_test.go
Labels: cleanup

#2437 `merkledb` / `sync` -- Disambiguate no end root from no start root
  x/merkledb/db.go
  x/merkledb/history.go
  x/merkledb/history_test.go
  x/merkledb/proof_test.go
  x/sync/g_db/db_client.go
  x/sync/network_server.go
  x/sync/network_server_test.go
Labels: merkledb

#2447 Remove usage of timer.Timer in block building
  vms/platformvm/block/builder/builder.go
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/builder/standard_block_test.go
  vms/platformvm/vm.go
Labels: cleanup

#2380 `vms/platformvm`: Remove double block building logic
  vms/platformvm/block/builder/builder.go
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/builder/standard_block_test.go
  vms/platformvm/block/executor/rejector.go
  vms/platformvm/network/network.go
  vms/platformvm/vm.go
Labels: cleanup

#2446 Remove usage of timer.Timer in benchlist
  snow/networking/benchlist/benchlist.go
  snow/networking/benchlist/benchlist_test.go
Labels: cleanup

#2450 `vms/platformvm`: Remove `standardBlockState` struct
  vms/platformvm/block/executor/acceptor_test.go
  vms/platformvm/block/executor/block_state.go
  vms/platformvm/block/executor/verifier.go
  vms/platformvm/block/executor/verifier_test.go
Labels: cleanup

#2456 Refactor sampler seeding
  snow/consensus/snowball/consensus_performance_test.go
  snow/consensus/snowball/consensus_reversibility_test.go
  snow/consensus/snowball/network_test.go
  snow/consensus/snowball/tree_test.go
  snow/consensus/snowman/consensus_test.go
  snow/consensus/snowman/network_test.go
  utils/sampler/rand.go
  utils/sampler/uniform.go
  utils/sampler/uniform_best.go
  utils/sampler/uniform_replacer.go
  utils/sampler/uniform_resample.go
  utils/sampler/uniform_test.go
  utils/sampler/weighted_without_replacement.go
  utils/sampler/weighted_without_replacement_generic.go
  utils/sampler/weighted_without_replacement_test.go
  vms/proposervm/proposer/windower.go
Labels: cleanup

#2391 Update tmpnet fixture to include Proof-of-Possession for initial stakers
  tests/fixture/tmpnet/config.go
  tests/fixture/tmpnet/local/network.go
Labels: testing

#2463 `vms/platformvm`: Remove `EnableAdding` and `DisableAdding` from `Mempool` interface
  vms/platformvm/block/builder/builder.go
  vms/platformvm/txs/mempool/mempool.go
  vms/platformvm/txs/mempool/mock_mempool.go
Labels: cleanup

#2465 `vms/avm`: Add `exists` bool to mempool `Peek`
  vms/avm/block/builder/builder.go
  vms/avm/block/builder/builder_test.go
  vms/avm/txs/mempool/mempool.go
  vms/avm/txs/mempool/mempool_test.go
  vms/avm/txs/mempool/mock_mempool.go
Labels: cleanup

#2461 `vms/platformvm`: Add `processStandardTxs` helper
  vms/platformvm/block/executor/verifier.go
Labels: cleanup

#2455 `e2e`: Rename 'funded key' to 'pre-funded key' for consistency
  tests/e2e/c/dynamic_fees.go
  tests/e2e/c/interchain_workflow.go
  tests/e2e/p/staking_rewards.go
  tests/e2e/x/transfer/virtuous.go
  tests/fixture/e2e/env.go
  tests/fixture/e2e/helpers.go
  tests/fixture/test_data_server.go
  tests/fixture/test_data_server_test.go
  tests/fixture/tmpnet/cmd/main.go
  tests/fixture/tmpnet/config.go
  tests/fixture/tmpnet/local/network.go
  tests/fixture/tmpnet/local/network_test.go
Labels: testing

#2466 `vms/platformvm`: Add `TestBuildBlockShouldReward` test
  vms/platformvm/block/builder/builder_test.go
Labels: testing, cleanup

#2188 Switch client version to a proto type from a string
  message/mock_outbound_message_builder.go
  message/outbound_msg_builder.go
  network/peer/peer.go
  proto/p2p/p2p.proto
  proto/pb/p2p/p2p.pb.go
  proto/pb/vm/vm.pb.go
  proto/vm/vm.proto
  version/application.go
  version/application_test.go
  version/compatibility_test.go
  version/constants.go
  version/parser.go
  version/parser_test.go
  version/version.go
  vms/rpcchainvm/vm_client.go
  vms/rpcchainvm/vm_server.go
Labels: networking

#2473 Apply state modifications once
  vms/platformvm/block/executor/acceptor.go
  vms/platformvm/block/executor/backend.go
  vms/platformvm/block/executor/block_state.go
  vms/platformvm/block/executor/verifier.go
  vms/platformvm/block/executor/verifier_test.go
Labels: cleanup, Durango

#2469 `vms/platformvm`: Add `TestBuildBlockDoesNotBuildWithEmptyMempool` test
  vms/platformvm/block/builder/builder_test.go
Labels: testing, cleanup

#2471 `vms/platformvm`: Add `TestBuildBlockShouldAdvanceTime` test
  vms/platformvm/block/builder/builder_test.go
Labels: testing, cleanup

#2472 `vms/platformvm`: Add `TestBuildBlockForceAdvanceTime` test
  vms/platformvm/block/builder/builder_test.go
Labels: testing, cleanup

#2248 P2P AppError handling
  go.mod
  go.sum
  message/inbound_msg_builder.go
  message/inbound_msg_builder_test.go
  message/internal_msg_builder.go
  message/ops.go
  network/p2p/client.go
  network/p2p/network.go
  network/p2p/network_test.go
  network/p2p/router.go
  proto/pb/vm/vm.pb.go
  proto/vm/vm.proto
  snow/engine/avalanche/vertex/mock_vm.go
  snow/engine/common/engine.go
  snow/engine/common/error.go
  snow/engine/common/error_test.go
  snow/engine/common/no_ops_handlers.go
  snow/engine/common/test_engine.go
  snow/engine/common/test_vm.go
  snow/engine/common/traced_engine.go
  snow/engine/snowman/block/mocks/chain_vm.go
  snow/networking/handler/handler.go
  snow/networking/router/chain_router_test.go
  snow/networking/sender/sender.go
  snow/networking/sender/sender_test.go
  vms/avm/network/atomic.go
  vms/rpcchainvm/vm_client.go
  vms/rpcchainvm/vm_server.go
Labels: networking

#2359 `vms/platformvm`: Verify txs before building a block
  vms/platformvm/block/builder/builder.go
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/block/executor/verifier.go
  vms/platformvm/txs/mempool/mempool.go
  vms/platformvm/txs/mempool/mempool_test.go
  vms/platformvm/txs/mempool/mock_mempool.go
Labels: cleanup

#2475 Refactor p2p unit tests
  go.mod
  go.sum
  network/p2p/gossip/gossip.go
  network/p2p/gossip/gossip_test.go
  network/p2p/mocks/mock_handler.go
  network/p2p/network_test.go
  network/p2p/validators_test.go
  scripts/mocks.mockgen.txt
  snow/engine/common/test_sender.go
Labels: networking

#2476 Add ACP signaling
  api/info/service.go
  config/config.go
  config/flags.go
  config/keys.go
  message/mock_outbound_message_builder.go
  message/outbound_msg_builder.go
  network/config.go
  network/network.go
  network/peer/config.go
  network/peer/info.go
  network/peer/peer.go
  node/node.go
  proto/p2p/p2p.proto
  proto/pb/p2p/p2p.pb.go
  utils/constants/acps.go
Labels: networking

#2452 Refactor SDK
  go.mod
  go.sum
  network/p2p/client.go
  network/p2p/gossip/gossip_test.go
  network/p2p/handler.go
  network/p2p/handler_test.go
  network/p2p/network.go
  network/p2p/network_test.go
  network/p2p/router.go
  network/p2p/throttler_handler.go
  network/p2p/throttler_handler_test.go
  network/p2p/validators_test.go
Labels: cleanup

#2480 Cleanup CI
  .github/workflows/auto-generated-checker.yml
  .github/workflows/buf-lint.yml
  .github/workflows/build-linux-binaries.yml
  .github/workflows/build-ubuntu-amd64-release.yml
  .github/workflows/build-ubuntu-arm64-release.yml
  .github/workflows/ci.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test.e2e.existing.yml
  .github/workflows/test.e2e.yml
  .github/workflows/test.unit.yml
  .github/workflows/test.upgrade.yml
Labels: testing, ci, cleanup

#2478 Ensure upgrade test uses the correct binary on restart
  .github/workflows/ci.yml
  scripts/tests.upgrade.sh
  tests/upgrade/upgrade_test.go
Labels: testing

#2435 Prefetch Improvement
  x/merkledb/db.go
Labels: merkledb

#2483 ci: run each fuzz test for 10 seconds
  .github/workflows/ci.yml
Labels: testing, ci

#2481 Remove nullable options
  codec/reflectcodec/struct_fielder.go
  codec/reflectcodec/type_codec.go
  codec/reflectcodec/type_codec_test.go
  codec/test_codec.go
Labels: cleanup

#2177 `merkledb` -- dynamic root
  scripts/mocks.mockgen.txt
  x/merkledb/codec.go
  x/merkledb/codec_test.go
  x/merkledb/db.go
  x/merkledb/db_test.go
  x/merkledb/history.go
  x/merkledb/history_test.go
  x/merkledb/metrics_test.go
  x/merkledb/mock_db.go
  x/merkledb/node.go
  x/merkledb/proof.go
  x/merkledb/proof_test.go
  x/merkledb/trie.go
  x/merkledb/trie_test.go
  x/merkledb/trieview.go
  x/sync/client_test.go
  x/sync/g_db/db_client.go
  x/sync/manager.go
  x/sync/network_server.go
  x/sync/network_server_test.go
  x/sync/sync_test.go
Labels: merkledb

#2484 fix onEvictCache
  x/merkledb/cache.go
  x/merkledb/db.go
  x/merkledb/intermediate_node_db_test.go
  x/merkledb/value_node_db_test.go
Labels: bug, storage, merkledb

#2423 MerkleDB -- update readme
  x/merkledb/README.md
Labels: documentation, merkledb

#2306 Drop Pending Stakers 3 - persist stakers' StartTime
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/state/metadata_codec.go
  vms/platformvm/state/metadata_delegator.go
  vms/platformvm/state/metadata_delegator_test.go
  vms/platformvm/state/metadata_validator.go
  vms/platformvm/state/metadata_validator_test.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/validators/manager_benchmark_test.go
  vms/platformvm/vm.go
  vms/platformvm/vm_regression_test.go
Labels: Durango

#2428 SDK Push Gossiper implementation
  go.mod
  go.sum
  network/p2p/gossip/gossip.go
  network/p2p/gossip/gossip_test.go
  network/p2p/gossip/gossipable.go
  network/p2p/gossip/handler.go
  network/p2p/gossip/test_gossip.go
  network/p2p/network_test.go
  proto/pb/sdk/sdk.pb.go
  proto/sdk/sdk.proto
Labels: networking

#2457 `tmpnet`: Move tmpnet/local to tmpnet package
  scripts/tests.upgrade.sh
  tests/e2e/c/dynamic_fees.go
  tests/e2e/faultinjection/duplicate_node_id.go
  tests/e2e/p/interchain_workflow.go
  tests/e2e/p/staking_rewards.go
  tests/fixture/e2e/env.go
  tests/fixture/e2e/flags.go
  tests/fixture/e2e/helpers.go
  tests/fixture/tmpnet/README.md
  tests/fixture/tmpnet/cmd/main.go
  tests/fixture/tmpnet/config.go
  tests/fixture/tmpnet/defaults.go
  tests/fixture/tmpnet/interfaces.go
  tests/fixture/tmpnet/local/README.md
  tests/fixture/tmpnet/network.go
  tests/fixture/tmpnet/network_test.go
  tests/fixture/tmpnet/node.go
  tests/fixture/tmpnet/node_test.go
  tests/fixture/tmpnet/utils.go
  tests/upgrade/upgrade_test.go
Labels: testing

#2470 `merkledb` -- make tests use time as randomness seed
  x/sync/client.go
  x/sync/client_test.go
Labels: testing, merkledb

#2462 `tmpnet`: Break config.go up into coherent parts
  tests/fixture/e2e/env.go
  tests/fixture/tmpnet/README.md
  tests/fixture/tmpnet/config.go
  tests/fixture/tmpnet/defaults.go
  tests/fixture/tmpnet/flags.go
  tests/fixture/tmpnet/genesis.go
  tests/fixture/tmpnet/network.go
  tests/fixture/tmpnet/node.go
  tests/fixture/tmpnet/node_test.go
  tests/fixture/tmpnet/utils.go
Labels: testing

#2332 Drop Pending Stakers 4 - minimal UT infra cleanup
  vms/platformvm/service_test.go
  vms/platformvm/txs/executor/advance_time_test.go
  vms/platformvm/txs/executor/create_chain_test.go
  vms/platformvm/txs/executor/create_subnet_test.go
  vms/platformvm/txs/executor/export_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/txs/executor/import_test.go
  vms/platformvm/txs/executor/proposal_tx_executor_test.go
  vms/platformvm/txs/executor/reward_validator_test.go
  vms/platformvm/txs/executor/staker_tx_verification_test.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/txs/validator_test.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
Labels: Durango

#2401 ProposerVM Extend windows 2- extend windowing
  chains/manager.go
  scripts/mocks.mockgen.txt
  snow/validators/test_state.go
  utils/sampler/rand_test.go
  vms/proposervm/batched_vm_test.go
  vms/proposervm/block.go
  vms/proposervm/block_test.go
  vms/proposervm/config.go
  vms/proposervm/post_fork_block_test.go
  vms/proposervm/post_fork_option_test.go
  vms/proposervm/pre_fork_block_test.go
  vms/proposervm/proposer/mock_windower.go
  vms/proposervm/proposer/windower.go
  vms/proposervm/proposer/windower_test.go
  vms/proposervm/scheduler/mock_scheduler.go
  vms/proposervm/state_syncable_vm_test.go
  vms/proposervm/vm.go
  vms/proposervm/vm_byzantine_test.go
  vms/proposervm/vm_regression_test.go
  vms/proposervm/vm_test.go
Labels: Durango

#2494 Support json marshalling txs returned from the wallet
  wallet/chain/c/builder.go
  wallet/chain/c/context.go
  wallet/chain/p/builder.go
  wallet/chain/p/context.go
  wallet/chain/x/builder.go
  wallet/chain/x/context.go
  wallet/chain/x/signer_visitor.go
Labels: enhancement

#2496 Avoid escaping to improve readability
  api/auth/auth.go
  ids/id.go
  ids/id_test.go
  ids/node_id.go
  ids/node_id_test.go
  ids/short.go
  node/overridden_manager_test.go
  snow/choices/status.go
  snow/consensus/snowball/parameters.go
  snow/consensus/snowball/tree_test.go
  snow/validators/manager_test.go
  snow/validators/set_test.go
  tests/fixture/tmpnet/cmd/main.go
  utils/bag/bag_test.go
  utils/crypto/secp256k1/secp256k1.go
  utils/formatting/encoding.go
  utils/json/float32.go
  utils/json/float64.go
  utils/json/uint16.go
  utils/json/uint32.go
  utils/json/uint64.go
  utils/json/uint8.go
  utils/logging/sanitize.go
Labels: cleanup

#2495 Allow OutputOwners to be json marshalled without InitCtx
  vms/secp256k1fx/output_owners.go
  vms/secp256k1fx/output_owners_test.go
Labels: enhancement

#2499 Combine implementations
  tests/e2e/p/interchain_workflow.go
  tests/e2e/p/permissionless_subnets.go
  tests/e2e/p/staking_rewards.go
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/txs/executor/standard_tx_executor.go
  vms/platformvm/vm_test.go
Labels: cleanup

#2314 Drop Pending Stakers 5 - validated PostDurango StakerTxs
  tests/e2e/p/interchain_workflow.go
  tests/e2e/p/permissionless_subnets.go
  tests/e2e/p/staking_rewards.go
  tests/e2e/p/workflow.go
  tests/fixture/e2e/helpers.go
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/state/state.go
  vms/platformvm/txs/executor/advance_time_test.go
  vms/platformvm/txs/executor/create_chain_test.go
  vms/platformvm/txs/executor/create_subnet_test.go
  vms/platformvm/txs/executor/export_test.go
  vms/platformvm/txs/executor/proposal_tx_executor_test.go
  vms/platformvm/txs/executor/reward_validator_test.go
  vms/platformvm/txs/executor/staker_tx_verification.go
  vms/platformvm/txs/executor/staker_tx_verification_helpers.go
  vms/platformvm/txs/executor/staker_tx_verification_test.go
  vms/platformvm/txs/executor/standard_tx_executor.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/txs/validator.go
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
Labels: Durango

#2503 Remove unused `BuildGenesisTest` function
  vms/platformvm/vm_test.go
Labels: cleanup

#2508 Remove unused `AcceptorTracker` struct
  snow/acceptor.go
Labels: cleanup

#2511 Dedupe secp256k1 key usage in tests
  tests/e2e/static-handlers/suites.go
  vms/avm/environment_test.go
Labels: testing, cleanup

#2514 Gossip Test structs
  network/p2p/gossip/gossip.go
  network/p2p/gossip/gossip_test.go
  network/p2p/handler.go
  network/p2p/handler_test.go
  network/p2p/network_test.go
  network/p2p/throttler_handler_test.go
Labels: networking

#2460 `tmpnet`: Separate node into orchestration, config and process
  tests/e2e/faultinjection/duplicate_node_id.go
  tests/e2e/p/interchain_workflow.go
  tests/e2e/p/staking_rewards.go
  tests/fixture/e2e/env.go
  tests/fixture/e2e/helpers.go
  tests/fixture/tmpnet/README.md
  tests/fixture/tmpnet/cmd/main.go
  tests/fixture/tmpnet/defaults.go
  tests/fixture/tmpnet/network.go
  tests/fixture/tmpnet/network_test.go
  tests/fixture/tmpnet/node.go
  tests/fixture/tmpnet/node_config.go
  tests/fixture/tmpnet/node_process.go
  tests/fixture/tmpnet/utils.go
  tests/upgrade/upgrade_test.go
Labels: testing

#2507 Move `snow.DefaultConsensusContextTest` to `snowtest.ConsensusContext`
  indexer/index_test.go
  indexer/indexer_test.go
  network/test_network.go
  snow/acceptor.go
  snow/consensus/snowman/consensus_test.go
  snow/consensus/snowman/network_test.go
  snow/context.go
  snow/engine/avalanche/bootstrap/bootstrapper_test.go
  snow/engine/common/queue/jobs_test.go
  snow/engine/snowman/bootstrap/bootstrapper_test.go
  snow/engine/snowman/config_test.go
  snow/engine/snowman/syncer/state_syncer_test.go
  snow/networking/benchlist/benchlist_test.go
  snow/networking/handler/handler_test.go
  snow/networking/handler/health_test.go
  snow/networking/handler/message_queue_test.go
  snow/networking/router/chain_router_test.go
  snow/networking/sender/sender_test.go
  snow/snowtest/snowtest.go
  vms/platformvm/vm_test.go
Labels: testing, cleanup

#2509 Add gossip Marshaller interface
  go.mod
  go.sum
  network/p2p/gossip/bloom.go
  network/p2p/gossip/gossip.go
  network/p2p/gossip/gossip_test.go
  network/p2p/gossip/gossipable.go
  network/p2p/gossip/handler.go
  network/p2p/gossip/test_gossip.go
Labels: networking

#2519 Include chain creation error in health check
  chains/manager.go
Labels: monitoring

#2520 Make X-chain mempool safe for concurrent use
  vms/avm/block/builder/builder_test.go
  vms/avm/network/network.go
  vms/avm/network/network_test.go
  vms/avm/txs/mempool/mempool.go
  vms/avm/txs/mempool/mempool_test.go
  vms/avm/txs/mempool/mock_mempool.go
Labels: enhancement, vm, Durango

#2521 Initialize transactions once
  genesis/genesis.go
  vms/avm/block/parser.go
  vms/avm/block/standard_block.go
  vms/avm/environment_test.go
  vms/avm/network/network_test.go
  vms/avm/service_test.go
  vms/avm/state/state_test.go
  vms/avm/txs/base_tx_test.go
  vms/avm/txs/create_asset_tx_test.go
  vms/avm/txs/export_tx_test.go
  vms/avm/txs/import_tx_test.go
  vms/avm/txs/parser.go
  vms/avm/vm.go
  vms/avm/vm_regression_test.go
  vms/avm/vm_test.go
Labels: vm, cleanup, Durango

#2517 `vms/avm`: Remove usage of `require.Contains` from service tests
  vms/avm/service_test.go
Labels: testing, cleanup

#2524 Move context lock into issueTx
  vms/avm/environment_test.go
  vms/avm/service.go
  vms/avm/service_test.go
  vms/avm/vm.go
  vms/avm/wallet_service.go
Labels: vm

#2526 Rework X-chain locking in tests
  vms/avm/environment_test.go
  vms/avm/index_test.go
  vms/avm/service_test.go
  vms/avm/vm_regression_test.go
  vms/avm/vm_test.go
  vms/avm/wallet_service_test.go
Labels: testing, cleanup

#2527 `vms/avm`: Simplify `mempool.Remove` signature
  vms/avm/block/builder/builder.go
  vms/avm/block/executor/block.go
  vms/avm/txs/mempool/mempool.go
  vms/avm/txs/mempool/mempool_test.go
  vms/avm/txs/mempool/mock_mempool.go
Labels: cleanup

#2528 Remove unused mocks
  network/peer/mock_gossip_tracker.go
  scripts/mocks.mockgen.txt
  vms/platformvm/txs/builder/mock_builder.go
Labels: cleanup

#2513 Move `avm.newContext` to `snowtest.Context`
  snow/snowtest/snowtest.go
  vms/avm/environment_test.go
  vms/avm/index_test.go
  vms/avm/service_test.go
  vms/avm/state_test.go
  vms/avm/txs/executor/semantic_verifier_test.go
  vms/avm/txs/executor/syntactic_verifier_test.go
  vms/avm/vm_benchmark_test.go
  vms/avm/vm_regression_test.go
  vms/avm/vm_test.go
Labels: testing, cleanup

#2530 Do not fail-fast Tests / Unit
  .github/workflows/ci.yml
Labels: ci

#2523 Make P-Chain Mempool thread-safe
  vms/platformvm/block/builder/builder.go
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/block/executor/verifier.go
  vms/platformvm/network/network.go
  vms/platformvm/network/network_test.go
  vms/platformvm/service.go
  vms/platformvm/txs/mempool/mempool.go
  vms/platformvm/txs/mempool/mempool_test.go
  vms/platformvm/txs/mempool/mock_mempool.go
Labels: vm

#2515 `vms/platformvm`: Use `snowtest.Context` helper
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/builder/standard_block_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/service_test.go
  vms/platformvm/txs/add_delegator_test.go
  vms/platformvm/txs/add_validator_test.go
  vms/platformvm/txs/executor/export_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/txs/executor/import_test.go
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
Labels: testing, cleanup

#2532 Move locking into issueTx
  vms/avm/network/network.go
  vms/avm/network/network_test.go
  vms/avm/vm.go
  vms/avm/wallet_service.go
Labels: vm

#2534 Fix merge in wallet service
  vms/avm/wallet_service.go
Labels: bug, cleanup

#2533 Introduce TxVerifier interface to network
  vms/avm/network/network.go
  vms/avm/network/network_test.go
  vms/avm/network/tx_verifier.go
  vms/avm/vm.go
Labels: cleanup

#2479 Rename `Version` message to `Handshake`
  message/messages_benchmark_test.go
  message/messages_test.go
  message/mock_outbound_message_builder.go
  message/ops.go
  message/outbound_msg_builder.go
  network/README.md
  network/peer/config.go
  network/peer/peer.go
  proto/p2p/p2p.proto
  proto/pb/p2p/p2p.pb.go
Labels: cleanup

#2537 Rename myVersionTime to ipSigningTime
  message/messages_benchmark_test.go
  message/messages_test.go
  message/outbound_msg_builder.go
  network/peer/peer.go
  proto/p2p/p2p.proto
  proto/pb/p2p/p2p.pb.go
Labels: networking, cleanup

#2540 Remove resolved TODO
  vms/platformvm/block/proposal_block.go
Labels: cleanup

#2538 Only initialize Txs once
  vms/platformvm/block/abort_block.go
  vms/platformvm/block/atomic_block.go
  vms/platformvm/block/block.go
  vms/platformvm/block/commit_block.go
  vms/platformvm/block/proposal_block.go
  vms/platformvm/block/serialization_test.go
  vms/platformvm/block/standard_block.go
  vms/platformvm/state/state_test.go
  vms/platformvm/vm_test.go
Labels: cleanup

#2541 JSON marshal the `Transactions` field in `BanffProposalBlocks`
  vms/platformvm/block/proposal_block.go
  vms/platformvm/block/serialization_test.go
Labels: cleanup

#2539 Enable `predeclared` linter
  .golangci.yml
  message/inbound_msg_builder.go
  snow/validators/manager_test.go
  snow/validators/set_test.go
  utils/profiler/continuous.go
  utils/profiler/profiler.go
Labels: cleanup

#2525 Move context lock into `network.issueTx`
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/network/network.go
  vms/platformvm/service.go
  vms/platformvm/service_test.go
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/vm.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
Labels: networking

#2544 Remove comment on treating failed sends as FATAL
  snow/engine/common/sender.go
Labels: documentation

#2542 Add TxVerifier interface to network
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/network/network.go
  vms/platformvm/network/network_test.go
  vms/platformvm/network/tx_verifier.go
  vms/platformvm/vm.go
Labels: cleanup

#2490 X-chain SDK gossip
  vms/avm/config.go
  vms/avm/config_test.go
  vms/avm/environment_test.go
  vms/avm/network/config.go
  vms/avm/network/gossip.go
  vms/avm/network/gossip_test.go
  vms/avm/network/network.go
  vms/avm/network/network_test.go
  vms/avm/txs/tx.go
  vms/avm/vm.go
  vms/avm/vm_test.go
Labels: Durango

#2543 Remove network context
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/network/network.go
  vms/platformvm/network/network_test.go
  vms/platformvm/vm.go
Labels: cleanup

#2545 Add a `snow.Context` param to `snowtest.ConsensusContext`
  api/server/server_test.go
  indexer/index_test.go
  indexer/indexer_test.go
  network/test_network.go
  snow/consensus/snowman/consensus_test.go
  snow/consensus/snowman/network_test.go
  snow/engine/avalanche/bootstrap/bootstrapper_test.go
  snow/engine/common/queue/jobs_test.go
  snow/engine/snowman/bootstrap/bootstrapper_test.go
  snow/engine/snowman/config_test.go
  snow/engine/snowman/syncer/state_syncer_test.go
  snow/engine/snowman/transitive_test.go
  snow/networking/benchlist/benchlist_test.go
  snow/networking/handler/handler_test.go
  snow/networking/handler/health_test.go
  snow/networking/handler/message_queue_test.go
  snow/networking/router/chain_router_test.go
  snow/networking/sender/sender_test.go
  snow/snowtest/snowtest.go
  vms/platformvm/vm_test.go
Labels: testing, cleanup

#2518 Remove `snow.DefaultContextTest`
  api/server/server_test.go
  go.mod
  go.sum
  indexer/index_test.go
  indexer/indexer_test.go
  network/test_network.go
  snow/consensus/snowman/consensus_test.go
  snow/consensus/snowman/network_test.go
  snow/context.go
  snow/engine/avalanche/bootstrap/bootstrapper_test.go
  snow/engine/avalanche/state/unique_vertex_test.go
  snow/engine/common/queue/jobs_test.go
  snow/engine/snowman/bootstrap/bootstrapper_test.go
  snow/engine/snowman/config_test.go
  snow/engine/snowman/syncer/state_syncer_test.go
  snow/engine/snowman/transitive_test.go
  snow/networking/benchlist/benchlist_test.go
  snow/networking/handler/handler_test.go
  snow/networking/handler/health_test.go
  snow/networking/handler/message_queue_test.go
  snow/networking/router/chain_router_test.go
  snow/networking/sender/sender_test.go
  snow/snowtest/snowtest.go
  vms/platformvm/txs/add_subnet_validator_test.go
  vms/platformvm/txs/create_chain_test.go
  vms/platformvm/txs/executor/staker_tx_verification_test.go
  vms/platformvm/utxo/handler_test.go
  vms/platformvm/vm_test.go
  vms/proposervm/batched_vm_test.go
  vms/proposervm/state_syncable_vm_test.go
  vms/proposervm/vm_regression_test.go
  vms/proposervm/vm_test.go
  vms/rpcchainvm/batched_vm_test.go
  vms/rpcchainvm/state_syncable_vm_test.go
  vms/rpcchainvm/with_context_vm_test.go
Labels: testing, cleanup

#2529 Fix windowing when no validator is available
  vms/proposervm/block.go
  vms/proposervm/proposer/windower.go
  vms/proposervm/proposer/windower_test.go
  vms/proposervm/vm.go
Labels: bug

#2547 Unexport fields from gossip.BloomFilter
  go.mod
  go.sum
  network/p2p/gossip/bloom.go
  network/p2p/gossip/bloom_test.go
  network/p2p/gossip/handler.go
  network/p2p/gossip/test_gossip.go
  vms/avm/network/gossip.go
Labels: bug, vm, networking

#2487 P-Chain SDK Gossip
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/config/execution_config.go
  vms/platformvm/config/execution_config_test.go
  vms/platformvm/network/config.go
  vms/platformvm/network/gossip.go
  vms/platformvm/network/gossip_test.go
  vms/platformvm/network/network.go
  vms/platformvm/network/network_test.go
  vms/platformvm/service_test.go
  vms/platformvm/txs/tx.go
  vms/platformvm/vm.go
Labels: networking, Durango

#2549 Notify block builder of txs after reject
  vms/avm/block/executor/block.go
  vms/avm/block/executor/block_test.go
Labels: bug, vm

#2553 Set dependabot target branch to `dev`
  .github/dependabot.yml
Labels: ci

#2554 Remove `MockLogger`
  api/admin/service_test.go
  api/info/service_test.go
  scripts/mocks.mockgen.txt
  utils/logging/mock_logger.go
  vms/registry/vm_registerer_test.go
Labels: cleanup

#2557 Do not mark txs as dropped when mempool is full
  vms/avm/txs/mempool/mempool.go
  vms/avm/txs/mempool/mempool_test.go
  vms/platformvm/txs/mempool/mempool.go
  vms/platformvm/txs/mempool/mempool_test.go
Labels: bug

#2558 Update bug bounty program to immunefi
  SECURITY.md
Labels: documentation

#2561 Fix p2p sdk metric labels
  network/p2p/gossip/gossip.go
  network/p2p/gossip/handler.go
Labels: bug, monitoring, networking

#2562 Suppress gossip warnings due to no sampled peers
  network/p2p/gossip/gossip.go
  network/p2p/validators.go
Labels: bug, monitoring, networking

#2560 Remove dead code and unnecessary lock from reflect codec
  codec/reflectcodec/struct_fielder.go
Labels: cleanup

#2564 Remove unused index interface
  indexer/index.go
  indexer/index_test.go
  indexer/indexer.go
  indexer/service.go
Labels: cleanup

#2555 Implement SetMap and use it in XP-chain mempools
  utils/setmap/setmap.go
  utils/setmap/setmap_test.go
  vms/avm/txs/mempool/mempool.go
  vms/avm/txs/mempool/mempool_test.go
  vms/platformvm/txs/mempool/mempool.go
  vms/platformvm/txs/mempool/mempool_test.go
Labels: vm

#2565 `vms/platformvm`: Add `TestIterate`
  vms/platformvm/txs/mempool/mempool_test.go
Labels: testing

#2559 Remove `len` tag parsing from the reflect codec
  codec/reflectcodec/struct_fielder.go
  codec/reflectcodec/type_codec.go
  codec/test_codec.go
  snow/engine/avalanche/vertex/stateless_vertex.go
Labels: cleanup

#2567 Use more specific type
  network/network.go
Labels: cleanup

#2568 Standardize `onShutdownCtx`
  vms/avm/vm.go
  vms/platformvm/vm.go
Labels: cleanup

#2569 Verify avm mempool txs against the last accepted state
  vms/avm/block/executor/block_test.go
  vms/avm/block/executor/manager.go
  vms/avm/block/executor/manager_test.go
Labels: vm
