Repository ava-labs/avalanchego, pull requests merged in 2024-09, with the labels that each got.

#3293 Remove local chain config from e2e test
  go.mod
  go.sum
  scripts/tests.upgrade.sh
  tests/fixture/tmpnet/genesis.go
  tests/upgrade/upgrade_test.go
Labels: testing

#3353 Separate codec registries by upgrade
  vms/platformvm/block/codec.go
  vms/platformvm/txs/codec.go
Labels: cleanup, acp77

#3217 Implement `ConvertSubnetTx`
  tests/e2e/p/permissionless_layer_one.go
  vms/platformvm/block/codec.go
  vms/platformvm/client.go
  vms/platformvm/metrics/tx_metrics.go
  vms/platformvm/service.go
  vms/platformvm/txs/codec.go
  vms/platformvm/txs/convert_subnet_tx.go
  vms/platformvm/txs/convert_subnet_tx_test.go
  vms/platformvm/txs/convert_subnet_tx_test_complex.json
  vms/platformvm/txs/convert_subnet_tx_test_simple.json
  vms/platformvm/txs/executor/atomic_tx_executor.go
  vms/platformvm/txs/executor/proposal_tx_executor.go
  vms/platformvm/txs/executor/standard_tx_executor.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/txs/fee/calculator_test.go
  vms/platformvm/txs/fee/complexity.go
  vms/platformvm/txs/fee/static_calculator.go
  vms/platformvm/txs/visitor.go
  wallet/chain/p/builder/builder.go
  wallet/chain/p/builder/builder_with_options.go
  wallet/chain/p/builder_test.go
  wallet/chain/p/signer/visitor.go
  wallet/chain/p/wallet/backend_visitor.go
  wallet/chain/p/wallet/wallet.go
  wallet/chain/p/wallet/with_options.go
Labels: acp77

#3340 [e2e] Emit a duration-scoped grafana link for each test
  tests/e2e/c/dynamic_fees.go
  tests/fixture/e2e/env.go
  tests/fixture/e2e/flags.go
  tests/fixture/e2e/metrics_link.go
  tests/fixture/tmpnet/network.go
Labels: testing

#3356 [tmpnet] Avoid calling Stat in advance of Read/Open
  tests/fixture/tmpnet/node_process.go
  tests/fixture/tmpnet/subnet.go
Labels: testing

#3359 Align codec interface to exclusively use packers
  codec/codec.go
  codec/manager.go
  codec/reflectcodec/type_codec.go
Labels: cleanup

#3360 Include stacktrace in shutdown timeout message
  snow/networking/router/chain_router.go
Labels: monitoring

#3362 [testing] Cleanup ginkgo imports
  tests/e2e/banff/suites.go
  tests/e2e/c/dynamic_fees.go
  tests/e2e/c/interchain_workflow.go
  tests/e2e/e2e_test.go
  tests/e2e/etna/suites.go
  tests/e2e/faultinjection/duplicate_node_id.go
  tests/e2e/p/elastic_subnets.go
  tests/e2e/p/interchain_workflow.go
  tests/e2e/p/owner_retrieval.go
  tests/e2e/p/permissionless_layer_one.go
  tests/e2e/p/staking_rewards.go
  tests/e2e/p/validator_sets.go
  tests/e2e/p/workflow.go
  tests/e2e/vms/xsvm.go
  tests/e2e/x/interchain_workflow.go
  tests/e2e/x/transfer/virtuous.go
  tests/fixture/e2e/describe.go
  tests/fixture/e2e/env.go
  tests/fixture/e2e/ginkgo_test_context.go
  tests/fixture/e2e/metrics_link.go
Labels: testing

#3345 Abort query if not enough stake is connected
  snow/engine/snowman/engine.go
  snow/engine/snowman/engine_test.go
Labels: consensus, incident response

#3375 Log a fatal before exit if node cannot be created
  app/app.go
Labels: monitoring

#3361 Avoid including 'failed' in debug log messages
  snow/engine/snowman/engine.go
Labels: monitoring

#3371 Add AccruedFees to state.Chain interface
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/block/executor/standard_block_test.go
  vms/platformvm/block/executor/verifier_test.go
  vms/platformvm/state/diff.go
  vms/platformvm/state/diff_test.go
  vms/platformvm/state/mock_chain.go
  vms/platformvm/state/mock_diff.go
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
Labels: acp77

#3370 Add SoV state struct
  vms/platformvm/state/subnet_only_validator.go
  vms/platformvm/state/subnet_only_validator_test.go
Labels: acp77

#3380 Replace iterator equality helper
  utils/iterator/slice.go
  vms/platformvm/state/diff_test.go
  vms/platformvm/state/stakers_test.go
  vms/platformvm/state/state_test.go
Labels: cleanup, acp77

#3383 Use math.Ln2 where possible
  utils/math/continuous_averager.go
  utils/math/meter/continuous_meter.go
Labels: cleanup

#3382 Implement ExpiryEntry
  vms/platformvm/state/expiry.go
  vms/platformvm/state/expiry_test.go
Labels: acp77

#3381 Implement iterator deduplicator
  utils/iterator/filter.go
  utils/iterator/filter_test.go
Labels: acp77

#3367 Implement ACP-77 fee calculations
  vms/platformvm/validators/fee/fee.go
  vms/platformvm/validators/fee/fee_test.go
Labels: acp77

#3379 Add Expiry Replay Protection
  vms/platformvm/state/diff.go
  vms/platformvm/state/diff_test.go
  vms/platformvm/state/expiry.go
  vms/platformvm/state/mock_chain.go
  vms/platformvm/state/mock_diff.go
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
Labels: acp77

#3387 chore: remove redundant symbol in tests/antithesis/README.md
  tests/antithesis/README.md
Labels: documentation

#3386 Grc 243 migrate static aws credentials
  .github/workflows/build-linux-binaries.yml
  .github/workflows/build-macos-release.yml
  .github/workflows/build-public-ami.yml
  .github/workflows/build-ubuntu-amd64-release.yml
  .github/workflows/build-ubuntu-arm64-release.yml
  .github/workflows/build-win-release.yml
Labels: bug, ci

#3395 ACP-77: Update `SecondsUntil` to prevent under-charging
  vms/platformvm/validators/fee/fee.go
  vms/platformvm/validators/fee/fee_test.go
Labels: acp77

#3398 Fix node initialization in snowman test
  snow/consensus/snowman/network_test.go
Labels: bug

#3399 Update to latest coreth dependency version
  go.mod
  go.sum
Labels: dependencies

#3401 Update ubuntu versions
  .github/actionlint.yml
  .github/actions/install-focal-deps/action.yml
  .github/workflows/build-linux-binaries.yml
  .github/workflows/build-ubuntu-amd64-release.yml
  .github/workflows/build-ubuntu-arm64-release.yml
  .github/workflows/ci.yml
Labels: ci

#3402 Remove ami support
  .github/packer/clean-public-ami.sh
  .github/packer/create_public_ami.yml
  .github/packer/roles/public-ami/defaults/main.yml
  .github/packer/roles/public-ami/tasks/main.yml
  .github/packer/roles/public-ami/templates/avalanchego.service.j2
  .github/packer/roles/public-ami/templates/conf.json.j2
  .github/packer/ubuntu-jammy-x86_64-public-ami.pkr.hcl
  .github/workflows/amichange.json
  .github/workflows/build-public-ami.yml
  .github/workflows/update-ami.py
Labels: ci

#3396 Implement acp-77 fee configs
  config/config.go
  config/flags.go
  config/keys.go
  genesis/genesis_fuji.go
  genesis/genesis_local.go
  genesis/genesis_mainnet.go
  genesis/params.go
  node/node.go
  vms/platformvm/config/config.go
Labels: acp77

#3407 Ensure slices are zeroed
  database/batch.go
  database/encdb/db.go
  database/prefixdb/db.go
  utils/set/sampleable_set.go
  utils/zero.go
Labels: cleanup

#3408 Move `validators.TestManager` to `validatorstest.Manager`
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/executor/acceptor_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/validators/test_manager.go
  vms/platformvm/validators/validatorstest/manager.go
Labels: cleanup

#3409 Fix `TestSubnetValidatorBLSKeyDiffAfterExpiry`
  vms/platformvm/vm_regression_test.go
Labels: testing, cleanup

#3235 Remove subnetIDs from uptime manager
  api/info/client.go
  api/info/service.go
  api/info/service.md
  chains/manager.go
  message/internal_msg_builder.go
  message/messagemock/outbound_message_builder.go
  message/messages_test.go
  message/ops.go
  message/outbound_msg_builder.go
  network/metrics.go
  network/network.go
  network/peer/info.go
  network/peer/message_queue_test.go
  network/peer/peer.go
  network/peer/peer_test.go
  network/peer/set_test.go
  proto/p2p/p2p.proto
  proto/pb/p2p/p2p.pb.go
  scripts/mocks.mockgen.txt
  snow/networking/handler/handler.go
  snow/networking/handler/handler_test.go
  snow/networking/handler/health_test.go
  snow/networking/handler/message_queue.go
  snow/networking/router/chain_router.go
  snow/networking/router/chain_router_test.go
  snow/networking/sender/sender_test.go
  snow/uptime/locked_calculator.go
  snow/uptime/locked_calculator_test.go
  snow/uptime/manager.go
  snow/uptime/manager_test.go
  snow/uptime/no_op_calculator.go
  snow/uptime/state.go
  snow/uptime/test_state.go
  snow/uptime/uptimemock/calculator.go
  snow/validators/subnet_connector.go
  snow/validators/unhandled_subnet_connector.go
  snow/validators/validatorsmock/subnet_connector.go
  vms/platformvm/api/static_service.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/executor/block_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/block/executor/options.go
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/client_permissionless_validator.go
  vms/platformvm/service.go
  vms/platformvm/service_test.go
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/vm.go
  vms/platformvm/vm_test.go
Labels: acp77, Uptime Tracking

#3406 Simplify common.Engine API
  chains/manager.go
  snow/engine/avalanche/bootstrap/bootstrapper.go
  snow/engine/common/engine.go
  snow/engine/common/halter.go
  snow/engine/common/no_ops_handlers.go
  snow/engine/common/traced_engine.go
  snow/engine/enginetest/engine.go
  snow/engine/snowman/bootstrap/bootstrapper.go
  snow/engine/snowman/bootstrap/bootstrapper_test.go
  snow/engine/snowman/bootstrap/config.go
  snow/engine/snowman/bootstrap/storage.go
  snow/engine/snowman/bootstrap/storage_test.go
  snow/engine/snowman/engine.go
  snow/engine/snowman/syncer/state_syncer.go
  snow/networking/handler/handler.go
  snow/networking/handler/handler_test.go
  snow/networking/handler/health_test.go
  snow/networking/router/chain_router_test.go
  snow/networking/sender/sender_test.go
  vms/platformvm/vm_test.go
Labels: cleanup

#3411 Bound GetNextStakerChangeTime for ACP-77
  vms/platformvm/block/builder/builder.go
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/block/executor/standard_block_test.go
  vms/platformvm/block/executor/verifier.go
  vms/platformvm/state/chain_time_helpers.go
  vms/platformvm/state/chain_time_helpers_test.go
  vms/platformvm/txs/executor/advance_time_test.go
  vms/platformvm/txs/executor/proposal_tx_executor.go
  vms/platformvm/txs/executor/state_changes.go
  vms/platformvm/txs/executor/state_changes_test.go
Labels: acp77

#3106 Migrate `x/sync` to `p2p`
  network/p2p/p2ptest/client.go
  network/p2p/p2ptest/client_test.go
  proto/pb/sync/sync.pb.go
  proto/sync/sync.proto
  scripts/mocks.mockgen.source.txt
  scripts/mocks.mockgen.txt
  x/merkledb/mock_db.go
  x/sync/client.go
  x/sync/client_test.go
  x/sync/manager.go
  x/sync/mock_client.go
  x/sync/network_client.go
  x/sync/network_server.go
  x/sync/network_server_test.go
  x/sync/response_handler.go
  x/sync/sync_test.go
  x/sync/syncmock/network_client.go
Labels: cleanup

#3415 Remove stale expiries in AdvanceTimeTo
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/block/executor/standard_block_test.go
  vms/platformvm/txs/executor/state_changes.go
  vms/platformvm/txs/executor/state_changes_test.go
Labels: acp77

#3417 Remove mocked iterator
  scripts/mocks.mockgen.source.txt
  utils/iterator/iteratormock/iterator.go
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/state/diff_test.go
Labels: cleanup

#3270 Parsing acp-77 warp payloads
  vms/platformvm/warp/message/README.md
  vms/platformvm/warp/message/codec.go
  vms/platformvm/warp/message/payload.go
  vms/platformvm/warp/message/payload_test.go
  vms/platformvm/warp/message/register_subnet_validator.go
  vms/platformvm/warp/message/register_subnet_validator_test.go
  vms/platformvm/warp/message/set_subnet_validator_weight.go
  vms/platformvm/warp/message/set_subnet_validator_weight_test.go
  vms/platformvm/warp/message/subnet_conversion.go
  vms/platformvm/warp/message/subnet_conversion_test.go
  vms/platformvm/warp/message/subnet_validator_registration.go
  vms/platformvm/warp/message/subnet_validator_registration_test.go
  vms/platformvm/warp/message/subnet_validator_weight.go
  vms/platformvm/warp/message/subnet_validator_weight_test.go
Labels: acp77

#3422 Fix gossip unit test
  network/p2p/gossip/gossip_test.go
Labels: testing, cleanup

#3426 [e2e] Add wallet balance logging to staking rewards test
  tests/antithesis/avalanchego/main.go
  tests/e2e/p/staking_rewards.go
  tests/fixture/e2e/helpers.go
Labels: testing
