Repository ava-labs/avalanchego, pull requests merged in 2024-07, with the labels that each got.

#3160 [ci] Add actionlint job
  .github/actionlint.yml
  .github/workflows/build-linux-binaries.yml
  .github/workflows/build-macos-release.yml
  .github/workflows/build-public-ami.yml
  .github/workflows/build-ubuntu-amd64-release.yml
  .github/workflows/build-ubuntu-arm64-release.yml
  .github/workflows/build-win-release.yml
  .github/workflows/ci.yml
  .github/workflows/publish_antithesis_images.yml
  .github/workflows/trigger-antithesis-runs.yml
  scripts/actionlint.sh
Labels: ci

#3157 check router is closing in requests
  snow/networking/router/chain_router.go
  snow/networking/router/chain_router_test.go
Labels: antithesis

#3166 Use `ids.Empty` instead of `ids.ID{}`
  chains/test_manager.go
  database/helpers.go
  genesis/genesis.go
  ids/galiasreader/alias_reader_client.go
  snow/consensus/snowman/topological.go
  snow/engine/avalanche/bootstrap/queue/test_job.go
  snow/engine/avalanche/state/unique_vertex_test.go
  snow/engine/avalanche/vertex/stateless_vertex_test.go
  snow/engine/snowman/block/test_vm.go
  snow/networking/handler/handler_test.go
  snow/networking/router/chain_router_test.go
  snow/networking/timeout/manager_test.go
  vms/avm/client.go
  vms/avm/vm.go
  vms/avm/wallet_client.go
  vms/components/avax/addresses.go
  vms/components/avax/atomic_utxos.go
  vms/components/avax/utxo_fetching.go
  vms/components/chain/state_test.go
  vms/platformvm/client.go
  vms/platformvm/txs/create_chain_test.go
  vms/proposervm/proposer/windower_test.go
  vms/proposervm/state/chain_state.go
  vms/proposervm/vm_test.go
  x/sync/g_db/db_client.go
Labels: cleanup

#3167 Replace usage of utils.Err with errors.Join
  api/server/metrics.go
  cache/metercacher/metrics.go
  database/leveldb/metrics.go
  database/meterdb/db.go
  genesis/config.go
  indexer/index.go
  message/messages.go
  network/ip_tracker.go
  network/metrics.go
  network/p2p/gossip/gossip.go
  network/p2p/network.go
  network/p2p/peer_tracker.go
  network/peer/metrics.go
  network/throttling/inbound_resource_throttler.go
  network/throttling/outbound_msg_throttler.go
  node/node.go
  snow/engine/avalanche/bootstrap/metrics.go
  snow/engine/avalanche/bootstrap/queue/jobs.go
  snow/engine/avalanche/bootstrap/queue/state.go
  snow/engine/avalanche/vertex/codec.go
  snow/engine/common/tracker/peers.go
  snow/engine/snowman/bootstrap/metrics.go
  snow/networking/benchlist/benchlist.go
  snow/networking/handler/message_queue_metrics.go
  snow/networking/handler/metrics.go
  snow/networking/router/chain_router_metrics.go
  snow/networking/timeout/metrics.go
  snow/networking/tracker/resource_tracker.go
  utils/bloom/metrics.go
  utils/error.go
  utils/metric/api_interceptor.go
  utils/resource/metrics.go
  utils/timer/adaptive_timeout_manager.go
  vms/avm/block/parser.go
  vms/avm/state/state.go
  vms/avm/txs/parser.go
  vms/avm/vm.go
  vms/components/keystore/codec.go
  vms/example/xsvm/execute/tx.go
  vms/example/xsvm/tx/codec.go
  vms/nftfx/fx.go
  vms/platformvm/block/codec.go
  vms/platformvm/state/metadata_codec.go
  vms/platformvm/state/state.go
  vms/platformvm/txs/codec.go
  vms/platformvm/vm.go
  vms/platformvm/warp/codec.go
  vms/platformvm/warp/payload/codec.go
  vms/propertyfx/fx.go
  vms/proposervm/block/codec.go
  vms/proposervm/vm.go
  vms/secp256k1fx/fx.go
  vms/txs/mempool/metrics.go
  x/merkledb/metrics.go
  x/sync/metrics.go
Labels: cleanup

#3170 Refactor rpcchainvm metrics registration
  node/node.go
  vms/registry/vm_getter.go
  vms/rpcchainvm/batched_vm_test.go
  vms/rpcchainvm/factory.go
  vms/rpcchainvm/state_syncable_vm_test.go
  vms/rpcchainvm/vm_client.go
  vms/rpcchainvm/with_context_vm_test.go
Labels: monitoring

#3171 Add example reward calculator usage
  vms/platformvm/reward/example_test.go
Labels: documentation

#2753 Send AppErrors from p2p SDK
  go.mod
  go.sum
  network/p2p/error.go
  network/p2p/gossip/handler.go
  network/p2p/handler.go
  network/p2p/handler_test.go
  network/p2p/network_test.go
  network/p2p/router.go
  network/p2p/throttler_handler.go
  network/p2p/throttler_handler_test.go
  vms/avm/network/gossip.go
  vms/platformvm/network/gossip.go
  vms/platformvm/vm_test.go
Labels: enhancement, networking

#3173 build(tests): require `//go:build test` tag if importing test packages outside of `_test.go` files
  .golangci.yml
  .vscode/settings.json
  cache/test_cacher.go
  chains/atomic/test_shared_memory.go
  codec/test_codec.go
  database/benchmark_database.go
  database/test_database.go
  ids/test_aliases.go
  scripts/build_fuzz.sh
  scripts/build_test.sh
  scripts/lint.sh
  scripts/tests.e2e.existing.sh
  scripts/tests.e2e.sh
  scripts/tests.upgrade.sh
  snow/consensus/snowball/test_snowflake.go
  snow/engine/avalanche/bootstrap/queue/test_job.go
  snow/engine/avalanche/bootstrap/queue/test_parser.go
  snow/engine/avalanche/vertex/test_builder.go
  snow/engine/avalanche/vertex/test_manager.go
  snow/engine/avalanche/vertex/test_parser.go
  snow/engine/avalanche/vertex/test_storage.go
  snow/engine/avalanche/vertex/test_vm.go
  snow/engine/common/test_bootstrap_tracker.go
  snow/engine/common/test_bootstrapper.go
  snow/engine/common/test_engine.go
  snow/engine/common/test_sender.go
  snow/engine/common/test_timer.go
  snow/engine/common/test_vm.go
  snow/engine/snowman/block/test_batched_vm.go
  snow/engine/snowman/block/test_state_summary.go
  snow/engine/snowman/block/test_state_syncable_vm.go
  snow/engine/snowman/block/test_vm.go
  snow/networking/benchlist/test_benchable.go
  snow/networking/sender/test_external_sender.go
  snow/snowtest/snowtest.go
  snow/validators/test_state.go
  tests/e2e/banff/suites.go
  tests/e2e/c/dynamic_fees.go
  tests/e2e/c/interchain_workflow.go
  tests/e2e/faultinjection/duplicate_node_id.go
  tests/e2e/p/interchain_workflow.go
  tests/e2e/p/permissionless_subnets.go
  tests/e2e/p/staking_rewards.go
  tests/e2e/p/validator_sets.go
  tests/e2e/p/workflow.go
  tests/e2e/vms/xsvm.go
  tests/e2e/x/interchain_workflow.go
  tests/e2e/x/transfer/virtuous.go
  tests/fixture/e2e/env.go
  tests/fixture/e2e/helpers.go
  vms/platformvm/warp/test_signer.go
  wallet/subnet/primary/common/test_utxos.go
Labels: cleanup

#3178 Include VM path in plugin version error
  vms/rpcchainvm/runtime/subprocess/initializer.go
  vms/rpcchainvm/runtime/subprocess/runtime.go
Labels: documentation, monitoring

#3161 [ci] Simplify ci monitoring with custom actions
  .github/actions/run-monitored-tmpnet-cmd/action.yml
  .github/actions/run-monitored-tmpnet-cmd/notify-metrics-availability.sh
  .github/actions/upload-tmpnet-artifact/action.yml
  .github/workflows/ci.yml
Labels: ci

#3177 [vms/avm] Replace `strings.Replace` with `fmt.Sprintf` in tests
  vms/avm/service_test.go
Labels: testing, cleanup

#3151 Reduce usage of `getBlock` in consensus
  snow/engine/snowman/issuer.go
  snow/engine/snowman/transitive.go
  snow/engine/snowman/transitive_test.go
  snow/engine/snowman/voter.go
Labels: consensus, cleanup

#3186 [ci] Enable run-monitored-tmpnet-cmd reuse by other repos
  .github/actions/run-monitored-tmpnet-cmd/action.yml
Labels: ci

#3183 [ci] Allow antithesis test setups to be triggered independently
  .github/workflows/trigger-antithesis-avalanchego.yml
  .github/workflows/trigger-antithesis-xsvm.yml
Labels: ci

#3191 [antithesis] Fix image version separator in triggering workflows
  .github/workflows/trigger-antithesis-avalanchego.yml
  .github/workflows/trigger-antithesis-xsvm.yml
Labels: ci

#3158 Remove `block.Status`
  go.mod
  go.sum
  proto/pb/vm/vm.pb.go
  proto/vm/vm.proto
  snow/consensus/snowman/block.go
  snow/consensus/snowman/consensus_test.go
  snow/consensus/snowman/metrics.go
  snow/consensus/snowman/network_test.go
  snow/consensus/snowman/snowmantest/block.go
  snow/consensus/snowman/snowmantest/engine.go
  snow/consensus/snowman/snowmantest/mock_block.go
  snow/consensus/snowman/snowmantest/require.go
  snow/decidable.go
  snow/engine/snowman/bootstrap/bootstrapper_test.go
  snow/engine/snowman/bootstrap/storage_test.go
  snow/engine/snowman/getter/getter.go
  snow/engine/snowman/getter/getter_test.go
  snow/engine/snowman/transitive_test.go
  snow/snowtest/context.go
  snow/snowtest/decidable.go
  snow/snowtest/status.go
  vms/avm/block/executor/block.go
  vms/avm/block/executor/block_test.go
  vms/components/chain/state.go
  vms/components/chain/state_test.go
  vms/example/xsvm/chain/block.go
  vms/example/xsvm/chain/chain.go
  vms/platformvm/block/executor/block.go
  vms/platformvm/block/executor/block_test.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
  vms/proposervm/batched_vm.go
  vms/proposervm/batched_vm_test.go
  vms/proposervm/block.go
  vms/proposervm/mock_post_fork_block.go
  vms/proposervm/post_fork_block.go
  vms/proposervm/post_fork_block_test.go
  vms/proposervm/post_fork_option.go
  vms/proposervm/post_fork_option_test.go
  vms/proposervm/pre_fork_block.go
  vms/proposervm/pre_fork_block_test.go
  vms/proposervm/state/block_state.go
  vms/proposervm/state/block_state_test.go
  vms/proposervm/state/mock_state.go
  vms/proposervm/state_syncable_vm_test.go
  vms/proposervm/tree/tree_test.go
  vms/proposervm/vm.go
  vms/proposervm/vm_byzantine_test.go
  vms/proposervm/vm_test.go
  vms/rpcchainvm/batched_vm_test.go
  vms/rpcchainvm/state_syncable_vm_test.go
  vms/rpcchainvm/vm_client.go
  vms/rpcchainvm/vm_server.go
Labels: consensus

#3192 [antithesis] Add schedule for workflows
  .github/workflows/trigger-antithesis-avalanchego.yml
  .github/workflows/trigger-antithesis-xsvm.yml
Labels: ci

#3195 Update `golangci-lint` to `v1.59.1`
  .golangci.yml
  message/messages_test.go
  network/p2p/handler.go
  scripts/lint.sh
  snow/engine/avalanche/getter/getter.go
  snow/engine/snowman/transitive.go
  tests/fixture/tmpnet/network.go
  vms/proposervm/vm.go
Labels: ci

#3193 [ci] Ensure monitoring action compatibility for other repos
  .github/actions/run-monitored-tmpnet-cmd/action.yml
Labels: ci

#3194 chore: fix some comments for struct field
  snow/validators/manager.go
  utils/logging/factory.go
Labels: cleanup

#3196 [antithesis] Configure workload history
  .github/workflows/trigger-antithesis-avalanchego.yml
  .github/workflows/trigger-antithesis-xsvm.yml
Labels: ci

#3205 Make math.Add64 and math.Mul64 generic
  genesis/config.go
  snow/consensus/snowman/bootstrapper/majority.go
  snow/consensus/snowman/bootstrapper/sampler.go
  snow/engine/avalanche/state/serializer.go
  snow/engine/snowman/syncer/state_syncer.go
  snow/engine/snowman/transitive.go
  snow/networking/benchlist/benchlist.go
  snow/validators/set.go
  utils/math/safe_math.go
  utils/math/safe_math_test.go
  utils/sampler/weighted_array.go
  utils/sampler/weighted_benchmark_test.go
  utils/sampler/weighted_best.go
  utils/sampler/weighted_heap.go
  utils/sampler/weighted_linear.go
  utils/sampler/weighted_uniform.go
  utils/sampler/weighted_without_replacement_generic.go
  vms/avm/service.go
  vms/avm/utxo/spender.go
  vms/avm/wallet_service.go
  vms/components/avax/flow_checker.go
  vms/components/avax/utxo_fetching.go
  vms/example/xsvm/state/storage.go
  vms/platformvm/api/static_service.go
  vms/platformvm/reward/calculator.go
  vms/platformvm/service.go
  vms/platformvm/state/state.go
  vms/platformvm/txs/add_delegator_tx.go
  vms/platformvm/txs/add_permissionless_delegator_tx.go
  vms/platformvm/txs/add_permissionless_validator_tx.go
  vms/platformvm/txs/add_validator_tx.go
  vms/platformvm/txs/executor/staker_tx_verification.go
  vms/platformvm/txs/executor/staker_tx_verification_helpers.go
  vms/platformvm/utxo/verifier.go
  vms/platformvm/warp/validator.go
  vms/proposervm/proposer/windower.go
  vms/secp256k1fx/input.go
  wallet/chain/c/backend.go
  wallet/chain/c/builder.go
  wallet/chain/p/builder/builder.go
  wallet/chain/x/builder/builder.go
Labels: cleanup

#3206 [antithesis] Fix job duration
  .github/workflows/trigger-antithesis-avalanchego.yml
  .github/workflows/trigger-antithesis-xsvm.yml
Labels: ci

#3212 [vms/platformvm] `RegisterDUnsignedTxsTypes` -> `RegisterDurangoUnsignedTxsTypes`
  vms/platformvm/block/codec.go
  vms/platformvm/txs/codec.go
Labels: cleanup

#3213 chore: fix some comments
  wallet/chain/c/wallet.go
  wallet/chain/p/wallet.go
Labels: cleanup

#3208 Fix typos
  config/config.md
  database/database.go
  snow/consensus/snowball/unary_snowflake.go
  snow/engine/avalanche/bootstrap/queue/jobs.go
  tests/antithesis/README.md
Labels: cleanup

#3210 Cleanup fee.staticCalculator
  vms/platformvm/service_test.go
  vms/platformvm/txs/executor/staker_tx_verification.go
  vms/platformvm/txs/executor/standard_tx_executor.go
  vms/platformvm/txs/fee/calculator.go
  vms/platformvm/txs/fee/calculator_test.go
  vms/platformvm/txs/fee/static_calculator.go
  vms/platformvm/txs/txstest/context.go
Labels: cleanup

#3204 add getSubnet to p-chain api reference
  vms/platformvm/service.md
Labels: documentation

#3221 [ci] Update fuzz workflows to target master branch
  .github/workflows/fuzz.yml
  .github/workflows/fuzz_merkledb.yml
Labels: ci

#3230 Cleanup wallet tests
  wallet/chain/p/builder_test.go
Labels: testing, cleanup

#3234 [ci] Remove defunct network outage sim workflow
  .github/actionlint.yml
  .github/workflows/cleanup-net-outage-sim.sh
  .github/workflows/net-outage-sim.yml
  .github/workflows/run-net-outage-sim.sh
Labels: ci

#3086 Remove deadcode
  database/helpers.go
  network/p2p/gossip/gossip.go
  utils/hashing/hashing.go
  vms/rpcchainvm/grpcutils/util.go
Labels: cleanup

#3214 [ci] Lint on non-test code importing packages from /tests
  scripts/lint.sh
  scripts/tests.e2e.existing.sh
  scripts/tests.e2e.sh
  scripts/tests.upgrade.sh
  tests/e2e/banff/suites.go
  tests/e2e/c/dynamic_fees.go
  tests/e2e/c/interchain_workflow.go
  tests/e2e/faultinjection/duplicate_node_id.go
  tests/e2e/p/interchain_workflow.go
  tests/e2e/p/permissionless_subnets.go
  tests/e2e/p/staking_rewards.go
  tests/e2e/p/validator_sets.go
  tests/e2e/p/workflow.go
  tests/e2e/vms/xsvm.go
  tests/e2e/x/interchain_workflow.go
  tests/e2e/x/transfer/virtuous.go
  tests/fixture/e2e/env.go
  tests/fixture/e2e/helpers.go
Labels: ci

#3218 ACP 118 reference implementation
  network/p2p/handler.go
  proto/pb/sdk/sdk.pb.go
  proto/sdk/sdk.proto
  vms/avm/network/network.go
  vms/platformvm/network/network.go
  vms/platformvm/vm_regression_test.go
Labels: Warp Signature API

#3245 Remove unused error from fee calculator creation
  vms/platformvm/block/builder/builder.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/block/executor/manager.go
  vms/platformvm/block/executor/verifier.go
  vms/platformvm/service_test.go
  vms/platformvm/state/chain_time_helpers.go
  vms/platformvm/txs/executor/advance_time_test.go
  vms/platformvm/txs/executor/create_chain_test.go
  vms/platformvm/txs/executor/create_subnet_test.go
  vms/platformvm/txs/executor/export_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/txs/executor/import_test.go
  vms/platformvm/txs/executor/proposal_tx_executor_test.go
  vms/platformvm/txs/executor/reward_validator_test.go
  vms/platformvm/txs/executor/staker_tx_verification_test.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
Labels: cleanup, acp103

#3244 Rename Transitive snowman to Engine snowman
  snow/engine/snowman/engine.go
  snow/engine/snowman/engine_test.go
  snow/engine/snowman/issuer.go
  snow/engine/snowman/voter.go
Labels: cleanup

#3240 Simplify static fee calculations
  api/info/service.go
  config/config.go
  config/flags.go
  genesis/genesis_fuji.go
  genesis/genesis_local.go
  genesis/genesis_mainnet.go
  genesis/params.go
  node/config.go
  node/node.go
  tests/antithesis/avalanchego/main.go
  vms/platformvm/block/executor/verifier.go
  vms/platformvm/config/config.go
  vms/platformvm/service_test.go
  vms/platformvm/state/chain_time_helpers.go
  vms/platformvm/txs/fee/calculator.go
  vms/platformvm/txs/fee/calculator_test.go
  vms/platformvm/txs/fee/static_calculator.go
  vms/platformvm/txs/fee/static_calculator_test.go
  vms/platformvm/txs/fee/static_config.go
  vms/platformvm/txs/txstest/context.go
  wallet/chain/p/builder/builder.go
  wallet/chain/p/builder/context.go
  wallet/chain/p/builder_test.go
Labels: cleanup, acp103

#3249 Remove targetBlockSize arg
  vms/platformvm/block/builder/builder.go
  vms/platformvm/vm.go
Labels: acp103

#3250 Add dynamic fees config
  config/config.go
  config/flags.go
  config/keys.go
  genesis/genesis_fuji.go
  genesis/genesis_local.go
  genesis/genesis_mainnet.go
  genesis/params.go
  node/node.go
  vms/platformvm/config/config.go
Labels: acp103

#3219 Remove unused Samplers
  utils/sampler/uniform_benchmark_test.go
  utils/sampler/uniform_best.go
  utils/sampler/uniform_resample.go
  utils/sampler/uniform_test.go
  utils/sampler/weighted.go
  utils/sampler/weighted_array.go
  utils/sampler/weighted_array_test.go
  utils/sampler/weighted_benchmark_test.go
  utils/sampler/weighted_best.go
  utils/sampler/weighted_linear.go
  utils/sampler/weighted_linear_test.go
  utils/sampler/weighted_test.go
  utils/sampler/weighted_uniform.go
  utils/sampler/weighted_without_replacement.go
  utils/sampler/weighted_without_replacement_benchmark_test.go
  utils/sampler/weighted_without_replacement_test.go
Labels: cleanup

#3252 Inline `verifier` struct creation
  vms/platformvm/block/executor/block.go
  vms/platformvm/block/executor/manager.go
  vms/platformvm/block/executor/verifier_test.go
Labels: cleanup, acp77

#3248 Add fee.State to P-chain state
  vms/components/fee/state.go
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/block/executor/standard_block_test.go
  vms/platformvm/block/executor/verifier_test.go
  vms/platformvm/state/diff.go
  vms/platformvm/state/diff_test.go
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
Labels: acp103
