Repository ava-labs/avalanchego, pull requests merged in 2024-06, with the labels that each got.

#3073 Select metric by label in e2e tests
  tests/e2e/x/transfer/virtuous.go
  tests/metrics.go
Labels: monitoring

#3074 Implement label gatherer
  api/metrics/gatherer_test.go
  api/metrics/label_gatherer.go
  api/metrics/label_gatherer_test.go
  api/metrics/multi_gatherer.go
  api/metrics/multi_gatherer_test.go
  api/metrics/prefix_gatherer.go
  api/metrics/prefix_gatherer_test.go
Labels: monitoring

#3087 Remove avalanche metrics registerer from consensus context
  chains/manager.go
  snow/context.go
  snow/engine/avalanche/bootstrap/bootstrapper.go
  snow/engine/avalanche/bootstrap/bootstrapper_test.go
  snow/networking/sender/sender.go
  snow/networking/sender/sender_test.go
  snow/snowtest/snowtest.go
  vms/platformvm/vm_test.go
Labels: monitoring

#3084 Remove rejection from `consensus.Add`
  snow/consensus/snowman/consensus.go
  snow/consensus/snowman/consensus_test.go
  snow/consensus/snowman/network_test.go
  snow/consensus/snowman/topological.go
  snow/consensus/snowman/traced_consensus.go
  snow/engine/snowman/transitive.go
  snow/engine/snowman/transitive_test.go
Labels: consensus, cleanup

#2890 [vms/platformvm] Rename `txstest.Builder` to `txstest.WalletFactory`
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/builder/standard_block_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/block/executor/standard_block_test.go
  vms/platformvm/service_test.go
  vms/platformvm/txs/executor/advance_time_test.go
  vms/platformvm/txs/executor/create_chain_test.go
  vms/platformvm/txs/executor/create_subnet_test.go
  vms/platformvm/txs/executor/export_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/txs/executor/import_test.go
  vms/platformvm/txs/executor/proposal_tx_executor_test.go
  vms/platformvm/txs/executor/reward_validator_test.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/txs/txstest/builder.go
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
Labels: testing, cleanup

#3088 Small metrics cleanup
  snow/networking/handler/handler.go
  snow/networking/handler/message_queue.go
  snow/networking/handler/message_queue_test.go
  vms/avm/vm.go
  vms/platformvm/vm.go
Labels: monitoring

#3089 Fix race in test
  vms/platformvm/service_test.go
Labels: testing

#2978 Implement error driven snowflake hardcoded to support a single beta
  snow/consensus/snowball/binary_snowflake.go
  snow/consensus/snowball/nnary_snowflake.go
  snow/consensus/snowball/parameters.go
  snow/consensus/snowball/unary_snowball.go
  snow/consensus/snowball/unary_snowball_test.go
  snow/consensus/snowball/unary_snowflake.go
  snow/consensus/snowball/unary_snowflake_test.go
Labels: consensus

#3053 Replace all chain namespaces with labels
  api/metrics/prefix_gatherer.go
  api/metrics/prefix_gatherer_test.go
  chains/linearizable_vm.go
  chains/manager.go
  database/meterdb/db.go
  database/meterdb/db_test.go
  node/node.go
  snow/consensus/snowman/consensus_test.go
  snow/context.go
  snow/networking/benchlist/benchlist.go
  snow/networking/benchlist/benchlist_test.go
  snow/networking/benchlist/manager.go
  snow/networking/benchlist/metrics.go
  snow/networking/handler/handler.go
  snow/networking/handler/handler_test.go
  snow/networking/handler/health_test.go
  snow/networking/handler/metrics.go
  snow/networking/router/chain_router.go
  snow/networking/router/chain_router_metrics.go
  snow/networking/router/chain_router_test.go
  snow/networking/router/mock_router.go
  snow/networking/router/router.go
  snow/networking/router/traced_router.go
  snow/networking/sender/sender_test.go
  snow/networking/timeout/manager.go
  snow/networking/timeout/manager_test.go
  snow/networking/timeout/metrics.go
  snow/networking/tracker/resource_tracker.go
  snow/snowtest/snowtest.go
  tests/e2e/x/transfer/virtuous.go
  utils/resource/metrics.go
  utils/resource/usage.go
  utils/timer/adaptive_timeout_manager.go
  utils/timer/adaptive_timeout_manager_test.go
  vms/metervm/block_vm.go
  vms/metervm/vertex_vm.go
  vms/platformvm/vm_test.go
  vms/proposervm/batched_vm_test.go
  vms/proposervm/block_test.go
  vms/proposervm/config.go
  vms/proposervm/post_fork_option_test.go
  vms/proposervm/state_syncable_vm_test.go
  vms/proposervm/vm.go
  vms/proposervm/vm_test.go
  vms/rpcchainvm/vm_client.go
  vms/rpcchainvm/vm_server.go
Labels: monitoring

#3048 add a metrics gauge for built block slot
  vms/proposervm/block.go
  vms/proposervm/block_test.go
  vms/proposervm/post_fork_block.go
  vms/proposervm/vm.go
Labels: monitoring

#3090 [ci] Switch to gh workers for arm64
  .github/workflows/build-linux-binaries.yml
  .github/workflows/build-ubuntu-arm64-release.yml
  .github/workflows/ci.yml
Labels: ci

#3091 [ci] Ensure focal arm64 builds all have their required dependencies
  .github/actions/install-focal-deps/action.yml
  .github/workflows/build-linux-binaries.yml
  .github/workflows/build-ubuntu-arm64-release.yml
  .github/workflows/ci.yml
Labels: ci

#2736 X-chain - consolidate tx creation in unit tests
  vms/avm/environment_test.go
  vms/avm/index_test.go
  vms/avm/service_test.go
  vms/avm/state_test.go
  vms/avm/txs/txstest/builder.go
  vms/avm/txs/txstest/context.go
  vms/avm/txs/txstest/utxos.go
  vms/avm/vm_benchmark_test.go
  vms/avm/vm_regression_test.go
  vms/avm/vm_test.go
  vms/avm/wallet_service_test.go
Labels: testing, cleanup

#3094 Use netip.AddrPort rather than ips.IPPort
  api/info/client.go
  api/info/service.go
  config/config.go
  genesis/bootstrappers.go
  message/mock_outbound_message_builder.go
  message/outbound_msg_builder.go
  nat/nat.go
  nat/no_router.go
  nat/pmp.go
  nat/upnp.go
  network/config.go
  network/dialer/dialer.go
  network/dialer/dialer_test.go
  network/dialer_test.go
  network/example_test.go
  network/ip_tracker_test.go
  network/listener_test.go
  network/network.go
  network/network_test.go
  network/peer/example_test.go
  network/peer/info.go
  network/peer/ip.go
  network/peer/ip_signer.go
  network/peer/ip_signer_test.go
  network/peer/ip_test.go
  network/peer/peer.go
  network/peer/peer_test.go
  network/peer/test_peer.go
  network/test_network.go
  network/throttling/inbound_conn_upgrade_throttler.go
  network/throttling/inbound_conn_upgrade_throttler_test.go
  network/tracked_ip.go
  network/tracked_ip_test.go
  node/config.go
  node/node.go
  utils/atomic.go
  utils/atomic_test.go
  utils/beacon/beacon.go
  utils/beacon/set.go
  utils/beacon/set_test.go
  utils/dynamicip/ifconfig_resolver.go
  utils/dynamicip/opendns_resolver.go
  utils/dynamicip/resolver.go
  utils/dynamicip/updater.go
  utils/dynamicip/updater_test.go
  utils/ips/claimed_ip_port.go
  utils/ips/dynamic_ip_port.go
  utils/ips/ip.go
  utils/ips/ip_port.go
  utils/ips/ip_test.go
  utils/ips/lookup.go
  utils/ips/lookup_test.go
Labels: networking, cleanup

#3092 Error driven snowflake multi counter
  snow/consensus/snowball/binary_snowball.go
  snow/consensus/snowball/binary_snowball_test.go
  snow/consensus/snowball/binary_snowflake.go
  snow/consensus/snowball/binary_snowflake_test.go
  snow/consensus/snowball/factory.go
  snow/consensus/snowball/flat_test.go
  snow/consensus/snowball/nnary_snowball.go
  snow/consensus/snowball/nnary_snowball_test.go
  snow/consensus/snowball/nnary_snowflake.go
  snow/consensus/snowball/nnary_snowflake_test.go
  snow/consensus/snowball/parameters.go
  snow/consensus/snowball/test_snowflake.go
  snow/consensus/snowball/tree_test.go
  snow/consensus/snowball/unary_snowball.go
  snow/consensus/snowball/unary_snowball_test.go
  snow/consensus/snowball/unary_snowflake.go
  snow/consensus/snowball/unary_snowflake_test.go
Labels: consensus

#3076 [antithesis] Add ci jobs to trigger test runs
  .github/workflows/publish_antithesis_images.yml
  .github/workflows/trigger-antithesis-runs.yml
  tests/antithesis/README.md
Labels: ci

#3115 bump ledger-avalanche dependency to current main branch
  go.mod
  go.sum
Labels: dependencies

#3112 [antithesis] Fix image publication job by quoting default tag value
  .github/workflows/publish_antithesis_images.yml
Labels: ci

#3111 Remove .Status() from .IsPreferred()
  snow/consensus/snowman/consensus.go
  snow/consensus/snowman/consensus_test.go
  snow/consensus/snowman/topological.go
  snow/engine/snowman/transitive.go
Labels: consensus

#3093 Add early termination metrics case by case
  snow/consensus/snowman/poll/early_term_no_traversal.go
  snow/consensus/snowman/poll/early_term_no_traversal_test.go
  snow/consensus/snowman/poll/set_test.go
  snow/engine/snowman/transitive.go
Labels: enhancement, consensus, monitoring

#3118 Update C-chain wallet context
  tests/e2e/c/interchain_workflow.go
  tests/e2e/p/interchain_workflow.go
  tests/e2e/x/interchain_workflow.go
  wallet/chain/c/backend.go
  wallet/chain/c/builder.go
  wallet/chain/c/context.go
  wallet/chain/c/signer.go
  wallet/chain/c/wallet.go
  wallet/subnet/primary/api.go
  wallet/subnet/primary/examples/c-chain-export/main.go
  wallet/subnet/primary/examples/c-chain-import/main.go
  wallet/subnet/primary/wallet.go
Labels: cleanup

#3110 Standardize wallet tx acceptance polling
  tests/antithesis/avalanchego/main.go
  tests/antithesis/xsvm/main.go
  tests/e2e/vms/xsvm.go
  tests/e2e/x/transfer/virtuous.go
  vms/avm/client.go
  vms/example/xsvm/api/client.go
  vms/example/xsvm/cmd/issue/export/cmd.go
  vms/example/xsvm/cmd/issue/importtx/cmd.go
  vms/example/xsvm/cmd/issue/transfer/cmd.go
  vms/platformvm/client.go
  wallet/chain/c/wallet.go
  wallet/chain/p/wallet.go
  wallet/chain/x/wallet.go
Labels: bug, cleanup

#3104 [antithesis] Remove assertions incompatible with fault injection
  tests/antithesis/avalanchego/main.go
  tests/antithesis/xsvm/main.go
Labels: testing

#3122 Use health labels
  api/health/health.go
  api/health/metrics.go
  api/health/worker.go
Labels: monitoring, cleanup

#3123 Remove `Decided` from the `Consensus` interface
  snow/consensus/snowman/consensus.go
  snow/consensus/snowman/consensus_test.go
  snow/consensus/snowman/topological.go
  snow/engine/snowman/transitive.go
Labels: consensus, cleanup

#3124 Remove .Status() from .Accepted()
  snow/consensus/snowman/snowman_block.go
  snow/consensus/snowman/topological.go
Labels: consensus, cleanup

#3127 Remove `Cancel` from the `Job` interface
  snow/engine/snowman/issuer.go
  snow/engine/snowman/job/scheduler.go
  snow/engine/snowman/job/scheduler_test.go
  snow/engine/snowman/voter.go
Labels: consensus, cleanup

#3125 Refactor `event.Blocker` into `job.Scheduler`
  snow/engine/snowman/issuer.go
  snow/engine/snowman/job/scheduler.go
  snow/engine/snowman/job/scheduler_test.go
  snow/engine/snowman/transitive.go
  snow/engine/snowman/transitive_test.go
  snow/engine/snowman/voter.go
  snow/event/blockable.go
  snow/event/blocker.go
  snow/event/blocker_test.go
Labels: consensus, cleanup

#3130 Remove block lookup from `deliver`
  snow/engine/snowman/transitive.go
Labels: consensus, cleanup

#3135 [chains/atomic] Remove a nested if statement
  chains/atomic/state.go
Labels: cleanup

#3136 [vms/platformvm] Minor grammer fixes in `state` struct code comments
  vms/platformvm/state/state.go
Labels: cleanup

#3142 bump protobuf (fixes some build issues)
  go.mod
  go.sum
Labels: dependencies

#3129 Emit version in JSON format for --json-version
  config/flags.go
  config/keys.go
  main/main.go
  version/string.go
  version/string_test.go
Labels: testing

#3137 [vms/platformvm] Cleanup execution config tests
  vms/platformvm/config/execution_config_test.go
Labels: testing, cleanup

#3138 [tmpnet] Enable bootstrap of subnets with disjoint validator sets
  tests/e2e/vms/xsvm.go
  tests/fixture/tmpnet/network.go
  tests/fixture/tmpnet/subnet.go
Labels: testing

#3139 Simplify dependency registration
  snow/engine/snowman/issuer.go
  snow/engine/snowman/transitive.go
Labels: consensus, cleanup

#3131 Replace `wasIssued` with `shouldIssueBlock`
  snow/engine/snowman/transitive.go
  snow/engine/snowman/transitive_test.go
Labels: consensus, cleanup

#3132 Remove parent lookup from issue
  snow/engine/snowman/transitive.go
Labels: consensus, cleanup

#3140 Remove status usage from consensus
  snow/engine/snowman/transitive.go
Labels: consensus, cleanup

#3156 Fix bootstrapping warn log
  node/node.go
Labels: bug
