Repository ava-labs/avalanchego, pull requests merged in 2024-05, with the labels that each got.

#2970 Consolidate record poll
  snow/consensus/snowball/binary_snowball.go
  snow/consensus/snowball/binary_snowball_test.go
  snow/consensus/snowball/binary_snowflake.go
  snow/consensus/snowball/binary_snowflake_test.go
  snow/consensus/snowball/consensus.go
  snow/consensus/snowball/factory.go
  snow/consensus/snowball/flat.go
  snow/consensus/snowball/nnary_snowball.go
  snow/consensus/snowball/nnary_snowball_test.go
  snow/consensus/snowball/nnary_snowflake.go
  snow/consensus/snowball/nnary_snowflake_test.go
  snow/consensus/snowball/tree.go
  snow/consensus/snowball/unary_snowball.go
  snow/consensus/snowball/unary_snowball_test.go
  snow/consensus/snowball/unary_snowflake.go
  snow/consensus/snowball/unary_snowflake_test.go
Labels: consensus

#2980 Reduce p2p sdk metrics
  network/p2p/network.go
  network/p2p/router.go
Labels: monitoring

#2985 Use vectors in message queue metrics
  snow/networking/handler/handler.go
  snow/networking/handler/message_queue.go
  snow/networking/handler/message_queue_metrics.go
  snow/networking/handler/message_queue_test.go
Labels: monitoring

#2983 Use vectors for p2p message metrics
  network/network.go
  network/peer/metrics.go
  network/peer/peer.go
  network/peer/peer_test.go
  network/peer/test_peer.go
Labels: monitoring, networking

#2984 Simplify gossip metrics
  network/p2p/gossip/gossip.go
  network/p2p/gossip/handler.go
Labels: monitoring, networking

#2987 Use vectors for message handler metrics
  snow/networking/handler/handler.go
  snow/networking/handler/metrics.go
Labels: consensus, monitoring

#2988 Use vector in message sender
  snow/networking/sender/sender.go
Labels: monitoring, networking

#2977 Simplify go version maintenance
  .github/actions/set-go-version-in-env/action.yml
  .github/actions/set-go-version-in-env/go_version_env.sh
  .github/actions/setup-go-for-project-v3/action.yml
  .github/actions/setup-go-for-project/action.yml
  .github/workflows/build-linux-binaries.yml
  .github/workflows/build-macos-release.yml
  .github/workflows/build-public-ami.yml
  .github/workflows/build-ubuntu-amd64-release.yml
  .github/workflows/build-ubuntu-arm64-release.yml
  .github/workflows/build-win-release.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/fuzz.yml
  .github/workflows/fuzz_merkledb.yml
  .github/workflows/publish_antithesis_images.yml
  Dockerfile
  README.md
  go.mod
  proto/Dockerfile.buf
  proto/README.md
  scripts/build_image.sh
  scripts/protobuf_codegen.sh
  tests/antithesis/Dockerfile.node
  tests/antithesis/Dockerfile.workload
Labels: ci

#2989 Use vector for router latency metrics
  snow/networking/timeout/manager.go
  snow/networking/timeout/metrics.go
Labels: monitoring, networking

#2990 Use vectors for accepted tx and block metrics
  vms/avm/metrics/tx_metrics.go
  vms/platformvm/metrics/block_metrics.go
  vms/platformvm/metrics/tx_metrics.go
Labels: vm, monitoring

#2991 Cleanup meterdb metrics
  database/meterdb/db.go
  database/meterdb/metrics.go
Labels: monitoring

#2992 Cleanup compression metrics
  message/messages.go
Labels: monitoring, networking

#2998 Fix antithesis image publication
  .github/workflows/publish_antithesis_images.yml
Labels: ci

#3001 Remove unused `Metadata` struct
  go.mod
  go.sum
  vms/components/avax/metadata.go
  vms/components/avax/metadata_test.go
Labels: cleanup

#3004 Update go version to 1.21.10
  CONTRIBUTING.md
  README.md
  go.mod
Labels: dependencies

#2994 vms/txs/mempool: unify avm and platformvm mempool implementations
  vms/avm/network/gossip.go
  vms/avm/network/network_test.go
  vms/avm/txs/mempool/mempool.go
  vms/avm/txs/mempool/mempool_test.go
  vms/avm/txs/tx.go
  vms/avm/vm.go
  vms/avm/wallet_service.go
  vms/platformvm/network/gossip.go
  vms/platformvm/network/gossip_test.go
  vms/platformvm/network/network_test.go
  vms/platformvm/txs/mempool/mempool.go
  vms/platformvm/txs/mempool/mempool_test.go
  vms/platformvm/txs/tx.go
  vms/platformvm/vm.go
  vms/txs/mempool/mempool.go
  vms/txs/mempool/mempool_test.go
  vms/txs/mempool/metrics.go
Labels: vm, cleanup

#3009 Use gauges for time metrics
  cache/metercacher/metrics.go
  database/leveldb/metrics.go
  database/meterdb/db.go
  message/messages.go
  network/p2p/network.go
  network/p2p/router.go
  snow/networking/handler/metrics.go
  snow/networking/timeout/metrics.go
Labels: bug, monitoring

#3010 Chore: fix typos.
  network/README.md
  vms/platformvm/docs/validators_versioning.md
Labels: cleanup

#2976 [antithesis] Refactor existing job to support xsvm test setup
  .github/workflows/ci.yml
  .github/workflows/publish_antithesis_images.yml
  config/viper.go
  go.mod
  go.sum
  scripts/build_antithesis_avalanchego_workload.sh
  scripts/build_antithesis_images.sh
  scripts/build_test.sh
  scripts/tests.build_antithesis_images.sh
  tests/antithesis/Dockerfile.config
  tests/antithesis/README.md
  tests/antithesis/avalanchego/Dockerfile.config
  tests/antithesis/avalanchego/Dockerfile.node
  tests/antithesis/avalanchego/Dockerfile.workload
  tests/antithesis/avalanchego/config.go
  tests/antithesis/avalanchego/gencomposeconfig/main.go
  tests/antithesis/avalanchego/main.go
  tests/antithesis/compose.go
  tests/antithesis/docker-compose.yml
  tests/fixture/tmpnet/local_network.go
  tests/fixture/tmpnet/network.go
Labels: testing

#2981 Mark nodes as connected to the P-chain networking stack
  network/p2p/handler.go
  network/p2p/throttler_handler.go
  vms/platformvm/vm.go
Labels: bug, networking

#3016 [antithesis] Ensure images with a prefix are pushed
  .github/workflows/publish_antithesis_images.yml
  scripts/build_antithesis_images.sh
Labels: ci

#2997 boostrapper: compact blocks before iterating them
  snow/engine/snowman/bootstrap/storage.go
Labels: consensus, storage

#3018 Remove pre-Durango networking checks
  network/peer/peer.go
  proto/pb/sdk/sdk.pb.go
  proto/sdk/sdk.proto
Labels: networking, cleanup

#3017 Standardize peer logs
  network/peer/msg_length.go
  network/peer/peer.go
Labels: monitoring, cleanup

#3020 Fix pebbledb memory corruption
  database/pebble/batch.go
  database/pebble/batch_test.go
  database/pebble/db.go
  database/pebble/db_test.go
  database/pebble/iterator.go
Labels: bug, storage

#3023 [vms/avm] fix linter error in benchmark : Use of weak random number generator
  config/config_test.go
  config/keys.go
  vms/avm/vm_benchmark_test.go
  vms/platformvm/service_test.go
Labels: cleanup

#3026 Simplify sampler interface
  network/ip_tracker.go
  network/p2p/validators.go
  network/peer/set.go
  snow/consensus/snowman/bootstrapper/sampler.go
  snow/validators/manager_test.go
  snow/validators/set.go
  snow/validators/set_test.go
  utils/sampler/uniform.go
  utils/sampler/uniform_best.go
  utils/sampler/uniform_replacer.go
  utils/sampler/uniform_resample.go
  utils/sampler/uniform_test.go
  utils/sampler/weighted.go
  utils/sampler/weighted_array.go
  utils/sampler/weighted_best.go
  utils/sampler/weighted_heap.go
  utils/sampler/weighted_linear.go
  utils/sampler/weighted_test.go
  utils/sampler/weighted_uniform.go
  utils/sampler/weighted_without_replacement.go
  utils/sampler/weighted_without_replacement_generic.go
  utils/sampler/weighted_without_replacement_test.go
  vms/avm/environment_test.go
  vms/proposervm/proposer/windower.go
Labels: cleanup

#3024 [build] Update linter version
  .golangci.yml
  network/peer/tls_config.go
  scripts/lint.sh
  vms/platformvm/txs/executor/import_test.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
Labels: ci

#3033 `gossipping` -> `gossiping`
  RELEASES.md
  node/node.go
  snow/README.md
Labels: cleanup

#3002 [tmpnet] Ensure tmpnet compatibility with windows
  scripts/build_test.sh
  tests/fixture/tmpnet/detached_process_default.go
  tests/fixture/tmpnet/detached_process_windows.go
  tests/fixture/tmpnet/node_process.go
Labels: testing

#3036 Fix negative ETA caused by rollback in vm.SetState
  snow/engine/snowman/bootstrap/bootstrapper.go
  snow/engine/snowman/bootstrap/bootstrapper_test.go
Labels: bug

#3003 [tmpnet] Enable single node networks
  tests/e2e/c/dynamic_fees.go
  tests/e2e/e2e_test.go
  tests/fixture/e2e/flags.go
  tests/fixture/e2e/helpers.go
  tests/fixture/tmpnet/README.md
  tests/fixture/tmpnet/cmd/main.go
  tests/fixture/tmpnet/network.go
  tests/fixture/tmpnet/network_test.go
  tests/fixture/tmpnet/node.go
  tests/upgrade/upgrade_test.go
Labels: testing

#3035 Enable gossiping of newer IPs when connected to an older IP
  network/README.md
  network/ip_tracker.go
  network/ip_tracker_test.go
Labels: networking

#3037 Fix ACP links
  RELEASES.md
  utils/constants/acps.go
Labels: cleanup

#3031 Prevent unnecessary bandwidth from activated ACPs
  config/config.go
  utils/constants/acps.go
Labels: cleanup

#3042 [antithesis] Ensure node image is pushed
  scripts/build_antithesis_images.sh
Labels: ci

#3043 Cleanup fee config passing
  node/node.go
Labels: cleanup

#3044 Fix typo fix
  snow/README.md
Labels: documentation

#3045 Grab iterator at previously executed height
  snow/engine/snowman/bootstrap/interval/state.go
  snow/engine/snowman/bootstrap/storage.go
Labels: consensus, storage

#3052 Remove optional gatherer
  api/metrics/multi_gatherer_test.go
  api/metrics/optional_gatherer.go
  api/metrics/optional_gatherer_test.go
  chains/linearizable_vm.go
  chains/manager.go
  go.mod
  go.sum
  snow/context.go
  snow/snowtest/snowtest.go
  vms/avm/vm.go
  vms/metervm/block_vm.go
  vms/metervm/vertex_vm.go
  vms/platformvm/vm.go
  vms/proposervm/vm.go
  vms/rpcchainvm/vm_client.go
  vms/rpcchainvm/vm_server.go
Labels: monitoring, cleanup

#3054 [vms/platformvm] Return the correct owner in `platform.GetSubnets` after transfer
  vms/platformvm/service.go
  vms/platformvm/service_test.go
Labels: bug

#3057 Add metrics client
  api/metrics/client.go
  go.mod
  tests/e2e/x/transfer/virtuous.go
  tests/http.go
Labels: testing, monitoring

#3055 [vms/platformvm] Replace `GetSubnets` with `GetSubnetIDs` in `State`
  vms/platformvm/service.go
  vms/platformvm/state/diff.go
  vms/platformvm/state/diff_test.go
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
  vms/platformvm/txs/executor/standard_tx_executor.go
  vms/platformvm/vm.go
  vms/platformvm/vm_test.go
Labels: cleanup

#3058 Implement `constants.VMName`
  tests/fixture/subnet/xsvm.go
  utils/constants/vm_ids.go
  vms/example/xsvm/cmd/chain/create/cmd.go
  vms/example/xsvm/cmd/version/cmd.go
  vms/example/xsvm/constants.go
  vms/example/xsvm/vm.go
  wallet/subnet/primary/examples/create-chain/main.go
Labels: monitoring

#3063 [testing] Remove superfluous gomega dep
  go.mod
  tests/e2e/e2e_test.go
  tests/upgrade/upgrade_test.go
Labels: testing

#3059 [antithesis] Enable workload instrumentation
  go.mod
  go.sum
  scripts/build_antithesis_images.sh
  scripts/build_test.sh
  tests/antithesis/README.md
  tests/antithesis/avalanchego/Dockerfile.builder-instrumented
  tests/antithesis/avalanchego/Dockerfile.builder-uninstrumented
  tests/antithesis/avalanchego/Dockerfile.node
  tests/antithesis/avalanchego/Dockerfile.workload
  tests/antithesis/avalanchego/main.go
  tests/antithesis/xsvm/Dockerfile.node
  tests/antithesis/xsvm/Dockerfile.workload
  tests/antithesis/xsvm/main.go
Labels: testing

#3061 Add pebbledb to docs
  config/config.md
  config/flags.go
  database/pebbledb/batch.go
  database/pebbledb/batch_test.go
  database/pebbledb/db.go
  database/pebbledb/db_test.go
  database/pebbledb/iterator.go
  node/node.go
Labels: documentation, cleanup

#3069 [ci] Remove perpetually failing govulncheck job
  .github/workflows/ci.yml
Labels: ci

#3066 Remove api namespace
  api/metrics/multi_gatherer.go
  api/server/metrics.go
  api/server/server.go
  node/node.go
  utils/metric/namespace.go
Labels: monitoring

#3062 Remove unused metrics namespaces
  chains/manager.go
  snow/consensus/snowman/metrics.go
  snow/consensus/snowman/poll/set.go
  snow/consensus/snowman/poll/set_test.go
  snow/consensus/snowman/topological.go
  snow/engine/avalanche/bootstrap/bootstrapper.go
  snow/engine/avalanche/bootstrap/metrics.go
  snow/engine/avalanche/getter/getter.go
  snow/engine/common/tracker/peers.go
  snow/engine/snowman/bootstrap/bootstrapper.go
  snow/engine/snowman/bootstrap/metrics.go
  snow/engine/snowman/getter/getter.go
  snow/engine/snowman/metrics.go
  snow/engine/snowman/transitive.go
  snow/engine/snowman/transitive_test.go
  snow/networking/sender/sender.go
  utils/metric/api_interceptor.go
  vms/avm/block/builder/builder_test.go
  vms/avm/metrics/metrics.go
  vms/avm/metrics/tx_metrics.go
  vms/avm/vm.go
  vms/metervm/block_metrics.go
  vms/metervm/block_vm.go
  vms/metervm/metrics.go
  vms/metervm/vertex_metrics.go
  vms/metervm/vertex_vm.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/metrics/block_metrics.go
  vms/platformvm/metrics/metrics.go
  vms/platformvm/metrics/tx_metrics.go
  vms/platformvm/validators/manager_benchmark_test.go
  vms/platformvm/vm.go
Labels: monitoring, cleanup

#3065 Only compact after executing a large number of blocks
  snow/engine/snowman/bootstrap/storage.go
Labels: storage

#3068 Remove db namespace
  database/leveldb/db.go
  database/leveldb/db_test.go
  database/leveldb/metrics.go
  database/pebbledb/batch_test.go
  database/pebbledb/db.go
  database/pebbledb/db_test.go
  node/node.go
  vms/platformvm/validators/manager_benchmark_test.go
Labels: monitoring

#3072 Remove averager metrics namespace
  network/throttling/bandwidth_throttler.go
  network/throttling/inbound_msg_buffer_throttler.go
  network/throttling/inbound_msg_byte_throttler.go
  snow/consensus/snowman/metrics.go
  snow/consensus/snowman/poll/set.go
  snow/engine/avalanche/getter/getter.go
  snow/engine/snowman/getter/getter.go
  snow/engine/snowman/metrics.go
  utils/metric/averager.go
  vms/metervm/metrics.go
Labels: monitoring
