Repository ava-labs/avalanchego, pull requests merged in 2024-12, with the labels that each got.

#3575 Remove observedSubnetUptime from Info Docs
  api/info/service.md
Labels: documentation

#3596 fix: feeState API call in docs
  vms/platformvm/service.md
Labels: documentation

#3599 Format Service.MD
  api/info/service.md
Labels: documentation

#3604 Verify tx gas isn't too large in VerifyTx
  vms/platformvm/block/executor/manager.go
Labels: incident response

#3605 Improve block building and verification logging
  vms/components/gas/state.go
  vms/platformvm/block/builder/builder.go
  vms/platformvm/block/executor/verifier.go
  vms/platformvm/network/gossip.go
Labels: monitoring

#3618 [testing] Always use the go.mod version of ginkgo
  scripts/ginkgo.sh
  scripts/tests.e2e.bootstrap_monitor.sh
  scripts/tests.e2e.existing.sh
  scripts/tests.e2e.sh
  scripts/tests.upgrade.sh
  tests/e2e/README.md
Labels: testing

#3614 Update e2e tests and CI jobs for post-etna
  .github/workflows/ci.yml
  tests/e2e/e2e_test.go
  tests/e2e/etna/suites.go
  tests/e2e/p/elastic_subnets.go
  tests/e2e/p/l1.go
  tests/fixture/e2e/flags.go
Labels: testing

#3617 [testing] Update golangci-lint to latest version
  .golangci.yml
  chains/atomic/gsharedmemory/shared_memory_client.go
  config/node/process_context_test.go
  genesis/genesis.go
  go.mod
  message/inbound_msg_builder.go
  message/inbound_msg_builder_test.go
  network/network_test.go
  node/beacon_manager_test.go
  scripts/lint.sh
  snow/engine/avalanche/bootstrap/queue/state.go
  snow/engine/snowman/voter.go
  tests/fixture/bootstrapmonitor/cmd/main.go
  tests/fixture/tmpnet/cmd/main.go
  utils/bimap/bimap_test.go
  utils/formatting/encoding_test.go
  utils/hashing/hashing.go
  utils/json/float32_test.go
  utils/set/sampleable_set_test.go
  utils/set/set_test.go
  vms/avm/index_test.go
  vms/avm/service_test.go
  vms/avm/state/state.go
  vms/avm/utxo/spender.go
  vms/platformvm/block/serialization_test.go
  vms/platformvm/service_test.go
  vms/platformvm/state/state.go
  vms/platformvm/txs/add_permissionless_delegator_tx_test.go
  vms/platformvm/txs/base_tx_test.go
  vms/platformvm/txs/convert_subnet_to_l1_tx_test.go
  vms/platformvm/txs/disable_l1_validator_tx_test.go
  vms/platformvm/txs/increase_l1_validator_balance_tx_test.go
  vms/platformvm/txs/register_l1_validator_tx_test.go
  vms/platformvm/txs/remove_subnet_validator_tx_test.go
  vms/platformvm/txs/set_l1_validator_weight_tx_test.go
  vms/platformvm/txs/transfer_subnet_ownership_tx_test.go
  vms/platformvm/txs/transform_subnet_tx_test.go
  vms/secp256k1fx/output_owners_test.go
  vms/types/blob_data_test.go
  x/merkledb/key_test.go
  x/merkledb/proof.go
Labels: testing
