Repository ava-labs/avalanchego, pull requests merged in 2024-04, with the labels that each got.

#2893 Remove memory alloc from encodeDBNode
  x/merkledb/codec.go
  x/merkledb/codec_test.go
Labels: testing, merkledb

#2855 Interval tree syncing integration
  chains/manager.go
  snow/engine/snowman/bootstrap/acceptor.go
  snow/engine/snowman/bootstrap/block_job.go
  snow/engine/snowman/bootstrap/bootstrapper.go
  snow/engine/snowman/bootstrap/bootstrapper_test.go
  snow/engine/snowman/bootstrap/config.go
  snow/engine/snowman/bootstrap/metrics.go
  snow/engine/snowman/bootstrap/storage.go
  snow/engine/snowman/bootstrap/storage_test.go
  vms/platformvm/vm_test.go
Labels: consensus

#2894 Optimize hashing of leaf nodes
  x/merkledb/codec.go
Labels: merkledb

#2895 Improve performance of marshalling small keys
  x/merkledb/codec.go
  x/merkledb/codec_test.go
Labels: merkledb

#2897 Improve tracing of merkledb trie updates
  x/merkledb/db.go
  x/merkledb/history.go
  x/merkledb/trie_test.go
  x/merkledb/view.go
Labels: monitoring, cleanup

#2896 Remove usage of bytes.Buffer and bytes.Reader
  x/merkledb/codec.go
  x/merkledb/codec_test.go
Labels: merkledb

#2899 Optimize key creation in hashing
  x/merkledb/view.go
  x/merkledb/view_test.go
Labels: merkledb

#2856 Move bootstrapping queue out of common
  chains/manager.go
  snow/engine/avalanche/bootstrap/bootstrapper_test.go
  snow/engine/avalanche/bootstrap/config.go
  snow/engine/avalanche/bootstrap/queue/job.go
  snow/engine/avalanche/bootstrap/queue/jobs.go
  snow/engine/avalanche/bootstrap/queue/jobs_test.go
  snow/engine/avalanche/bootstrap/queue/parser.go
  snow/engine/avalanche/bootstrap/queue/state.go
  snow/engine/avalanche/bootstrap/queue/test_job.go
  snow/engine/avalanche/bootstrap/queue/test_parser.go
  snow/engine/avalanche/bootstrap/tx_job.go
  snow/engine/avalanche/bootstrap/vertex_job.go
Labels: cleanup

#2902 Reuse key buffers during hashing
  x/merkledb/bytes_pool.go
  x/merkledb/bytes_pool_test.go
  x/merkledb/db.go
  x/merkledb/view.go
Labels: merkledb

#2887 Remove AddEphemeralNode
  tests/fixture/e2e/helpers.go
  tests/fixture/tmpnet/network.go
  tests/fixture/tmpnet/node.go
Labels: ci, cleanup

#2907 Rename linkedhashmap package to `linked`
  cache/lru_cache.go
  cache/lru_sized_cache.go
  network/throttling/inbound_msg_byte_throttler.go
  snow/consensus/snowman/metrics.go
  snow/consensus/snowman/poll/set.go
  snow/networking/router/chain_router.go
  snow/networking/tracker/resource_tracker.go
  utils/linked/hashmap.go
  utils/linked/hashmap_test.go
  utils/linkedhashmap/iterator.go
  utils/linkedhashmap/linkedhashmap.go
  vms/avm/environment_test.go
  vms/avm/txs/mempool/mempool.go
  vms/avm/vm.go
  vms/avm/wallet_service.go
  vms/example/xsvm/builder/builder.go
  vms/platformvm/txs/mempool/mempool.go
  x/merkledb/cache.go
Labels: cleanup

#2903 [tmpnet] Misc cleanup to support xsvm warp test PR
  tests/fixture/tmpnet/flags.go
  tests/fixture/tmpnet/network.go
  tests/fixture/tmpnet/network_config.go
  tests/fixture/tmpnet/node.go
  tests/fixture/tmpnet/subnet.go
  tests/fixture/tmpnet/utils.go
Labels: testing

#2912 Remove full message from error logs
  snow/networking/handler/handler.go
Labels: monitoring, cleanup

#2911 Remove `linked.Hashmap` locking
  network/throttling/inbound_msg_byte_throttler_test.go
  snow/networking/router/chain_router_test.go
  utils/linked/hashmap.go
  vms/avm/txs/mempool/mempool.go
  vms/platformvm/txs/mempool/mempool.go
Labels: cleanup

#2915 Remove cancellation for Send*AppRequest messages
  network/p2p/client.go
  network/p2p/network_test.go
  snow/engine/common/sender.go
  x/sync/network_client.go
Labels: bug

#2919 Fix comment and remove unneeded allocation
  x/merkledb/cache.go
Labels: cleanup, merkledb

#2920 Implement `utils.BytesPool` to replace `sync.Pool` for byte slices
  database/prefixdb/db.go
  utils/bytes.go
  utils/bytes_test.go
  x/merkledb/db.go
  x/merkledb/intermediate_node_db.go
  x/merkledb/intermediate_node_db_test.go
  x/merkledb/value_node_db.go
  x/merkledb/value_node_db_test.go
Labels: merkledb

#2921 Refactor `MerkleDB.commitChanges`
  x/merkledb/db.go
  x/merkledb/view.go
Labels: cleanup, merkledb

#2922 Remove value_node_db batch
  x/merkledb/db.go
  x/merkledb/db_test.go
  x/merkledb/value_node_db.go
  x/merkledb/value_node_db_test.go
Labels: cleanup, merkledb

#2925 Remove memory allocations from merkledb iteration
  x/merkledb/db_test.go
  x/merkledb/value_node_db.go
Labels: cleanup, merkledb

#2926 Remove duplicate metrics increment
  x/merkledb/intermediate_node_db.go
Labels: monitoring, cleanup, merkledb

#2927 Optimize merkledb metrics
  x/merkledb/db.go
  x/merkledb/db_test.go
  x/merkledb/intermediate_node_db.go
  x/merkledb/metrics.go
  x/merkledb/metrics_test.go
  x/merkledb/node.go
  x/merkledb/value_node_db.go
Labels: monitoring, cleanup, merkledb

#2928 Optimize intermediateNodeDB.constructDBKey
  x/merkledb/intermediate_node_db.go
  x/merkledb/intermediate_node_db_test.go
Labels: merkledb

#2929 [vms/proposervm] Remove `getForkHeight()`
  vms/proposervm/pre_fork_block.go
  vms/proposervm/vm.go
Labels: cleanup

#2933 Improve logging of startup and errors in bootstrapping
  snow/engine/snowman/bootstrap/bootstrapper.go
  snow/engine/snowman/bootstrap/storage.go
  snow/engine/snowman/transitive.go
Labels: monitoring, antithesis

#2930 Add hashing interface to merkledb
  x/merkledb/codec.go
  x/merkledb/codec_test.go
  x/merkledb/db.go
  x/merkledb/db_test.go
  x/merkledb/hashing.go
  x/merkledb/hashing_test.go
  x/merkledb/history_test.go
  x/merkledb/intermediate_node_db.go
  x/merkledb/intermediate_node_db_test.go
  x/merkledb/node.go
  x/merkledb/node_test.go
  x/merkledb/proof.go
  x/merkledb/proof_test.go
  x/merkledb/trie_test.go
  x/merkledb/value_node_db.go
  x/merkledb/value_node_db_test.go
  x/merkledb/view.go
  x/sync/client.go
Labels: merkledb

#2932 Assign instead of append to `keys` slice
  x/merkledb/codec.go
  x/merkledb/hashing.go
Labels: storage, merkledb

#2936 Remove uptimes from Pong messages
  message/messages_test.go
  message/mock_outbound_message_builder.go
  message/outbound_msg_builder.go
  network/peer/peer.go
  proto/p2p/p2p.proto
  proto/pb/p2p/p2p.pb.go
Labels: networking, cleanup

#2914 Enable creation of multi-arch docker images
  .github/workflows/ci.yml
  .github/workflows/publish_docker_image.yml
  .github/workflows/publish_image.sh
  Dockerfile
  scripts/build_image.sh
  scripts/constants.sh
  scripts/tests.build_image.sh
Labels: ci

#2937 Improve networking README
  network/README.md
Labels: documentation, networking

#2943 Include consensus decisions into logs
  tests/antithesis/docker-compose.yml
Labels: testing, monitoring, antithesis

#2944 Remove unused `validators.Manager` mock
  scripts/mocks.mockgen.source.txt
  snow/validators/mock_manager.go
Labels: cleanup

#2940 Split ManuallyTrack into ManuallyTrack and ManuallyGossip
  network/ip_tracker.go
  network/ip_tracker_test.go
  network/network.go
Labels: networking

#2752 Sync primary network checkpoints during bootstrapping
  genesis/checkpoints.go
  genesis/checkpoints.json
  genesis/generate/checkpoints/main.go
  genesis/generate/validators/main.go
  genesis/validators.go
  genesis/validators.json
  network/ip_tracker.go
  network/ip_tracker_test.go
  network/network.go
  snow/engine/snowman/bootstrap/bootstrapper.go
Labels: consensus, networking

#2948 [ci] Add govulncheck job and update x/net as per its recommendation
  .github/workflows/ci.yml
  go.mod
  go.sum
Labels: dependencies, ci

#2935 [tmpnet] Add network reuse to e2e fixture
  scripts/tests.e2e.existing.sh
  tests/e2e/README.md
  tests/fixture/e2e/env.go
  tests/fixture/e2e/flags.go
  tests/fixture/e2e/helpers.go
  tests/fixture/tmpnet/README.md
  tests/fixture/tmpnet/network.go
  tests/upgrade/upgrade_test.go
Labels: testing

#2043 `e2e`: Add basic warp test with xsvm
  scripts/tests.e2e.existing.sh
  scripts/tests.e2e.sh
  tests/e2e/e2e_test.go
  tests/e2e/vms/xsvm.go
  tests/fixture/tmpnet/defaults.go
  vms/example/xsvm/api/client.go
  vms/example/xsvm/cmd/issue/export/cmd.go
  vms/example/xsvm/cmd/issue/importtx/cmd.go
  vms/example/xsvm/cmd/issue/status/status.go
  vms/example/xsvm/cmd/issue/transfer/cmd.go
  vms/proposervm/block.go
  vms/proposervm/pre_fork_block.go
  wallet/subnet/primary/examples/create-chain/main.go
Labels: testing, warp, lifecycle/frozen, e2e-subnets

#2946 Improve bootstrapping peer selection
  chains/manager.go
  snow/engine/common/tracker/peers.go
  snow/engine/common/tracker/peers_test.go
  snow/engine/snowman/bootstrap/bootstrapper.go
  snow/engine/snowman/bootstrap/bootstrapper_test.go
  snow/engine/snowman/bootstrap/config.go
  snow/networking/handler/handler.go
  snow/networking/handler/handler_test.go
  snow/networking/handler/health_test.go
  snow/networking/router/chain_router_test.go
  snow/networking/sender/sender.go
  snow/networking/sender/sender_test.go
  vms/platformvm/vm_test.go
Labels: consensus, networking

#2947 Cleanup avalanche bootstrapping fetching
  chains/manager.go
  snow/engine/avalanche/bootstrap/bootstrapper.go
  snow/engine/avalanche/bootstrap/bootstrapper_test.go
  snow/engine/avalanche/bootstrap/config.go
  snow/engine/snowman/bootstrap/bootstrapper.go
Labels: consensus, networking

#2950 Add manager validator set callbacks
  chains/manager.go
  network/network.go
  node/overridden_manager.go
  snow/engine/avalanche/bootstrap/bootstrapper_test.go
  snow/engine/snowman/bootstrap/bootstrapper_test.go
  snow/engine/snowman/syncer/state_syncer_test.go
  snow/engine/snowman/transitive.go
  snow/engine/snowman/transitive_test.go
  snow/networking/handler/health_test.go
  snow/validators/manager.go
  snow/validators/manager_test.go
  snow/validators/set.go
  snow/validators/set_test.go
  vms/platformvm/vm.go
  vms/platformvm/vm_test.go
Labels: consensus

#2957 chore: fix function names in comment
  api/admin/service.go
  config/config.go
  database/test_database.go
Labels: documentation, cleanup

#2959 [ci] Fix conditional guarding monitoring configuration
  .github/workflows/ci.yml
Labels: ci

#2953 Cleanup consensus engine tests
  snow/engine/snowman/transitive_test.go
Labels: consensus, testing

#2956 Improve and test getProcessingAncestor
  snow/engine/snowman/metrics.go
  snow/engine/snowman/transitive.go
  snow/engine/snowman/transitive_test.go
  snow/engine/snowman/voter.go
Labels: consensus, testing

#2965 Exit topological sort earlier
  snow/consensus/snowman/consensus_test.go
  snow/consensus/snowman/topological.go
Labels: consensus

#2949 Consolidate beta
  config/config.go
  config/config.md
  config/flags.go
  config/keys.go
  snow/consensus/snowball/consensus.go
  snow/consensus/snowball/consensus_performance_test.go
  snow/consensus/snowball/factory.go
  snow/consensus/snowball/flat_test.go
  snow/consensus/snowball/nnary_snowball.go
  snow/consensus/snowball/nnary_snowball_test.go
  snow/consensus/snowball/nnary_snowflake.go
  snow/consensus/snowball/nnary_snowflake_test.go
  snow/consensus/snowball/parameters.go
  snow/consensus/snowball/parameters_test.go
  snow/consensus/snowball/tree.go
  snow/consensus/snowball/tree_test.go
  snow/consensus/snowball/unary_snowball.go
  snow/consensus/snowball/unary_snowball_test.go
  snow/consensus/snowball/unary_snowflake.go
  snow/consensus/snowball/unary_snowflake_test.go
  snow/consensus/snowman/consensus_test.go
  snow/engine/snowman/config_test.go
  snow/engine/snowman/transitive_test.go
  subnets/config.md
  subnets/config_test.go
  vms/platformvm/vm_test.go
Labels: consensus, cleanup

#2968 Abandon decided blocks
  snow/engine/snowman/transitive.go
  snow/engine/snowman/transitive_test.go
Labels: consensus

#2973 Cleanup test block creation
  scripts/mocks.mockgen.txt
  snow/choices/test_decidable.go
  snow/consensus/snowman/consensus_test.go
  snow/consensus/snowman/network_test.go
  snow/consensus/snowman/snowmantest/block.go
  snow/consensus/snowman/snowmantest/mock_block.go
  snow/consensus/snowman/test_block.go
  snow/engine/snowman/bootstrap/bootstrapper_test.go
  snow/engine/snowman/bootstrap/storage_test.go
  snow/engine/snowman/getter/getter_test.go
  snow/engine/snowman/transitive_test.go
  vms/components/chain/state_test.go
  vms/proposervm/batched_vm_test.go
  vms/proposervm/block_test.go
  vms/proposervm/post_fork_block_test.go
  vms/proposervm/post_fork_option_test.go
  vms/proposervm/pre_fork_block_test.go
  vms/proposervm/state_syncable_vm_test.go
  vms/proposervm/tree/tree_test.go
  vms/proposervm/vm_byzantine_test.go
  vms/proposervm/vm_test.go
  vms/rpcchainvm/batched_vm_test.go
  vms/rpcchainvm/state_syncable_vm_test.go
  vms/rpcchainvm/with_context_vm_test.go
Labels: testing

#2971 Update version for v1.11.5
  RELEASES.md
  go.mod
  go.sum
  version/compatibility.json
  version/constants.go
Labels: dependencies
