Repository ava-labs/avalanchego, pull requests merged in 2024-02, with the labels that each got.

#2690 Cleanup ID initialization
  ids/id.go
  version/constants.go
  vms/proposervm/vm.go
Labels: cleanup

#2692 Remove unused chains#beacons field
  chains/manager.go
Labels: cleanup

#2694 x/sync: Remove duplicated call to TrackBandwidth
  x/sync/network_client.go
  x/sync/response_handler.go
Labels: cleanup

#2689 Move VMAliaser into node from config
  config/config.go
  genesis/aliases.go
  node/config.go
  node/node.go
Labels: cleanup

#2709 Fix minor errors in x/sync tests
  x/sync/sync_test.go
Labels: testing

#2715 Check for github action updates in dependabot
  .github/dependabot.yml
Labels: dependencies

#2712 Add stringer to warp types
  vms/platformvm/warp/message.go
  vms/platformvm/warp/signature.go
  vms/platformvm/warp/unsigned_message.go
Labels: monitoring

#2701 Refactor `p2p.PeerTracker`
  network/p2p/peer_tracker.go
  network/p2p/peer_tracker_test.go
  x/sync/client.go
  x/sync/client_test.go
  x/sync/mock_network_client.go
  x/sync/network_client.go
Labels: networking

#2725 Manually setup golang in codeql action
  .github/workflows/codeql-analysis.yml
Labels: ci

#2724 Provide pgo file during compilation
  main/default.pgo
Labels: ci

#2718 P-chain - Tx builder cleanup
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/builder/standard_block_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/block/executor/standard_block_test.go
  vms/platformvm/service.go
  vms/platformvm/service_test.go
  vms/platformvm/txs/builder/builder.go
  vms/platformvm/txs/executor/advance_time_test.go
  vms/platformvm/txs/executor/create_chain_test.go
  vms/platformvm/txs/executor/export_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/txs/executor/import_test.go
  vms/platformvm/txs/executor/proposal_tx_executor_test.go
  vms/platformvm/txs/executor/reward_validator_test.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
Labels: testing

#2711 Refactor chain manager subnets
  chains/manager.go
  chains/subnets.go
  chains/subnets_test.go
  node/node.go
Labels: cleanup

#2717 Replace snowball/snowflake interface with single shared snow interface
  snow/consensus/snowball/binary_slush.go
  snow/consensus/snowball/binary_snowball.go
  snow/consensus/snowball/binary_snowflake.go
  snow/consensus/snowball/consensus.go
  snow/consensus/snowball/consensus_performance_test.go
  snow/consensus/snowball/consensus_reversibility_test.go
  snow/consensus/snowball/consensus_test.go
  snow/consensus/snowball/factory.go
  snow/consensus/snowball/flat.go
  snow/consensus/snowball/flat_test.go
  snow/consensus/snowball/network_test.go
  snow/consensus/snowball/nnary_slush.go
  snow/consensus/snowball/nnary_snowball.go
  snow/consensus/snowball/nnary_snowflake.go
  snow/consensus/snowball/tree.go
  snow/consensus/snowball/tree_test.go
  snow/consensus/snowball/unary_snowball.go
  snow/consensus/snowball/unary_snowflake.go
  snow/consensus/snowman/snowman_block.go
Labels: consensus, cleanup

#2733 Remove duplicate IP length constant
  network/peer/ip.go
  utils/ips/ip_port.go
  utils/wrappers/packing.go
Labels: cleanup

#2730 Provide BLS signature in Handshake message
  message/messages_benchmark_test.go
  message/messages_test.go
  message/mock_outbound_message_builder.go
  message/outbound_msg_builder.go
  network/config.go
  network/network.go
  network/network_test.go
  network/peer/ip.go
  network/peer/ip_signer.go
  network/peer/ip_signer_test.go
  network/peer/ip_test.go
  network/peer/peer.go
  network/peer/peer_test.go
  network/peer/test_peer.go
  network/test_network.go
  node/node.go
  proto/p2p/p2p.proto
  proto/pb/p2p/p2p.pb.go
Labels: networking, Durango

#2735 Verify BLS signature provided in Handshake messages
  network/network.go
  network/peer/config.go
  network/peer/peer.go
  network/peer/peer_test.go
  network/peer/test_peer.go
Labels: networking, Durango

#2739 P chain wallet u ts suggestions
  scripts/mocks.mockgen.txt
  wallet/chain/p/builder_test.go
  wallet/chain/p/mocks/mock_signer_backend.go
Labels: cleanup

#2741 Move UTXOs definition from primary to primary/common
  wallet/subnet/primary/api.go
  wallet/subnet/primary/common/utxos.go
  wallet/subnet/primary/examples/get-p-chain-balance/main.go
  wallet/subnet/primary/examples/get-x-chain-balance/main.go
  wallet/subnet/primary/utxos.go
  wallet/subnet/primary/wallet.go
Labels: cleanup

#2740 Minimize Signer interface and document Sign
  wallet/chain/c/signer.go
  wallet/chain/c/wallet.go
  wallet/chain/p/signer.go
  wallet/chain/p/wallet.go
  wallet/chain/x/signer.go
  wallet/chain/x/wallet.go
Labels: documentation, cleanup

#2744 Revert setup-go during unit tests
  .github/workflows/ci.yml
Labels: ci

#2734 P-chain wallet fees UTs
  wallet/chain/p/builder_test.go
Labels: testing

#2737 Add AppError to Sender interface
  message/mock_outbound_message_builder.go
  message/ops.go
  message/outbound_msg_builder.go
  proto/appsender/appsender.proto
  proto/pb/appsender/appsender.pb.go
  proto/pb/appsender/appsender_grpc.pb.go
  snow/engine/common/appsender/appsender_client.go
  snow/engine/common/appsender/appsender_server.go
  snow/engine/common/mock_sender.go
  snow/engine/common/sender.go
  snow/engine/common/test_sender.go
  snow/networking/sender/sender.go
  snow/networking/sender/traced_sender.go
Labels: networking

#2755 fix test sender
  snow/engine/common/test_sender.go
Labels: bug

#2758 Update version to v1.11.0
  .github/workflows/ci.yml
  RELEASES.md
  config/config.go
  go.mod
  go.sum
  proto/README.md
  utils/constants/acps.go
  version/compatibility.json
  version/constants.go
Labels: Durango

#2760 Remove deprecated IPC API
  api/ipcs/client.go
  api/ipcs/service.go
  config/config.go
  config/flags.go
  config/keys.go
  go.mod
  go.sum
  ipcs/chainipc.go
  ipcs/eventsocket.go
  ipcs/socket/socket.go
  ipcs/socket/socket_test.go
  ipcs/socket/socket_unix.go
  ipcs/socket/socket_windows.go
  node/config.go
  node/node.go
  tests/fixture/tmpnet/defaults.go
Labels: cleanup

#2761 `vms/platformvm`: Remove all keystore APIs except `ExportKey` and `ListAddresses`
  vms/platformvm/client.go
  vms/platformvm/service.go
  vms/platformvm/service_test.go
Labels: cleanup

#2759 Remove Deprecated Auth API
  api/auth/auth.go
  api/auth/auth_test.go
  api/auth/claims.go
  api/auth/response.go
  api/auth/service.go
  api/server/server.go
  api/server/wrapper.go
  config/config.go
  config/flags.go
  config/keys.go
  go.mod
  go.sum
  node/config.go
  node/node.go
Labels: cleanup

#2767 Remove `defaultAddress` helper from platformvm service tests
  vms/platformvm/service_test.go
Labels: testing, cleanup

#2702 [trace] upgrade opentelemetry to v1.22.0
  go.mod
  go.sum
  trace/noop.go
Labels: dependencies

#2769 Reenable the upgrade tests
  .github/workflows/ci.yml
  scripts/tests.upgrade.sh
Labels: testing

#2778 Make metrics more fine-grained
  network/p2p/gossip/gossip.go
Labels: monitoring

#2772 [network/p2p] Redesign Push Gossip
  go.mod
  go.sum
  network/p2p/gossip/gossip.go
  network/p2p/gossip/gossip_test.go
  network/p2p/gossip/gossipable.go
  network/p2p/gossip/handler.go
  network/p2p/gossip/test_gossip.go
  vms/avm/config_test.go
  vms/avm/environment_test.go
  vms/avm/network/config.go
  vms/avm/network/gossip.go
  vms/avm/network/gossip_test.go
  vms/avm/network/network.go
  vms/avm/network/network_test.go
  vms/avm/service.go
  vms/avm/vm.go
  vms/avm/wallet_service.go
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/config/execution_config_test.go
  vms/platformvm/network/config.go
  vms/platformvm/network/gossip.go
  vms/platformvm/network/network.go
  vms/platformvm/network/network_test.go
  vms/platformvm/service.go
  vms/platformvm/service_test.go
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/vm.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
Labels: incident response

#2781 `merkledb` -- rename metrics and add missing call
  x/merkledb/metrics.go
  x/merkledb/view.go
Labels: cleanup

#2780 `merkledb` comment accuracy fixes
  x/merkledb/proof.go
  x/merkledb/trie.go
  x/merkledb/view.go
Labels: storage, cleanup
