Repository ava-labs/avalanchego, pull requests merged in 2024-03, with the labels that each got.

#2798 Cleanup BLS naming and documentation
  snow/validators/gvalidators/validator_state_client.go
  snow/validators/gvalidators/validator_state_server.go
  snow/validators/gvalidators/validator_state_test.go
  snow/validators/logger.go
  tests/fixture/tmpnet/node.go
  utils/crypto/bls/public.go
  utils/crypto/bls/public_test.go
  utils/crypto/bls/secret.go
  vms/platformvm/service.go
  vms/platformvm/signer/proof_of_possession.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/warp/signature_test.go
  vms/platformvm/warp/validator.go
  vms/platformvm/warp/validator_test.go
  vms/rpcchainvm/vm_client.go
  vms/rpcchainvm/vm_server.go
Labels: cleanup

#2794 Add BLS keys + signers config for local network
  genesis/genesis_local.json
  genesis/genesis_test.go
  staking/local/README.md
  staking/local/signer1.key
  staking/local/signer2.key
  staking/local/signer3.key
  staking/local/signer4.key
  staking/local/signer5.key
Labels: enhancement

#2802 Remove double spaces
  nat/upnp.go
  vms/avm/fxs/fx.go
  vms/platformvm/state/state_test.go
  wallet/chain/p/builder_test.go
  wallet/chain/x/builder_test.go
Labels: documentation, cleanup

#2795 [vms/platformvm] Remove `platform.getMaxStakeAmount`
  vms/platformvm/client.go
  vms/platformvm/service.go
Labels: cleanup

#2811 Remove unused engine interface
  chains/manager.go
  snow/engine/snowman/engine.go
  snow/engine/snowman/test_engine.go
  snow/engine/snowman/traced_engine.go
  snow/engine/snowman/transitive.go
Labels: cleanup

#2812 Cleanup Duplicate Transitive Constructor
  chains/manager.go
  snow/engine/snowman/transitive.go
  snow/engine/snowman/transitive_test.go
Labels: consensus

#2814 Update minimum golang version to v1.21.8
  .github/workflows/build-linux-binaries.yml
  .github/workflows/build-macos-release.yml
  .github/workflows/build-public-ami.yml
  .github/workflows/build-ubuntu-amd64-release.yml
  .github/workflows/build-ubuntu-arm64-release.yml
  .github/workflows/build-win-release.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/fuzz.yml
  .github/workflows/fuzz_merkledb.yml
  CONTRIBUTING.md
  Dockerfile
  README.md
  proto/Dockerfile.buf
  scripts/build_avalanche.sh
Labels: dependencies

#2815 Cleanup consensus metrics
  snow/engine/snowman/issuer.go
  snow/engine/snowman/transitive.go
  snow/engine/snowman/voter.go
Labels: monitoring, cleanup

#2731 Use `BaseTx` in P-chain wallet
  wallet/chain/p/builder.go
  wallet/chain/p/builder_test.go
  wallet/chain/p/wallet.go
Labels: cleanup

#2790 Remove put gossip
  chains/manager.go
  chains/subnets_test.go
  config/config.go
  config/config_test.go
  config/flags.go
  config/keys.go
  message/fields.go
  snow/engine/common/mock_sender.go
  snow/engine/common/no_ops_handlers.go
  snow/engine/common/sender.go
  snow/engine/common/test_sender.go
  snow/engine/snowman/metrics.go
  snow/engine/snowman/transitive.go
  snow/engine/snowman/transitive_test.go
  snow/networking/router/chain_router.go
  snow/networking/sender/sender.go
  snow/networking/sender/sender_test.go
  snow/networking/sender/traced_sender.go
  subnets/config.go
  utils/constants/networking.go
  vms/platformvm/vm_test.go
Labels: cleanup

#2817 [vms/platformvm] Remove `GetPendingValidators` API
  vms/platformvm/client.go
  vms/platformvm/service.go
Labels: cleanup

#2797 [vms/platformvm] Remove `ErrFutureStakeTime` check in `VerifyTx`
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/block/executor/manager.go
  vms/platformvm/txs/executor/proposal_tx_executor_test.go
  vms/platformvm/txs/executor/staker_tx_verification.go
  vms/platformvm/txs/executor/staker_tx_verification_test.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
Labels: cleanup

#2823 Remove pre-Durango block building logic and verification
  vms/platformvm/block/builder/builder.go
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/block/executor/verifier.go
Labels: cleanup

#2827 [snow/networking] Enforce `PreferredIDAtHeight` in `Chits` messages
  snow/networking/handler/handler.go
Labels: cleanup

#2836 Combine AppGossip and AppGossipSpecific
  network/network.go
  network/network_test.go
  network/p2p/client.go
  network/p2p/gossip/gossip.go
  network/p2p/network_test.go
  proto/appsender/appsender.proto
  proto/pb/appsender/appsender.pb.go
  proto/pb/appsender/appsender_grpc.pb.go
  snow/engine/common/appsender/appsender_client.go
  snow/engine/common/appsender/appsender_server.go
  snow/engine/common/mock_sender.go
  snow/engine/common/sender.go
  snow/engine/common/test_sender.go
  snow/networking/sender/external_sender.go
  snow/networking/sender/mock_external_sender.go
  snow/networking/sender/sender.go
  snow/networking/sender/sender_test.go
  snow/networking/sender/test_external_sender.go
  snow/networking/sender/traced_sender.go
  vms/avm/network/network_test.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/network/network_test.go
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/vm_test.go
Labels: cleanup

#2830 [network/peer] Disconnect from peers who only send legacy version field
  message/messages_benchmark_test.go
  message/messages_test.go
  message/mock_outbound_message_builder.go
  message/outbound_msg_builder.go
  network/peer/peer.go
  proto/p2p/p2p.proto
  proto/pb/p2p/p2p.pb.go
  version/application.go
  version/application_test.go
  version/compatibility.go
  version/compatibility_test.go
  version/parser.go
  version/parser_test.go
Labels: cleanup

#2826 [vms/avm] Cleanup `GetTx` + remove state pruning logic
  vms/avm/state/mock_state.go
  vms/avm/state/state.go
  vms/avm/vm.go
Labels: cleanup

#2834 [vms/avm] Remove `snow.Context` from `Network`
  vms/avm/network/network.go
  vms/avm/network/network_test.go
  vms/avm/vm.go
Labels: cleanup

#2825 [vms/platformvm] Remove state pruning logic
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
  vms/platformvm/vm.go
Labels: cleanup

#2839 [utils/compression] Remove gzip compressor
  config/config.go
  message/messages.go
  proto/p2p/p2p.proto
  proto/pb/p2p/p2p.pb.go
  utils/compression/compressor_test.go
  utils/compression/gzip_compressor.go
  utils/compression/gzip_zip_bomb.bin
  utils/compression/no_compressor.go
  utils/compression/type.go
  utils/compression/type_test.go
  utils/compression/zstd_compressor.go
Labels: cleanup

#2833 Remove legacy p2p message handling
  proto/message/tx.proto
  proto/pb/message/tx.pb.go
  vms/avm/network/network.go
  vms/avm/network/network_test.go
  vms/components/message/codec.go
  vms/components/message/handler.go
  vms/components/message/handler_test.go
  vms/components/message/message.go
  vms/components/message/message_test.go
  vms/components/message/tx.go
  vms/components/message/tx_test.go
  vms/platformvm/network/network.go
  vms/platformvm/network/network_test.go
Labels: cleanup

#2831 Remove Pre-Durango TLS certificate parsing logic
  chains/manager.go
  indexer/examples/p-chain/main.go
  indexer/examples/x-chain-blocks/main.go
  network/certs_test.go
  network/network.go
  network/network_test.go
  network/peer/ip_test.go
  network/peer/peer.go
  network/peer/peer_test.go
  network/peer/test_peer.go
  network/peer/upgrader.go
  node/node.go
  staking/asn1.go
  staking/certificate.go
  staking/parse.go
  staking/parse_test.go
  staking/verify.go
  tests/fixture/tmpnet/node.go
  vms/proposervm/batched_vm.go
  vms/proposervm/block/block.go
  vms/proposervm/block/build.go
  vms/proposervm/block/build_test.go
  vms/proposervm/block/option.go
  vms/proposervm/block/parse.go
  vms/proposervm/block/parse_test.go
  vms/proposervm/state/block_state.go
  vms/proposervm/state/block_state_test.go
  vms/proposervm/vm.go
  vms/proposervm/vm_test.go
Labels: cleanup

#2800 Remove engine type handling for everything other than GetAncestors
  message/fields.go
  message/inbound_msg_builder.go
  message/inbound_msg_builder_test.go
  message/internal_msg_builder.go
  message/messages_test.go
  message/mock_outbound_message_builder.go
  message/outbound_msg_builder.go
  network/network_test.go
  network/peer/peer_test.go
  proto/p2p/p2p.proto
  proto/pb/p2p/p2p.pb.go
  snow/engine/avalanche/getter/getter.go
  snow/engine/avalanche/getter/getter_test.go
  snow/networking/handler/handler_test.go
  snow/networking/handler/message_queue_test.go
  snow/networking/router/chain_router_test.go
  snow/networking/sender/sender.go
  snow/networking/sender/sender_test.go
Labels: cleanup

#2808 P-chain: Improve GetValidatorsSet error expressivity
  vms/platformvm/validators/manager.go
  vms/platformvm/warp/validator.go
Labels: monitoring, antithesis

#2796 Add antithesis PoC workload
  tests/antithesis/config.go
  tests/antithesis/main.go
Labels: testing

#2838 Add Antithesis docker compose file
  tests/antithesis/docker-compose.yml
Labels: testing

#2763 `tmpnet`: Add a UUID to temporary networks to support metrics collection
  .github/workflows/ci.yml
  go.mod
  tests/e2e/README.md
  tests/e2e/c/dynamic_fees.go
  tests/e2e/e2e_test.go
  tests/fixture/e2e/env.go
  tests/fixture/e2e/helpers.go
  tests/fixture/tmpnet/README.md
  tests/fixture/tmpnet/cmd/main.go
  tests/fixture/tmpnet/network.go
  tests/fixture/tmpnet/network_config.go
  tests/upgrade/upgrade_test.go
Labels: testing

#2634 Remove verify height index
  proto/pb/vm/vm.pb.go
  proto/pb/vm/vm_grpc.pb.go
  proto/vm/vm.proto
  snow/engine/avalanche/vertex/mock_vm.go
  snow/engine/snowman/block/mock_chain_vm.go
  snow/engine/snowman/block/test_vm.go
  snow/engine/snowman/block/vm.go
  vms/avm/vm.go
  vms/example/xsvm/vm.go
  vms/metervm/block_metrics.go
  vms/metervm/block_vm.go
  vms/platformvm/vm.go
  vms/proposervm/batched_vm_test.go
  vms/proposervm/block_server.go
  vms/proposervm/height_indexed_vm.go
  vms/proposervm/indexer/block_server.go
  vms/proposervm/indexer/block_server_test.go
  vms/proposervm/indexer/height_indexer.go
  vms/proposervm/indexer/height_indexer_test.go
  vms/proposervm/state/block_height_index.go
  vms/proposervm/state/mock_state.go
  vms/proposervm/state_syncable_vm.go
  vms/proposervm/state_syncable_vm_test.go
  vms/proposervm/vm.go
  vms/proposervm/vm_regression_test.go
  vms/proposervm/vm_test.go
  vms/rpcchainvm/errors.go
  vms/rpcchainvm/vm_client.go
  vms/rpcchainvm/vm_server.go
  vms/tracedvm/block_vm.go
Labels: cleanup

#2820 `tmpnet`: Enable collection of logs and metrics
  .github/workflows/ci.yml
  .github/workflows/notify-metrics-availability.sh
  scripts/run_prometheus.sh
  scripts/run_promtail.sh
  tests/fixture/e2e/env.go
  tests/fixture/e2e/flags.go
  tests/fixture/e2e/helpers.go
  tests/fixture/tmpnet/README.md
  tests/fixture/tmpnet/network.go
  tests/fixture/tmpnet/node.go
  tests/fixture/tmpnet/node_config.go
  tests/fixture/tmpnet/node_process.go
  tests/upgrade/upgrade_test.go
Labels: testing, ci

#2801 Remove fallback validator height indexing
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
Labels: cleanup

#2857 `tmpnet`: Reuse dynamically-allocated API port across restarts
  tests/fixture/tmpnet/network.go
  tests/fixture/tmpnet/node.go
Labels: testing

#2858 Remove useless bootstrapping metric
  snow/engine/avalanche/bootstrap/bootstrapper.go
  snow/engine/avalanche/bootstrap/metrics.go
  snow/engine/avalanche/bootstrap/tx_job.go
  snow/engine/avalanche/bootstrap/vertex_job.go
  snow/engine/snowman/bootstrap/block_job.go
  snow/engine/snowman/bootstrap/bootstrapper.go
  snow/engine/snowman/bootstrap/bootstrapper_test.go
  snow/engine/snowman/bootstrap/metrics.go
Labels: consensus, cleanup

#2860 Remove duplicate log
  snow/engine/snowman/bootstrap/bootstrapper.go
Labels: monitoring, cleanup

#2866 Revert removal of legacy P-chain block parsing
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
Labels: incident response

#2861 nits
  vms/platformvm/service.go
  vms/platformvm/service_test.go
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/vm.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
Labels: cleanup

#2859 `tmpnet`: Ensure nodes are properly detached from the parent process
  scripts/build_test.sh
  tests/fixture/tmpnet/defaults.go
  tests/fixture/tmpnet/node_process.go
Labels: testing

#2873 indicies -> indices
  network/ip_tracker.go
  network/ip_tracker_test.go
  vms/platformvm/txs/add_permissionless_delegator_tx_test.go
  vms/platformvm/txs/add_permissionless_validator_tx_test.go
Labels: cleanup

#2845 docs migration
  api/admin/service.md
  api/health/service.md
  api/info/service.md
  api/keystore/service.md
  api/metrics/service.md
  config/config.md
  indexer/service.md
  subnets/config.md
  vms/avm/config.md
  vms/avm/service.md
  vms/platformvm/config/config.md
  vms/platformvm/service.md
Labels: documentation

#2756 Implement interval tree to replace bootstrapping jobs queue
  snow/engine/snowman/bootstrap/interval/blocks.go
  snow/engine/snowman/bootstrap/interval/blocks_test.go
  snow/engine/snowman/bootstrap/interval/interval.go
  snow/engine/snowman/bootstrap/interval/interval_test.go
  snow/engine/snowman/bootstrap/interval/state.go
  snow/engine/snowman/bootstrap/interval/tree.go
  snow/engine/snowman/bootstrap/interval/tree_test.go
  utils/logging/logger.go
Labels: enhancement, consensus, storage

#2699 Cleanup codec constants
  codec/manager.go
  codec/reflectcodec/type_codec.go
  vms/platformvm/state/metadata_validator.go
Labels: cleanup

#2875 Update health API readme
  api/health/service.md
Labels: documentation

#2871 `tmpnet`: Improve subnet configuration
  tests/fixture/tmpnet/README.md
  tests/fixture/tmpnet/network.go
  tests/fixture/tmpnet/subnet.go
Labels: testing

#2878 Add tests for inefficient string formatting
  .golangci.yml
  indexer/examples/p-chain/main.go
  indexer/examples/x-chain-blocks/main.go
  tests/fixture/tmpnet/cmd/main.go
  tests/fixture/tmpnet/network.go
  tests/fixture/tmpnet/subnet.go
  vms/rpcchainvm/vm_test.go
Labels: cleanup

#2881 [vms/platformvm] Declare `maxPageSize` in `service.go`
  vms/platformvm/service.go
Labels: cleanup

#2751 [vms/platformvm] Use `wallet` sdk in `txstest.Builder`
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/builder/standard_block_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/block/executor/standard_block_test.go
  vms/platformvm/service.go
  vms/platformvm/service_test.go
  vms/platformvm/txs/builder/builder.go
  vms/platformvm/txs/executor/advance_time_test.go
  vms/platformvm/txs/executor/create_chain_test.go
  vms/platformvm/txs/executor/create_subnet_test.go
  vms/platformvm/txs/executor/export_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/txs/executor/import_test.go
  vms/platformvm/txs/executor/proposal_tx_executor_test.go
  vms/platformvm/txs/executor/reward_validator_test.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/txs/txstest/backend.go
  vms/platformvm/txs/txstest/builder.go
  vms/platformvm/txs/txstest/context.go
  vms/platformvm/utxo/handler.go
  vms/platformvm/utxo/verifier.go
  vms/platformvm/utxo/verifier_test.go
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/vm.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
  wallet/chain/p/builder/builder.go
Labels: cleanup

#2882 Optimize encodeUint
  x/merkledb/codec.go
  x/merkledb/codec_test.go
Labels: cleanup, merkledb

#2884 [components/avax] Remove `AtomicUTXOManager` interface
  vms/avm/service.go
  vms/avm/vm.go
  vms/components/avax/atomic_utxos.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/service.go
  vms/platformvm/service_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/txs/txstest/backend.go
  vms/platformvm/vm.go
Labels: cleanup

#2883 Remove merkledb codec struct
  x/merkledb/codec.go
  x/merkledb/codec_test.go
  x/merkledb/db.go
  x/merkledb/node.go
Labels: cleanup, merkledb

#2888 [vms/platformvm] Minimize exported functions in `txstest`
  vms/platformvm/txs/executor/create_chain_test.go
  vms/platformvm/txs/executor/create_subnet_test.go
  vms/platformvm/txs/txstest/backend.go
  vms/platformvm/txs/txstest/builder.go
  vms/platformvm/txs/txstest/context.go
Labels: cleanup

#2880 `ci`: Skip monitoring if secrets are not present
  .github/workflows/ci.yml
Labels: ci

#2886 Optimize merkledb hashing
  x/merkledb/codec.go
  x/merkledb/codec_test.go
  x/merkledb/key.go
  x/merkledb/node.go
Labels: merkledb

#2891 [vms/platformvm] Miscellaneous testing cleanups
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/txs/executor/proposal_tx_executor_test.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
Labels: testing, cleanup

#2892 Move functions around so that encode and decode are next to each other
  x/merkledb/codec.go
Labels: cleanup, merkledb
