Repository ava-labs/avalanchego, pull requests merged in 2024-08, with the labels that each got.

#3256 Fix comparison comment in snowflake algorithms
  snow/consensus/snowball/binary_snowflake.go
  snow/consensus/snowball/nnary_snowflake.go
  snow/consensus/snowball/unary_snowflake.go
Labels: documentation, cleanup

#3207 Add network upgrade config
  chains/manager.go
  config/config.go
  config/flags.go
  config/keys.go
  network/network.go
  network/network_test.go
  network/peer/peer_test.go
  network/peer/test_peer.go
  network/test_network.go
  node/config.go
  node/node.go
  snow/engine/avalanche/state/serializer.go
  upgrade/upgrade.go
  upgrade/upgrade_test.go
  version/constants.go
  vms/avm/block/executor/block_test.go
  vms/avm/config/config.go
  vms/avm/environment_test.go
  vms/avm/service_test.go
  vms/avm/state/state_test.go
  vms/avm/txs/executor/syntactic_verifier_test.go
  vms/avm/vm.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/block/executor/verifier_test.go
  vms/platformvm/config/config.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/upgrade/config.go
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
  vms/proposervm/batched_vm_test.go
  vms/proposervm/block.go
  vms/proposervm/block_test.go
  vms/proposervm/config.go
  vms/proposervm/post_fork_option_test.go
  vms/proposervm/pre_fork_block.go
  vms/proposervm/pre_fork_block_test.go
  vms/proposervm/state_syncable_vm_test.go
  vms/proposervm/vm.go
  vms/proposervm/vm_test.go
Labels: acp77, acp103

#3236 [vms/platformvm] Add `VerifyWithContext` to `Block`s
  vms/platformvm/block/executor/block.go
  vms/platformvm/block/executor/block_state.go
  vms/platformvm/block/executor/verifier.go
Labels: acp77

#3259 [ci] Switch to v2 of docker compose plugin
  scripts/tests.build_antithesis_images.sh
  tests/antithesis/README.md
  tests/antithesis/compose.go
Labels: testing, ci

#3126 [vms/platformvm] Add tracking of a Subnet manager
  vms/platformvm/config/execution_config.go
  vms/platformvm/config/execution_config_test.go
  vms/platformvm/state/diff.go
  vms/platformvm/state/diff_test.go
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
Labels: acp77

#3258 Remove trackedSubnet check for explicitly named peers in network.Send()
  network/network.go
Labels: networking, Warp Signature API

#3253 [e2e] Enhance post-test bootstrap checks
  tests/e2e/c/dynamic_fees.go
  tests/e2e/c/interchain_workflow.go
  tests/e2e/p/interchain_workflow.go
  tests/e2e/p/staking_rewards.go
  tests/e2e/p/validator_sets.go
  tests/e2e/vms/xsvm.go
  tests/e2e/x/interchain_workflow.go
  tests/fixture/e2e/helpers.go
  tests/upgrade/upgrade_test.go
Labels: testing

#3254 [e2e] Abstract usage of ginkgo with a new test context
  tests/colors.go
  tests/context_helpers.go
  tests/e2e/banff/suites.go
  tests/e2e/c/dynamic_fees.go
  tests/e2e/c/interchain_workflow.go
  tests/e2e/e2e_test.go
  tests/e2e/faultinjection/duplicate_node_id.go
  tests/e2e/p/interchain_workflow.go
  tests/e2e/p/permissionless_subnets.go
  tests/e2e/p/staking_rewards.go
  tests/e2e/p/validator_sets.go
  tests/e2e/p/workflow.go
  tests/e2e/vms/xsvm.go
  tests/e2e/x/interchain_workflow.go
  tests/e2e/x/transfer/virtuous.go
  tests/fixture/e2e/env.go
  tests/fixture/e2e/ginkgo_test_context.go
  tests/fixture/e2e/helpers.go
  tests/test_context.go
  tests/upgrade/upgrade_test.go
Labels: testing

#3198 [antithesis] Refactor image build for reuse by other repos
  .github/workflows/publish_antithesis_images.yml
  scripts/build_antithesis_images.sh
  scripts/lib_build_antithesis_images.sh
  scripts/lib_test_antithesis_images.sh
  scripts/tests.build_antithesis_images.sh
  tests/antithesis/Dockerfile.builder-instrumented
  tests/antithesis/Dockerfile.builder-uninstrumented
  tests/antithesis/README.md
  tests/antithesis/avalanchego/Dockerfile.node
  tests/antithesis/avalanchego/Dockerfile.workload
  tests/antithesis/xsvm/Dockerfile.node
  tests/antithesis/xsvm/Dockerfile.workload
Labels: testing, ci

#3266 Expose upgrade config in the info API
  api/info/client.go
  api/info/service.go
  node/node.go
  upgrade/upgrade.go
Labels: acp77, acp103

#3264 [antithesis] Ensure references to pushed images are qualified
  scripts/lib_build_antithesis_images.sh
Labels: ci

#3260 refactor: rename `*test.Test*` identifiers
  cache/cachetest/cacher.go
  cache/lru_sized_cache_test.go
  cache/metercacher/cache_test.go
  codec/codectest/codectest.go
  codec/hierarchycodec/codec_test.go
  codec/linearcodec/codec_test.go
  ids/aliases_test.go
  ids/galiasreader/alias_reader_test.go
  ids/idstest/aliases.go
  network/p2p/gossip/gossip_test.go
  network/p2p/network_test.go
  network/p2p/validators_test.go
  snow/engine/avalanche/bootstrap/bootstrapper_test.go
  snow/engine/avalanche/state/unique_vertex_test.go
  snow/engine/avalanche/vertex/vertextest/builder.go
  snow/engine/avalanche/vertex/vertextest/manager.go
  snow/engine/avalanche/vertex/vertextest/parser.go
  snow/engine/avalanche/vertex/vertextest/storage.go
  snow/engine/avalanche/vertex/vertextest/vm.go
  snow/engine/enginetest/bootstrap_tracker.go
  snow/engine/enginetest/bootstrapper.go
  snow/engine/enginetest/engine.go
  snow/engine/enginetest/sender.go
  snow/engine/enginetest/timer.go
  snow/engine/enginetest/vm.go
  snow/engine/snowman/block/batched_vm_test.go
  snow/engine/snowman/block/blocktest/batched_vm.go
  snow/engine/snowman/block/blocktest/state_summary.go
  snow/engine/snowman/block/blocktest/state_syncable_vm.go
  snow/engine/snowman/block/blocktest/vm.go
  snow/engine/snowman/bootstrap/bootstrapper_test.go
  snow/engine/snowman/config_test.go
  snow/engine/snowman/engine_test.go
  snow/engine/snowman/getter/getter_test.go
  snow/engine/snowman/syncer/state_syncer_test.go
  snow/engine/snowman/syncer/utils_test.go
  snow/networking/handler/handler_test.go
  snow/networking/handler/health_test.go
  snow/networking/router/chain_router_test.go
  snow/networking/sender/sender_test.go
  snow/networking/sender/sendertest/external.go
  snow/snowtest/context.go
  snow/validators/validatorstest/state.go
  vms/avm/environment_test.go
  vms/avm/network/network_test.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/vm_test.go
  vms/platformvm/warp/validator_test.go
  vms/proposervm/batched_vm_test.go
  vms/proposervm/proposer/windower_test.go
  vms/proposervm/state_syncable_vm_test.go
  vms/proposervm/vm_test.go
  vms/rpcchainvm/state_syncable_vm_test.go
  wallet/chain/p/builder_test.go
  wallet/chain/x/builder_test.go
  wallet/subnet/primary/common/utxotest/utxotest.go
Labels: testing, cleanup

#3268 Separate e2e tests by etna activation
  .github/workflows/ci.yml
  tests/e2e/e2e_test.go
  tests/e2e/etna/suites.go
  tests/fixture/e2e/flags.go
Labels: testing, acp77, acp103

#3209 Implement P-chain ACP-103 complexity calculations
  vms/platformvm/txs/fee/calculator_test.go
  vms/platformvm/txs/fee/complexity.go
  vms/platformvm/txs/fee/complexity_test.go
Labels: acp103

#3211 Implement dynamic fee calculator
  vms/components/fee/gas.go
  vms/components/fee/gas_test.go
  vms/platformvm/txs/fee/calculator_test.go
  vms/platformvm/txs/fee/dynamic_calculator.go
  vms/platformvm/txs/fee/dynamic_calculator_test.go
Labels: acp103

#3269 [tmpnet] Add Network.GetNetworkID() to get ID of a running network
  tests/fixture/tmpnet/network.go
Labels: testing

#3152 Disable `TransformSubnetTx` post-Etna
  tests/e2e/p/elastic_subnets.go
  vms/platformvm/txs/executor/standard_tx_executor.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
Labels: acp77

#3274 [tmpnet] Fail node health check if node is not running
  tests/fixture/tmpnet/network.go
  tests/fixture/tmpnet/node_process.go
  tests/fixture/tmpnet/utils.go
Labels: testing

#3272 [tmpnet] Enable network restart to simplify iteration
  tests/e2e/README.md
  tests/fixture/e2e/env.go
  tests/fixture/e2e/flags.go
Labels: testing

#3280 Add StoppedTimer helper
  network/throttling/inbound_conn_upgrade_throttler.go
  network/throttling/inbound_resource_throttler.go
  tests/antithesis/avalanchego/main.go
  tests/antithesis/xsvm/main.go
  utils/timer/stopped_timer.go
Labels: cleanup

#3281 Fix race in timer stoppage
  network/throttling/inbound_resource_throttler.go
Labels: bug, networking

#3282 Refactor P-chain Builder
  snow/engine/snowman/engine_test.go
  utils/slice.go
  wallet/chain/p/builder/builder.go
  wallet/chain/p/builder/builder_test.go
Labels: acp103

#3290 Update write path of tmpnet subnet config
  tests/fixture/tmpnet/subnet.go
Labels: testing, ci

#3283 add network upgrades to chain ctx
  chains/manager.go
  proto/pb/vm/vm.pb.go
  proto/vm/vm.proto
  snow/context.go
  snow/snowtest/context.go
  vms/rpcchainvm/vm_client.go
  vms/rpcchainvm/vm_server.go
Labels: testing

#3232 Implement dynamic fee builder
  wallet/chain/p/builder/builder.go
  wallet/chain/p/builder/context.go
  wallet/chain/p/builder_test.go
Labels: acp103

#3277 Remove cross-chain requests
  go.mod
  go.sum
  message/internal_msg_builder.go
  message/ops.go
  network/p2p/client.go
  network/p2p/handler.go
  network/p2p/network.go
  network/p2p/network_test.go
  network/p2p/router.go
  network/p2p/throttler_handler.go
  proto/appsender/appsender.proto
  proto/pb/appsender/appsender.pb.go
  proto/pb/appsender/appsender_grpc.pb.go
  proto/pb/vm/vm.pb.go
  proto/pb/vm/vm_grpc.pb.go
  proto/vm/vm.proto
  scripts/mocks.mockgen.source.txt
  snow/engine/avalanche/vertex/mock_vm.go
  snow/engine/common/appsender/appsender_client.go
  snow/engine/common/appsender/appsender_server.go
  snow/engine/common/engine.go
  snow/engine/common/mock_sender.go
  snow/engine/common/no_ops_handlers.go
  snow/engine/common/sender.go
  snow/engine/common/traced_engine.go
  snow/engine/enginetest/engine.go
  snow/engine/enginetest/sender.go
  snow/engine/enginetest/vm.go
  snow/engine/snowman/block/mock_chain_vm.go
  snow/networking/handler/handler.go
  snow/networking/router/chain_router_test.go
  snow/networking/sender/sender.go
  snow/networking/sender/sender_test.go
  snow/networking/sender/traced_sender.go
  tests/upgrade/upgrade_test.go
  vms/avm/network/atomic.go
  vms/rpcchainvm/vm_client.go
  vms/rpcchainvm/vm_server.go
Labels: cleanup

#3215 [antithesis] Add tmpnet support to workloads to simplify development
  .github/workflows/ci.yml
  scripts/lib_build_antithesis_images.sh
  tests/antithesis/README.md
  tests/antithesis/avalanchego/main.go
  tests/antithesis/compose.go
  tests/antithesis/config.go
  tests/antithesis/node_health.go
  tests/antithesis/xsvm/main.go
  tests/fixture/e2e/flags.go
  tests/fixture/e2e/ginkgo_test_context.go
  tests/fixture/tmpnet/node_process.go
  tests/notify_context.go
  tests/simple_test_context.go
  tests/test_context.go
Labels: testing

#3295 Refactor e2e tests for P-chain tests
  tests/e2e/c/dynamic_fees.go
  tests/e2e/c/interchain_workflow.go
  tests/e2e/p/interchain_workflow.go
  tests/e2e/p/staking_rewards.go
  tests/e2e/p/validator_sets.go
  tests/e2e/p/workflow.go
  tests/e2e/vms/xsvm.go
  tests/e2e/x/interchain_workflow.go
  tests/fixture/e2e/helpers.go
Labels: testing

#3296 Fix e2e tests to support dynamic fees
  tests/e2e/p/staking_rewards.go
  tests/e2e/p/workflow.go
  tests/fixture/e2e/helpers.go
Labels: testing, acp103

#3297 Improve error message of dynamic fee calculations
  vms/platformvm/txs/fee/dynamic_calculator.go
Labels: monitoring, acp103

#3298 Reduce dynamic fees variability to ease testing
  genesis/genesis_fuji.go
  genesis/genesis_local.go
  genesis/genesis_mainnet.go
Labels: acp103

#3226 deprecate uptime apis
  api/info/service.go
  api/info/service.md
  network/metrics.go
  network/peer/info.go
  proto/p2p/p2p.proto
  proto/pb/p2p/p2p.pb.go
  vms/platformvm/api/static_service.go
  vms/platformvm/client_permissionless_validator.go
  vms/platformvm/service.md
Labels: documentation, Uptime Tracking

#3299 [antithesis] Fix broken flag handling and improve image testing
  .golangci.yml
  scripts/lib_test_antithesis_images.sh
  tests/antithesis/compose.go
  tests/antithesis/config.go
Labels: testing

#3276 [tmpnet] Add support for checking rpcchainvm version compatibility
  tests/fixture/subnet/xsvm.go
  tests/fixture/tmpnet/README.md
  tests/fixture/tmpnet/network.go
  tests/fixture/tmpnet/subnet.go
  vms/example/xsvm/README.md
  vms/example/xsvm/cmd/versionjson/cmd.go
  vms/example/xsvm/cmd/xsvm/main.go
Labels: testing

#3302 Rename gas price calculation function
  vms/components/fee/gas.go
  vms/components/fee/gas_test.go
  vms/platformvm/service.go
  vms/platformvm/service_test.go
Labels: cleanup, acp103

#3304 Remove duplicate fork definitions
  upgrade/upgradetest/config.go
  upgrade/upgradetest/fork.go
  vms/avm/block/executor/block_test.go
  vms/avm/environment_test.go
  vms/avm/index_test.go
  vms/avm/service_test.go
  vms/avm/state_test.go
  vms/avm/txs/executor/syntactic_verifier_test.go
  vms/avm/vm_benchmark_test.go
  vms/avm/vm_regression_test.go
  vms/avm/vm_test.go
  vms/avm/wallet_service_test.go
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/builder/standard_block_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/block/executor/standard_block_test.go
  vms/platformvm/block/executor/verifier_test.go
  vms/platformvm/service_test.go
  vms/platformvm/txs/executor/advance_time_test.go
  vms/platformvm/txs/executor/create_chain_test.go
  vms/platformvm/txs/executor/create_subnet_test.go
  vms/platformvm/txs/executor/export_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/txs/executor/import_test.go
  vms/platformvm/txs/executor/proposal_tx_executor_test.go
  vms/platformvm/txs/executor/reward_validator_test.go
  vms/platformvm/txs/executor/staker_tx_verification_test.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
  vms/proposervm/block_test.go
  vms/proposervm/post_fork_option_test.go
  vms/proposervm/state_syncable_vm_test.go
  vms/proposervm/vm_test.go
Labels: testing, cleanup

#3147 Restrict `Owner` usage after a Subnet manager is set
  vms/platformvm/txs/executor/create_chain_test.go
  vms/platformvm/txs/executor/staker_tx_verification.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/txs/executor/subnet_tx_verification.go
Labels: acp77

#2951 SoV networking support
  message/mock_outbound_message_builder.go
  message/outbound_msg_builder.go
  network/README.md
  network/ip_tracker.go
  network/ip_tracker_test.go
  network/network.go
  network/peer/config.go
  network/peer/network.go
  network/peer/peer.go
  network/peer/peer_test.go
  network/peer/test_network.go
  proto/p2p/p2p.proto
  proto/pb/p2p/p2p.pb.go
Labels: networking, acp77

#3305 [antithesis] Enable custom plugin dir for subnet-evm
  tests/antithesis/avalanchego/gencomposeconfig/main.go
  tests/antithesis/compose.go
  tests/antithesis/xsvm/gencomposeconfig/main.go
Labels: testing

#3310 Refactor state tests to always use initialized state
  vms/platformvm/genesis/genesistest/genesis.go
  vms/platformvm/state/diff_test.go
  vms/platformvm/state/stakers_test.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
Labels: cleanup, acp77, acp103

#3312 Remove mock for `Versions` interface
  scripts/mocks.mockgen.txt
  vms/platformvm/state/diff_test.go
  vms/platformvm/state/mock_state.go
Labels: cleanup

#3314 Allow P-chain wallet to be used by the platformvm
  wallet/chain/p/builder_test.go
  wallet/chain/p/client.go
  wallet/chain/p/wallet/backend.go
  wallet/chain/p/wallet/backend_visitor.go
  wallet/chain/p/wallet/wallet.go
  wallet/chain/p/wallet/with_options.go
  wallet/subnet/primary/examples/get-p-chain-balance/main.go
  wallet/subnet/primary/wallet.go
Labels: cleanup, acp103

#3315 Add .String() to Fork testing utility
  upgrade/upgradetest/fork.go
Labels: testing, acp103

#3319 Add statetest to replace common test state initialization
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
  vms/platformvm/state/statetest/state.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/validators/manager_benchmark_test.go
  vms/platformvm/vm.go
  vms/platformvm/vm_regression_test.go
Labels: testing, cleanup, acp103

#3321 Rename `components/fee` pkg to `components/gas`
  config/config.go
  config/flags.go
  genesis/genesis_fuji.go
  genesis/genesis_local.go
  genesis/genesis_mainnet.go
  genesis/params.go
  vms/components/gas/config.go
  vms/components/gas/dimensions.go
  vms/components/gas/dimensions_test.go
  vms/components/gas/gas.go
  vms/components/gas/gas_test.go
  vms/components/gas/state.go
  vms/components/gas/state_test.go
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/block/executor/standard_block_test.go
  vms/platformvm/block/executor/verifier_test.go
  vms/platformvm/client.go
  vms/platformvm/config/config.go
  vms/platformvm/service.go
  vms/platformvm/service_test.go
  vms/platformvm/state/diff.go
  vms/platformvm/state/diff_test.go
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
  vms/platformvm/txs/fee/calculator_test.go
  vms/platformvm/txs/fee/complexity.go
  vms/platformvm/txs/fee/complexity_test.go
  vms/platformvm/txs/fee/dynamic_calculator.go
  vms/platformvm/vm_test.go
  wallet/chain/p/builder/builder.go
  wallet/chain/p/builder/context.go
  wallet/chain/p/builder_test.go
Labels: cleanup

#3322 Remove mocks for `Staker` and `ScheduledStaker`
  scripts/mocks.mockgen.source.txt
  vms/platformvm/signer/mock_signer.go
  vms/platformvm/state/staker_test.go
  vms/platformvm/txs/mock_staker_tx.go
Labels: cleanup

#3011 [e2e] Simplify pre-funded key usage
  tests/e2e/banff/suites.go
  tests/e2e/c/interchain_workflow.go
  tests/e2e/p/elastic_subnets.go
  tests/e2e/p/interchain_workflow.go
  tests/e2e/p/owner_retrieval.go
  tests/e2e/p/staking_rewards.go
  tests/e2e/p/validator_sets.go
  tests/e2e/p/workflow.go
  tests/e2e/x/interchain_workflow.go
  tests/e2e/x/transfer/virtuous.go
  tests/fixture/e2e/env.go
  tests/fixture/test_data_server.go
  tests/fixture/test_data_server_test.go
Labels: testing

#3320 Move iterator implementations to `utils` pkg
  scripts/mocks.mockgen.source.txt
  scripts/mocks.mockgen.txt
  utils/iterator/empty.go
  utils/iterator/empty_test.go
  utils/iterator/filter.go
  utils/iterator/filter_test.go
  utils/iterator/iterator.go
  utils/iterator/iteratormock/iterator.go
  utils/iterator/merge.go
  utils/iterator/merge_test.go
  utils/iterator/slice.go
  utils/iterator/tree.go
  utils/iterator/tree_test.go
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/block/executor/acceptor_test.go
  vms/platformvm/block/executor/backend_test.go
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/block/executor/standard_block_test.go
  vms/platformvm/block/executor/verifier_test.go
  vms/platformvm/state/diff.go
  vms/platformvm/state/diff_test.go
  vms/platformvm/state/empty_iterator.go
  vms/platformvm/state/empty_iterator_test.go
  vms/platformvm/state/masked_iterator.go
  vms/platformvm/state/mock_chain.go
  vms/platformvm/state/mock_diff.go
  vms/platformvm/state/mock_staker_iterator.go
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/slice_iterator_test.go
  vms/platformvm/state/staker.go
  vms/platformvm/state/staker_diff_iterator.go
  vms/platformvm/state/staker_diff_iterator_test.go
  vms/platformvm/state/stakers.go
  vms/platformvm/state/stakers_test.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
  vms/platformvm/state/statemock/chain.go
  vms/platformvm/state/statemock/diff.go
  vms/platformvm/state/tree_iterator.go
  vms/platformvm/txs/executor/staker_tx_verification_test.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
Labels: cleanup

#3318 Remove duplicate genesis creations in P-chain unit tests
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/builder/standard_block_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/block/executor/standard_block_test.go
  vms/platformvm/block/executor/verifier_test.go
  vms/platformvm/block/parse_test.go
  vms/platformvm/genesis/genesistest/genesis.go
  vms/platformvm/service_test.go
  vms/platformvm/state/stakers_test.go
  vms/platformvm/state/state_test.go
  vms/platformvm/state/statetest/state.go
  vms/platformvm/txs/add_delegator_test.go
  vms/platformvm/txs/add_subnet_validator_test.go
  vms/platformvm/txs/add_validator_test.go
  vms/platformvm/txs/create_chain_test.go
  vms/platformvm/txs/executor/advance_time_test.go
  vms/platformvm/txs/executor/create_chain_test.go
  vms/platformvm/txs/executor/create_subnet_test.go
  vms/platformvm/txs/executor/export_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/txs/executor/import_test.go
  vms/platformvm/txs/executor/proposal_tx_executor_test.go
  vms/platformvm/txs/executor/reward_validator_test.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/validators/manager_benchmark_test.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
Labels: testing, acp103

#3327 Simplify P-Chain transaction creation in unit tests
  vms/platformvm/service_test.go
  vms/platformvm/txs/txstest/wallet.go
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
Labels: testing, cleanup

#3332 [tmpnet] Ensure nodes are stopped in the event of bootstrap failure
  tests/fixture/e2e/helpers.go
Labels: testing

#3334 Add tx complexity helper
  vms/platformvm/txs/fee/complexity.go
  vms/platformvm/txs/fee/complexity_test.go
Labels: acp103

#3330 Fixed segfault when --tracing-enabled is set
  snow/engine/common/traced_bootstrapable_engine.go
Labels: bug

#3336 Enforce network config not including `PrimaryNetworkID` in `trackedSubnets`
  network/config.go
  network/network.go
Labels: cleanup

#3328 Use wallet in `platformvm/block` tests
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/builder/standard_block_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/block/executor/standard_block_test.go
Labels: cleanup

#3339 [ci] Stop using setup-go-v3
  .github/actions/setup-go-for-project-v3/action.yml
  .github/workflows/build-linux-binaries.yml
  .github/workflows/build-ubuntu-arm64-release.yml
  .github/workflows/ci.yml
Labels: ci

#3333 Use wallet in `platformvm/txs` tests
  vms/platformvm/txs/executor/advance_time_test.go
  vms/platformvm/txs/executor/create_chain_test.go
  vms/platformvm/txs/executor/create_subnet_test.go
  vms/platformvm/txs/executor/export_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/txs/executor/import_test.go
  vms/platformvm/txs/executor/proposal_tx_executor_test.go
  vms/platformvm/txs/executor/reward_validator_test.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/txs/txstest/backend.go
  vms/platformvm/txs/txstest/builder.go
Labels: testing, cleanup, acp103

#3251 Add P-chain dynamic fees execution
  vms/platformvm/block/builder/builder.go
  vms/platformvm/block/executor/verifier.go
  vms/platformvm/block/executor/verifier_test.go
  vms/platformvm/service_test.go
  vms/platformvm/state/chain_time_helpers.go
  vms/platformvm/state/chain_time_helpers_test.go
  vms/platformvm/txs/executor/state_changes.go
  vms/platformvm/txs/executor/state_changes_test.go
  vms/platformvm/txs/txstest/context.go
  vms/platformvm/txs/txstest/wallet.go
  vms/platformvm/vm_test.go
  wallet/chain/p/builder/context.go
  wallet/chain/p/context.go
  wallet/subnet/primary/api.go
Labels: acp103

#3344 Include disconnected validators in health message
  snow/engine/common/tracker/peers.go
  snow/networking/handler/health.go
  snow/networking/handler/health_test.go
Labels: incident response
