Repository ava-labs/avalanchego, pull requests merged in 2024-10, with the labels that each got.

#3432 [e2e] Enable supplying ginkgo seed to e2e test script
  scripts/tests.e2e.sh
Labels: testing

#3433 [antithesis] Add curl to antithesis images
  tests/antithesis/avalanchego/Dockerfile.node
Labels: testing

#3434 ACP-118: Implement p2p handler
  network/p2p/acp118/handler.go
  network/p2p/acp118/handler_test.go
Labels: acp77, acp118

#3430 ACP-77: Update warp messages to align with spec changes
  vms/platformvm/warp/message/codec.go
  vms/platformvm/warp/message/payload_test.go
  vms/platformvm/warp/message/register_subnet_validator.go
  vms/platformvm/warp/message/register_subnet_validator_test.go
  vms/platformvm/warp/message/set_subnet_validator_weight.go
  vms/platformvm/warp/message/set_subnet_validator_weight_test.go
  vms/platformvm/warp/message/subnet_conversion.go
  vms/platformvm/warp/message/subnet_conversion_test.go
  vms/platformvm/warp/message/subnet_validator_weight.go
  vms/platformvm/warp/message/subnet_validator_weight_test.go
Labels: acp77

#3435 Change misleading protobuf comments
  proto/p2p/p2p.proto
  proto/pb/p2p/p2p.pb.go
Labels: documentation

#3439 Remove unused metrics registry from sync ManagerConfig
  x/sync/manager.go
Labels: cleanup

#3441 Publish last accepted height through chits
  message/messagemock/outbound_message_builder.go
  message/outbound_msg_builder.go
  proto/p2p/p2p.proto
  proto/pb/p2p/p2p.pb.go
  snow/engine/common/commonmock/sender.go
  snow/engine/common/engine.go
  snow/engine/common/no_ops_handlers.go
  snow/engine/common/sender.go
  snow/engine/common/traced_engine.go
  snow/engine/common/tracker/accepted.go
  snow/engine/common/tracker/accepted_test.go
  snow/engine/enginetest/engine.go
  snow/engine/enginetest/sender.go
  snow/engine/snowman/engine.go
  snow/engine/snowman/engine_test.go
  snow/networking/handler/handler.go
  snow/networking/handler/handler_test.go
  snow/networking/sender/sender.go
  snow/networking/sender/traced_sender.go
Labels: consensus

#3442 Include untracked files for clean branch
  .github/workflows/check-clean-branch.sh
  scripts/mocks.mockgen.source.txt
Labels: testing

#3443 [testing] Fix bootstrap monitor e2e image build error check
  tests/fixture/bootstrapmonitor/e2e/e2e_test.go
Labels: testing

#3448 ACP-77: Allow xsvm to sign arbitrary warp messages
  vms/example/xsvm/vm.go
  vms/example/xsvm/warp.go
Labels: testing, acp77

#3449 Use netip.AddrPort rather than string for node.ProcessContext
  node/node.go
  node/process_context.go
  node/process_context_test.go
  tests/fixture/tmpnet/network.go
  tests/fixture/tmpnet/node.go
  tests/fixture/tmpnet/node_process.go
Labels: testing, acp77

#3450 Remove unused `meteredHandler` struct type
  network/p2p/router.go
Labels: cleanup

#3451 Add ACP-118 caching support
  network/p2p/acp118/handler.go
  network/p2p/acp118/handler_test.go
Labels: acp118

#3455 Remove unexpected block unwrapping
  vms/platformvm/block/executor/verifier.go
  vms/platformvm/block/executor/verifier_test.go
Labels: cleanup

#3462 [ci] Update MacOS jobs to macos-14
  .github/workflows/build-macos-release.yml
  .github/workflows/ci.yml
Labels: ci

#3467 [testing] Enable config of log format for bootstrap monitor
  tests/fixture/bootstrapmonitor/cmd/main.go
  tests/fixture/bootstrapmonitor/e2e/e2e_test.go
Labels: testing

#3474 cache signatures only in acp118 handler
  network/p2p/acp118/handler.go
  network/p2p/acp118/handler_test.go
Labels: cleanup, acp118

#3465 [tmpnet] Add --start-network to support hypersdk MODE=run
  tests/fixture/e2e/env.go
  tests/fixture/e2e/flags.go
  tests/fixture/e2e/helpers.go
  tests/upgrade/upgrade_test.go
Labels: testing

#3466 [e2e] Check network health after bootstrap checks
  tests/e2e/banff/suites.go
  tests/e2e/p/elastic_subnets.go
  tests/e2e/p/owner_retrieval.go
  tests/e2e/p/permissionless_layer_one.go
  tests/e2e/p/workflow.go
  tests/e2e/x/transfer/virtuous.go
  tests/fixture/e2e/helpers.go
Labels: testing

#3481 ACP-77: Add ConversionID to state
  vms/platformvm/client.go
  vms/platformvm/config/execution_config.go
  vms/platformvm/config/execution_config_test.go
  vms/platformvm/service.go
  vms/platformvm/service.md
  vms/platformvm/state/diff.go
  vms/platformvm/state/diff_test.go
  vms/platformvm/state/mock_chain.go
  vms/platformvm/state/mock_diff.go
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
  vms/platformvm/txs/executor/create_chain_test.go
  vms/platformvm/txs/executor/staker_tx_verification.go
  vms/platformvm/txs/executor/standard_tx_executor.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/txs/executor/subnet_tx_verification.go
Labels: acp77

#3483 Wrap `TestDiffExpiry` sub-tests in `t.Run`
  vms/platformvm/state/diff_test.go
Labels: testing, cleanup

#3488 Move RPC metrics registration after its client's initialization
  vms/rpcchainvm/vm_client.go
Labels: cleanup

#3490 Remove deprecated X-chain pubsub server
  go.mod
  pubsub/bloom/filter.go
  pubsub/bloom/filter_test.go
  pubsub/bloom/map_filter.go
  pubsub/connection.go
  pubsub/connections.go
  pubsub/filter_param.go
  pubsub/filter_test.go
  pubsub/filterer.go
  pubsub/messages.go
  pubsub/server.go
  vms/avm/pubsub_filterer.go
  vms/avm/pubsub_filterer_test.go
  vms/avm/service.md
  vms/avm/vm.go
Labels: cleanup

#3492 Update SoV struct to align with latest ACP-77 spec
  vms/platformvm/state/subnet_only_validator.go
  vms/platformvm/state/subnet_only_validator_test.go
Labels: acp77

#3489 Register VM and snowman metrics after chain creation
  chains/manager.go
Labels: cleanup

#3494 ACP-77: Update P-chain state staker tests
  vms/platformvm/state/state_test.go
Labels: testing, cleanup, acp77

#3487 ACP-77: Write subnet public key diffs to state
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
  vms/platformvm/validators/manager.go
Labels: acp77

#3498 Add `Deregister` to `metrics.MultiGatherer` interface
  api/metrics/label_gatherer.go
  api/metrics/label_gatherer_test.go
  api/metrics/multi_gatherer.go
  api/metrics/prefix_gatherer.go
  utils/slice.go
  utils/slice_test.go
Labels: monitoring

#3502 Use subnet public key diffs after Etna is activated
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_interface_test.go
  vms/platformvm/validators/manager.go
  vms/platformvm/validators/manager_test.go
Labels: acp77

#3504 Add NumSubnets to the validator manager interface
  network/network.go
  node/node.go
  node/overridden_manager.go
  snow/engine/snowman/bootstrap/bootstrapper.go
  snow/engine/snowman/bootstrap/bootstrapper_test.go
  snow/engine/snowman/syncer/state_syncer.go
  snow/engine/snowman/syncer/state_syncer_test.go
  snow/engine/snowman/syncer/utils_test.go
  snow/validators/manager.go
  snow/validators/manager_test.go
  vms/platformvm/state/state.go
  vms/platformvm/vm_test.go
Labels: acp77

#3509 ACP-77: Filter the inactive validator from block proposals and tx gossip
  network/p2p/validators.go
  network/p2p/validators_test.go
  vms/proposervm/proposer/windower.go
  vms/proposervm/proposer/windower_test.go
Labels: acp77

#3508 [testing] Enable bootstrap testing of partial sync
  tests/fixture/bootstrapmonitor/README.md
  tests/fixture/bootstrapmonitor/bootstrap_test_config.go
  tests/fixture/bootstrapmonitor/bootstrap_test_config_test.go
Labels: testing
