Repository ava-labs/avalanchego, pull requests merged in 2024-01, with the labels that each got.

#2570 Update `CODEOWNERS`
  .github/CODEOWNERS
Labels: ci

#2574 Remove license from mocks
  api/server/mock_server.go
  chains/atomic/mock_shared_memory.go
  codec/mock_manager.go
  database/mock_batch.go
  database/mock_iterator.go
  indexer/indexer_test.go
  message/mock_message.go
  message/mock_outbound_message_builder.go
  scripts/mock.gen.sh
  scripts/mocks.mockgen.txt
  snow/consensus/snowman/mock_block.go
  snow/engine/avalanche/vertex/mock_vm.go
  snow/engine/snowman/block/mock_build_block_with_context_vm.go
  snow/engine/snowman/block/mock_chain_vm.go
  snow/engine/snowman/block/mock_state_syncable_vm.go
  snow/engine/snowman/block/mock_with_verify_context.go
  snow/engine/snowman/getter/getter_test.go
  snow/networking/handler/mock_handler.go
  snow/networking/timeout/mock_manager.go
  snow/networking/tracker/mock_resource_tracker.go
  snow/networking/tracker/mock_targeter.go
  snow/uptime/mock_calculator.go
  snow/validators/mock_state.go
  snow/validators/mock_subnet_connector.go
  utils/crypto/keychain/mock_ledger.go
  utils/filesystem/mock_io.go
  utils/hashing/mock_hasher.go
  utils/resource/mock_user.go
  vms/avm/block/mock_block.go
  vms/avm/metrics/mock_metrics.go
  vms/avm/state/mock_state.go
  vms/avm/txs/mempool/mock_mempool.go
  vms/components/avax/mock_transferable_in.go
  vms/components/verify/mock_verifiable.go
  vms/mock_manager.go
  vms/platformvm/block/mock_block.go
  vms/platformvm/state/mock_staker_iterator.go
  vms/platformvm/state/mock_state.go
  vms/platformvm/txs/mempool/mock_mempool.go
  vms/platformvm/utxo/mock_verifier.go
  vms/proposervm/block_test.go
  vms/proposervm/mock_post_fork_block.go
  vms/proposervm/pre_fork_block_test.go
  vms/proposervm/proposer/mock_windower.go
  vms/proposervm/scheduler/mock_scheduler.go
  vms/proposervm/state/mock_state.go
  vms/proposervm/vm_test.go
  vms/registry/mock_vm_getter.go
  vms/registry/mock_vm_registerer.go
  vms/registry/mock_vm_registry.go
  vms/registry/vm_registerer_test.go
  vms/rpcchainvm/batched_vm_test.go
  vms/rpcchainvm/state_syncable_vm_test.go
  vms/rpcchainvm/vm_test.go
  vms/rpcchainvm/with_context_vm_test.go
  x/sync/mock_client.go
Labels: ci

#2573 Add missing import
  utils/ulimit/ulimit_bsd.go
Labels: cleanup

#2566 `vms/platformvm`: Prune mempool periodically
  vms/platformvm/block/builder/builder.go
  vms/platformvm/config/execution_config.go
  vms/platformvm/config/execution_config_test.go
  vms/platformvm/vm.go
  vms/platformvm/vm_test.go
Labels: vm

#2576 [MerkleDB] Make intermediate node cache two layered
  x/merkledb/db.go
  x/merkledb/db_test.go
  x/merkledb/intermediate_node_db.go
  x/merkledb/intermediate_node_db_test.go
  x/merkledb/proof.go
  x/sync/client_test.go
Labels: merkledb

#2581 Fix merkledb rebuild iterator
  x/merkledb/db.go
Labels: merkledb

#2585 Fix intermediate node caching
  x/merkledb/db.go
  x/merkledb/intermediate_node_db.go
  x/merkledb/intermediate_node_db_test.go
Labels: merkledb

#2583 `tmpnet`: Use AvalancheLocalChainConfig for cchain genesis
  tests/fixture/tmpnet/genesis.go
Labels: testing

#2582 `testing`: Ensure CheckBootstrapIsPossible is safe for teardown
  tests/fixture/e2e/helpers.go
Labels: testing

#2464 `tmpnet`: Separate network into orchestration and configuration
  tests/e2e/README.md
  tests/fixture/e2e/env.go
  tests/fixture/e2e/helpers.go
  tests/fixture/tmpnet/README.md
  tests/fixture/tmpnet/cmd/main.go
  tests/fixture/tmpnet/defaults.go
  tests/fixture/tmpnet/network.go
  tests/fixture/tmpnet/network_config.go
  tests/fixture/tmpnet/network_test.go
  tests/fixture/tmpnet/node.go
  tests/upgrade/upgrade_test.go
Labels: testing

#2590 Update uintsize implementation
  x/merkledb/codec.go
  x/merkledb/codec_test.go
Labels: merkledb

#2588 Optimize bloom filter
  go.mod
  go.sum
  network/p2p/gossip/bloom.go
  network/p2p/gossip/bloom_test.go
  network/p2p/gossip/handler.go
  proto/pb/sdk/sdk.pb.go
  proto/sdk/sdk.proto
  pubsub/bloom/filter.go
  pubsub/bloom/filter_test.go
  pubsub/bloom/map_filter.go
  pubsub/connection.go
  pubsub/filter_param.go
  pubsub/filter_test.go
  utils/bloom/bloom_filter.go
  utils/bloom/filter.go
  utils/bloom/filter_test.go
  utils/bloom/hasher.go
  utils/bloom/hasher_test.go
  utils/bloom/optimal.go
  utils/bloom/optimal_test.go
  utils/bloom/read_filter.go
  utils/bloom/read_filter_test.go
  vms/avm/network/config.go
  vms/avm/network/gossip.go
  vms/platformvm/network/config.go
  vms/platformvm/network/gossip.go
Labels: enhancement

#2596 Remove TLS key gen from networking tests
  network/certs_test.go
  network/test_cert_1.crt
  network/test_cert_2.crt
  network/test_cert_3.crt
  network/test_key_1.key
  network/test_key_2.key
  network/test_key_3.key
Labels: testing, networking

#2591 [utils/bloom] Optionally Update Bloom Filter Size on Reset
  go.mod
  go.sum
  network/p2p/gossip/bloom.go
  network/p2p/gossip/bloom_test.go
  network/p2p/gossip/gossip.go
  network/p2p/gossip/gossip_test.go
  network/p2p/gossip/gossipable.go
  network/p2p/gossip/test_gossip.go
  utils/bloom/filter.go
  utils/bloom/filter_test.go
  vms/avm/network/gossip.go
  vms/avm/network/network_test.go
  vms/avm/txs/mempool/mempool.go
  vms/avm/txs/mempool/mock_mempool.go
  vms/platformvm/network/gossip.go
  vms/platformvm/network/gossip_test.go
  vms/platformvm/network/network_test.go
  vms/platformvm/txs/mempool/mempool.go
  vms/platformvm/txs/mempool/mock_mempool.go
Labels: networking

#2599 [ci] Increase Fuzz Time in Periodic Runs
  .github/workflows/fuzz.yml
Labels: ci

#2601 `tmpnet`: Save metrics snapshot to disk before node shutdown
  tests/fixture/tmpnet/network.go
  tests/fixture/tmpnet/node.go
  tests/fixture/tmpnet/node_config.go
Labels: testing

#2602 chore: Fix typo s/useage/usage
  RELEASES.md
Labels: documentation

#2600 Deprecate `SnowRogueCommitThresholdKey` and `SnowVirtuousCommitThresholdKey`
  config/config.go
  config/flags.go
  config/keys.go
  snow/consensus/snowball/parameters.go
Labels: consensus

#2604 Fix networking invalid field log
  network/peer/peer.go
Labels: monitoring

#2605 chore: Fix typo s/seperate/separate/
  proto/pb/vm/vm_grpc.pb.go
  proto/vm/vm.proto
Labels: documentation, cleanup

#2603 Support dynamic port peerlist gossip
  .github/workflows/ci.yml
  app/app.go
  config/config.go
  config/flags.go
  nat/nat.go
  network/dialer_test.go
  network/network.go
  network/peer/peer.go
  network/peer/peer_test.go
  network/peer/test_peer.go
  network/test_network.go
  node/config.go
  node/node.go
Labels: bug, networking

#2580 Replace `PeerListAck` with `GetPeerList`
  config/config.go
  config/flags.go
  config/keys.go
  genesis/bootstrappers.go
  message/messages_test.go
  message/mock_outbound_message_builder.go
  message/ops.go
  message/outbound_msg_builder.go
  network/README.md
  network/certs_test.go
  network/config.go
  network/ip_tracker.go
  network/ip_tracker_test.go
  network/network.go
  network/network_test.go
  network/peer/gossip_tracker.go
  network/peer/gossip_tracker_callback.go
  network/peer/gossip_tracker_metrics.go
  network/peer/gossip_tracker_test.go
  network/peer/network.go
  network/peer/peer.go
  network/peer/test_network.go
  network/test_network.go
  node/node.go
  proto/p2p/p2p.proto
  proto/pb/p2p/p2p.pb.go
  utils/bloom/read_filter.go
  utils/constants/networking.go
  utils/ips/claimed_ip_port.go
  utils/ips/ip_port.go
Labels: networking

#2609 Log critical consensus values during health checks
  snow/engine/common/request.go
  snow/engine/common/request_test.go
  snow/engine/snowman/transitive.go
  utils/bimap/bimap.go
  utils/bimap/bimap_test.go
Labels: consensus, monitoring

#2610 Update contributions branch to master
  CONTRIBUTING.md
Labels: documentation

#2614 Add ip bloom metrics
  network/ip_tracker.go
  network/ip_tracker_test.go
  network/network.go
Labels: monitoring

#2617 `x/sync`: Auto-generate `MockNetworkClient`
  scripts/mocks.mockgen.txt
  x/sync/client_test.go
  x/sync/mock_network_client.go
Labels: ci, cleanup

#2589 Remove CreateStaticHandlers from VM interface
  api/admin/service.go
  api/admin/service_test.go
  node/node.go
  proto/pb/vm/vm.pb.go
  proto/pb/vm/vm_grpc.pb.go
  proto/vm/vm.proto
  scripts/mocks.mockgen.txt
  snow/engine/avalanche/vertex/mock_vm.go
  snow/engine/common/test_vm.go
  snow/engine/common/vm.go
  snow/engine/snowman/block/mock_chain_vm.go
  tests/e2e/e2e_test.go
  tests/e2e/static-handlers/suites.go
  utils/constants/aliases.go
  vms/avm/static_client.go
  vms/avm/static_service_test.go
  vms/avm/vm.go
  vms/example/xsvm/vm.go
  vms/platformvm/api/static_client.go
  vms/platformvm/vm.go
  vms/registry/mock_vm_registerer.go
  vms/registry/mock_vm_registry.go
  vms/registry/vm_registerer.go
  vms/registry/vm_registerer_test.go
  vms/registry/vm_registry.go
  vms/registry/vm_registry_test.go
  vms/rpcchainvm/vm_client.go
  vms/rpcchainvm/vm_server.go
Labels: cleanup

#2492 `tmpnet`: Add support for subnets
  tests/e2e/e2e_test.go
  tests/fixture/e2e/env.go
  tests/fixture/e2e/flags.go
  tests/fixture/e2e/helpers.go
  tests/fixture/tmpnet/README.md
  tests/fixture/tmpnet/cmd/main.go
  tests/fixture/tmpnet/defaults.go
  tests/fixture/tmpnet/network.go
  tests/fixture/tmpnet/network_config.go
  tests/fixture/tmpnet/network_test.go
  tests/fixture/tmpnet/node.go
  tests/fixture/tmpnet/subnet.go
  tests/upgrade/upgrade_test.go
Labels: testing, e2e-subnets

#2615 Add `mockgen` source mode for generics + bls imports
  scripts/mock.gen.sh
  scripts/mocks.mockgen.source.txt
  snow/engine/common/mock_sender.go
  snow/networking/router/mock_router.go
  snow/networking/sender/mock_external_sender.go
  snow/validators/mock_manager.go
  vms/avm/block/executor/mock_manager.go
  vms/avm/txs/mock_unsigned_tx.go
  vms/platformvm/block/executor/mock_manager.go
  vms/platformvm/txs/mock_staker.go
  vms/platformvm/txs/mock_staker_tx.go
  vms/platformvm/txs/mock_unsigned_tx.go
  x/merkledb/mock_db.go
Labels: ci

#2616 Verify all MockGen generated files are re-generated in CI
  scripts/mock.gen.sh
  vms/components/avax/mock_transferable_out.go
  vms/platformvm/fx/mock_fx.go
Labels: ci

#2505 P-chain Add UTs around stakers persistence in platformvm state
  vms/platformvm/state/diff_test.go
  vms/platformvm/state/state_test.go
Labels: testing

#2623 Revert "Set dependabot target branch to `dev` (#2553)"
  .github/dependabot.yml
Labels: dependencies, ci

#2624 Remove remaining 2023 remnants
  LICENSE
  header.yml
  network/ip_tracker.go
  tests/fixture/tmpnet/network_config.go
  tests/fixture/tmpnet/subnet.go
  utils/filesystem/mock_file.go
Labels: cleanup

#2627 Remove support for compressing gzip messages
  config/config.go
  config/flags.go
  message/messages.go
  message/messages_test.go
  message/outbound_msg_builder_test.go
  utils/compression/gzip_compressor.go
  utils/compression/type.go
Labels: cleanup

#2458 Modify TLS parsing rules for Durango
  indexer/examples/p-chain/main.go
  indexer/examples/x-chain-blocks/main.go
  network/network.go
  network/peer/peer.go
  network/peer/test_peer.go
  network/peer/upgrader.go
  staking/asn1.go
  staking/certificate.go
  staking/large_rsa_key.sig
  staking/parse.go
  staking/parse_test.go
  staking/verify.go
  staking/verify_test.go
  vms/proposervm/batched_vm.go
  vms/proposervm/block/block.go
  vms/proposervm/block/build.go
  vms/proposervm/block/option.go
  vms/proposervm/block/parse.go
  vms/proposervm/block/parse_test.go
  vms/proposervm/state/block_state.go
  vms/proposervm/vm.go
Labels: networking, Durango

#2548 Update versions for v1.10.18
  RELEASES.md
  network/p2p/network_test.go
  network/peer/peer.go
  network/peer/validator_id.go
  utils/sorting_test.go
  version/compatibility.json
  version/constants.go
  vms/avm/network/network.go
  vms/platformvm/block/executor/verifier.go
  vms/platformvm/vm.go
Labels: documentation

#2489 `vms/platformvm`: Change `AdvanceTimeTo` to modify passed-in `parentState`
  vms/platformvm/block/builder/builder.go
  vms/platformvm/block/executor/verifier.go
  vms/platformvm/txs/executor/proposal_tx_executor.go
  vms/platformvm/txs/executor/state_changes.go
  vms/platformvm/txs/executor/tx_mempool_verifier.go
Labels: cleanup

#2362 `vms/platformvm`: Remove `MempoolTxVerifier`
  vms/platformvm/block/executor/manager.go
  vms/platformvm/txs/executor/export_test.go
  vms/platformvm/txs/executor/import_test.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/txs/executor/state_changes.go
  vms/platformvm/txs/executor/tx_mempool_verifier.go
Labels: cleanup

#2587 Verify `SignedIP.Timestamp` from `PeerList` messages
  network/network.go
  network/peer/ip.go
  network/peer/ip_test.go
  network/peer/peer.go
Labels: networking, cleanup

#2632 Fix metrics namespace
  api/metrics/multi_gatherer.go
  chains/manager.go
  message/creator.go
  network/throttling/inbound_msg_throttler.go
  snow/engine/common/queue/state.go
  snow/networking/handler/message_queue_metrics.go
  utils/metric/namespace.go
  utils/metric/namespace_test.go
  vms/proposervm/state/block_state.go
Labels: monitoring, cleanup

#2633 Bloomfilter metrics union
  network/ip_tracker.go
  network/ip_tracker_test.go
  network/p2p/gossip/bloom.go
  network/p2p/gossip/bloom_test.go
  utils/bloom/metrics.go
Labels: cleanup

#2612 Add bloom filter metrics to the p2p sdk
  go.mod
  go.sum
  network/ip_tracker.go
  network/ip_tracker_test.go
  network/p2p/gossip/bloom.go
  network/p2p/gossip/bloom_test.go
  network/p2p/gossip/gossip_test.go
  utils/bloom/metrics.go
  vms/avm/network/gossip.go
  vms/avm/network/gossip_test.go
  vms/avm/network/network.go
  vms/platformvm/network/gossip.go
  vms/platformvm/network/gossip_test.go
  vms/platformvm/network/network.go
Labels: monitoring

#2491 Replace `shutdownEnvironment` with `t.Cleanup()`
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/builder/standard_block_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/block/executor/standard_block_test.go
  vms/platformvm/txs/executor/advance_time_test.go
  vms/platformvm/txs/executor/create_chain_test.go
  vms/platformvm/txs/executor/create_subnet_test.go
  vms/platformvm/txs/executor/export_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/txs/executor/import_test.go
  vms/platformvm/txs/executor/proposal_tx_executor_test.go
  vms/platformvm/txs/executor/reward_validator_test.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
Labels: testing, cleanup

#2607 P-chain - Memo field zeroed post Durango
  vms/components/avax/base_tx.go
  vms/platformvm/txs/executor/staker_tx_verification.go
  vms/platformvm/txs/executor/staker_tx_verification_test.go
  vms/platformvm/txs/executor/standard_tx_executor.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
Labels: Durango

#2578 Refactor feature extensions out of VMManager
  api/info/service.go
  chains/manager.go
  node/node.go
  vms/fx/factory.go
  vms/nftfx/factory.go
  vms/nftfx/factory_test.go
  vms/propertyfx/factory.go
  vms/propertyfx/factory_test.go
  vms/secp256k1fx/factory.go
  vms/secp256k1fx/factory_test.go
Labels: cleanup

#2641 Remove getter for router on chain manager
  chains/manager.go
  chains/test_manager.go
Labels: cleanup

#2645 Fix `require.ErrorIs` argument order
  network/p2p/network_test.go
  vms/proposervm/block_test.go
  vms/proposervm/vm_regression_test.go
Labels: testing, cleanup

#2363 Allow calls to `Options` before `Verify`
  snow/consensus/snowman/oracle_block.go
  vms/platformvm/block/executor/acceptor.go
  vms/platformvm/block/executor/acceptor_test.go
  vms/platformvm/block/executor/block.go
  vms/platformvm/block/executor/block_state.go
  vms/platformvm/block/executor/block_test.go
  vms/platformvm/block/executor/options.go
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/block/executor/verifier.go
  vms/platformvm/metrics/metrics.go
  vms/platformvm/txs/executor/advance_time_test.go
  vms/platformvm/txs/executor/backend.go
  vms/platformvm/txs/executor/proposal_tx_executor.go
  vms/platformvm/txs/reward_validator_tx.go
Labels: consensus

#2646 Improve logging of unexpected proposer errors
  snow/engine/snowman/transitive.go
  vms/proposervm/block.go
  vms/proposervm/block_test.go
Labels: monitoring

#2647 Disable non-security related dependabot PRs
  .github/dependabot.yml
Labels: ci

#2649 Add historical fork times
  version/constants.go
Labels: cleanup

#2651 Cleanup warp signer tests
  vms/platformvm/warp/gwarp/signer_test.go
  vms/platformvm/warp/signer_test.go
  vms/platformvm/warp/test_signer.go
Labels: testing, cleanup

#2652 Reintroduce the upgrade test against v1.10.18
  .github/workflows/ci.yml
  scripts/tests.upgrade.sh
Labels: testing

#2653 Cleanup database benchmarks
  database/benchmark_database.go
  database/encdb/db_test.go
  database/leveldb/db_test.go
  database/memdb/db_test.go
  database/meterdb/db_test.go
  database/pebble/db_test.go
  database/prefixdb/db_test.go
  database/rpcdb/db_test.go
  database/versiondb/db_test.go
  x/merkledb/db_test.go
Labels: testing, cleanup

#2654 Cleanup database tests
  database/corruptabledb/db_test.go
  database/encdb/db_test.go
  database/leveldb/db_test.go
  database/memdb/db_test.go
  database/meterdb/db_test.go
  database/pebble/db_test.go
  database/prefixdb/db_test.go
  database/rpcdb/db_test.go
  database/test_database.go
  database/versiondb/db_test.go
  x/merkledb/db_test.go
Labels: testing, cleanup

#2650 `ci`: Add shellcheck step to lint job
  .github/workflows/build-deb-pkg.sh
  .github/workflows/build-tgz-pkg.sh
  .github/workflows/ci.yml
  .github/workflows/cleanup-net-outage-sim.sh
  .github/workflows/publish_image.sh
  .github/workflows/run-net-outage-sim.sh
  scripts/build_fuzz.sh
  scripts/build_test.sh
  scripts/constants.sh
  scripts/lint.sh
  scripts/mock.gen.sh
  scripts/protobuf_codegen.sh
  scripts/shellcheck.sh
  scripts/tests.e2e.existing.sh
  scripts/tests.e2e.sh
  scripts/tests.upgrade.sh
Labels: testing, ci

#2638 Replace `closeFn` with `t.Cleanup`
  database/rpcdb/db_test.go
  snow/validators/gvalidators/validator_state_test.go
  vms/platformvm/warp/gwarp/signer_test.go
Labels: testing, cleanup

#2655 Fix TestExpiredBuildBlock
  vms/proposervm/vm_test.go
Labels: bug, testing

#2657 `ci`: Update shellcheck.sh to pass all args to shellcheck
  scripts/shellcheck.sh
Labels: ci

#2668 `vms/platformvm`: Remove `NewAdvanceTimeTx` from `Builder`
  vms/platformvm/txs/builder/builder.go
  vms/platformvm/txs/executor/advance_time_test.go
Labels: testing, cleanup

#2670 Log error if database returns unsorted heights
  vms/platformvm/state/state.go
Labels: monitoring, incident response

#2669 `vms/platformvm`: Move `vm.Shutdown` call in tests to `t.Cleanup`
  vms/platformvm/service_test.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
Labels: testing, cleanup

#2664 `e2e`: Add test of `platform.getValidatorsAt` across nodes
  tests/e2e/p/validator_sets.go
Labels: testing

#2672 Fix P-chain validator set lookup race condition
  network/p2p/client.go
  network/p2p/gossip/gossip.go
  network/p2p/gossip/handler.go
  network/p2p/gossip/message.go
  network/p2p/network.go
  network/p2p/router.go
  vms/platformvm/network/network.go
  vms/platformvm/vm.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
Labels: bug, incident response

#2648 Update versions for v1.10.19
  RELEASES.md
  go.mod
  go.sum
  version/compatibility.json
  version/constants.go
Labels: dependencies

#2677 `ci`: Upgrade all workflow actions to versions using Node 20
  .github/workflows/buf-push.yml
  .github/workflows/build-linux-binaries.yml
  .github/workflows/build-macos-release.yml
  .github/workflows/build-public-ami.yml
  .github/workflows/build-ubuntu-amd64-release.yml
  .github/workflows/build-ubuntu-arm64-release.yml
  .github/workflows/build-win-release.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/fuzz.yml
  .github/workflows/fuzz_merkledb.yml
  .github/workflows/net-outage-sim.yml
  .github/workflows/publish_docker_image.yml
Labels: ci

#2675 `tmpnet`: Ensure restart after chain creation
  tests/fixture/tmpnet/network.go
  tests/fixture/tmpnet/subnet.go
Labels: testing

#2680 Publish docker images with race detection
  .github/workflows/publish_image.sh
  Dockerfile
  scripts/build_image.sh
Labels: ci

#2676 `vms/platformvm`: Remove `NewRewardValidatorTx` from `Builder`
  vms/platformvm/block/builder/builder.go
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/service_test.go
  vms/platformvm/txs/builder/builder.go
  vms/platformvm/txs/executor/reward_validator_test.go
  vms/platformvm/vm.go
Labels: cleanup

#2678 `ci`: Updated shellcheck script to support autofix
  scripts/shellcheck.sh
Labels: ci

#2679 Unblock misconfigured subnets
  snow/engine/snowman/transitive.go
  snow/engine/snowman/transitive_test.go
Labels: enhancement

#2663 `vms/platformvm`: Add missing txs to `txs.Builder`
  vms/platformvm/txs/builder/builder.go
  vms/platformvm/validator_set_property_test.go
Labels: cleanup

#2662 `vms/platformvm`: Disable `AddValidatorTx` and `AddDelegatorTx`
  tests/e2e/p/workflow.go
  vms/platformvm/block/builder/builder_test.go
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/service_test.go
  vms/platformvm/txs/executor/staker_tx_verification.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/vm_test.go
Labels: vm

#2684 Deprecate the auth API
  config/config.go
Labels: documentation

#2686 Fix P-chain Shutdown deadlock
  vms/platformvm/vm.go
Labels: bug
