Repository ava-labs/avalanchego, pull requests merged in 2024-11, with the labels that each got.

#3513 Rename `constantsAreUnmodified` to `immutableFieldsAreUnmodified`
  vms/platformvm/state/subnet_only_validator.go
  vms/platformvm/state/subnet_only_validator_test.go
Labels: cleanup

#3512 Return shallow copy of validator set in platformVM's validator manager
  vms/platformvm/validators/manager.go
  vms/platformvm/vm_regression_test.go
Labels: bug, antithesis

#3516 ACP-77: Add caching to SoV DB helpers
  vms/platformvm/state/subnet_only_validator.go
  vms/platformvm/state/subnet_only_validator_test.go
Labels: acp77

#3388 ACP-77: Implement validator state
  RELEASES.md
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/block/executor/standard_block_test.go
  vms/platformvm/block/executor/verifier_test.go
  vms/platformvm/config/execution_config.go
  vms/platformvm/config/execution_config_test.go
  vms/platformvm/state/diff.go
  vms/platformvm/state/diff_test.go
  vms/platformvm/state/mock_chain.go
  vms/platformvm/state/mock_diff.go
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
  vms/platformvm/state/subnet_only_validator.go
Labels: acp77

#3519 ACP-77: Reduce block gossip log level
  snow/engine/snowman/engine.go
Labels: monitoring, acp77

#3518 ACP-77: Implement ids.ID#Append
  ids/id.go
  ids/id_test.go
Labels: acp77

#3520 ACP-103: Document and update genesis test fee configs
  genesis/genesis_fuji.go
  genesis/genesis_local.go
  genesis/genesis_mainnet.go
  vms/platformvm/block/executor/verifier_test.go
Labels: testing, acp77, acp103

#3412 ACP-77: Deactivate SoVs without sufficient fees
  vms/platformvm/block/builder/builder.go
  vms/platformvm/block/executor/manager.go
  vms/platformvm/block/executor/proposal_block_test.go
  vms/platformvm/block/executor/standard_block_test.go
  vms/platformvm/block/executor/verifier.go
  vms/platformvm/block/executor/verifier_test.go
  vms/platformvm/state/chain_time_helpers.go
  vms/platformvm/state/chain_time_helpers_test.go
  vms/platformvm/state/subnet_only_validator.go
  vms/platformvm/txs/executor/proposal_tx_executor.go
  vms/platformvm/txs/executor/state_changes.go
  vms/platformvm/txs/executor/state_changes_test.go
Labels: acp77

#3524 Remove stutter in P-chain wallet builder
  wallet/chain/p/builder/with_options.go
  wallet/chain/p/wallet/with_options.go
Labels: cleanup

#3523 Clarify EndAccumulatedFee comment
  vms/platformvm/state/subnet_only_validator.go
Labels: documentation, cleanup, acp77

#3527 [tmpnet] Misc cleanup for monitoring tooling
  scripts/configure-local-metrics-collection.sh
  scripts/run_prometheus.sh
  scripts/run_promtail.sh
  tests/fixture/tmpnet/README.md
  tests/fixture/tmpnet/network.go
Labels: testing

#3528 Remove P-chain txsmock package
  scripts/mocks.mockgen.source.txt
  vms/platformvm/block/executor/verifier_test.go
  vms/platformvm/txs/txsmock/unsigned_tx.go
Labels: testing, cleanup

#3525 Unexport all P-Chain visitors
  vms/platformvm/block/builder/builder.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/block/executor/manager.go
  vms/platformvm/block/executor/verifier.go
  vms/platformvm/txs/executor/advance_time_test.go
  vms/platformvm/txs/executor/atomic_tx_executor.go
  vms/platformvm/txs/executor/create_chain_test.go
  vms/platformvm/txs/executor/create_subnet_test.go
  vms/platformvm/txs/executor/export_test.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/txs/executor/import_test.go
  vms/platformvm/txs/executor/proposal_tx_executor.go
  vms/platformvm/txs/executor/proposal_tx_executor_test.go
  vms/platformvm/txs/executor/reward_validator_test.go
  vms/platformvm/txs/executor/standard_tx_executor.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
Labels: cleanup

#3529 Standardize P-Chain tx visitor order
  vms/platformvm/metrics/tx_metrics.go
  vms/platformvm/txs/executor/atomic_tx_executor.go
  vms/platformvm/txs/executor/standard_tx_executor.go
  vms/platformvm/txs/fee/complexity.go
  vms/platformvm/txs/fee/static_calculator.go
  vms/platformvm/txs/visitor.go
  wallet/chain/p/signer/visitor.go
  wallet/chain/p/wallet/backend_visitor.go
Labels: cleanup

#3420 ACP-77: Implement `RegisterSubnetValidatorTx`
  tests/e2e/p/l1.go
  vms/platformvm/metrics/tx_metrics.go
  vms/platformvm/signer/proof_of_possession.go
  vms/platformvm/signer/proof_of_possession_test.go
  vms/platformvm/txs/codec.go
  vms/platformvm/txs/executor/atomic_tx_executor.go
  vms/platformvm/txs/executor/proposal_tx_executor.go
  vms/platformvm/txs/executor/standard_tx_executor.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/txs/fee/calculator_test.go
  vms/platformvm/txs/fee/complexity.go
  vms/platformvm/txs/fee/static_calculator.go
  vms/platformvm/txs/register_subnet_validator_tx.go
  vms/platformvm/txs/register_subnet_validator_tx_test.go
  vms/platformvm/txs/register_subnet_validator_tx_test.json
  vms/platformvm/txs/visitor.go
  vms/platformvm/validators/manager.go
  vms/platformvm/warp/payload/addressed_call.go
  vms/platformvm/warp/payload/hash.go
  vms/platformvm/warp/payload/payload.go
  vms/platformvm/warp/payload/payload_test.go
  wallet/chain/p/builder/builder.go
  wallet/chain/p/builder/with_options.go
  wallet/chain/p/builder_test.go
  wallet/chain/p/signer/visitor.go
  wallet/chain/p/wallet/backend_visitor.go
  wallet/chain/p/wallet/wallet.go
  wallet/chain/p/wallet/with_options.go
  wallet/subnet/primary/examples/register-subnet-validator/main.go
Labels: acp77

#3533 ACP-77: Refactor P-Chain configs
  node/node.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/executor/block_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/block/executor/verifier_test.go
  vms/platformvm/config/config.go
  vms/platformvm/config/config_test.go
  vms/platformvm/config/execution_config.go
  vms/platformvm/config/internal.go
  vms/platformvm/config/network.go
  vms/platformvm/factory.go
  vms/platformvm/network/network.go
  vms/platformvm/network/network_test.go
  vms/platformvm/service.go
  vms/platformvm/service_test.go
  vms/platformvm/state/chain_time_helpers.go
  vms/platformvm/state/chain_time_helpers_test.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
  vms/platformvm/state/statetest/state.go
  vms/platformvm/txs/executor/backend.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/txs/executor/staker_tx_verification_test.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/txs/executor/state_changes_test.go
  vms/platformvm/txs/txstest/context.go
  vms/platformvm/txs/txstest/wallet.go
  vms/platformvm/validator_set_property_test.go
  vms/platformvm/validators/manager.go
  vms/platformvm/validators/manager_benchmark_test.go
  vms/platformvm/validators/manager_test.go
  vms/platformvm/vm.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
Labels: cleanup, acp77

#3537 ACP-77: Refactor subnet auth verification
  vms/platformvm/txs/executor/staker_tx_verification.go
  vms/platformvm/txs/executor/standard_tx_executor.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/txs/executor/subnet_tx_verification.go
Labels: cleanup

#3421 ACP-77: Implement `SetSubnetValidatorWeightTx`
  tests/e2e/p/l1.go
  vms/platformvm/metrics/tx_metrics.go
  vms/platformvm/txs/codec.go
  vms/platformvm/txs/executor/atomic_tx_executor.go
  vms/platformvm/txs/executor/proposal_tx_executor.go
  vms/platformvm/txs/executor/standard_tx_executor.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/txs/fee/calculator_test.go
  vms/platformvm/txs/fee/complexity.go
  vms/platformvm/txs/fee/static_calculator.go
  vms/platformvm/txs/set_subnet_validator_weight_tx.go
  vms/platformvm/txs/set_subnet_validator_weight_tx_test.go
  vms/platformvm/txs/set_subnet_validator_weight_tx_test.json
  vms/platformvm/txs/visitor.go
  wallet/chain/p/builder/builder.go
  wallet/chain/p/builder/with_options.go
  wallet/chain/p/builder_test.go
  wallet/chain/p/signer/visitor.go
  wallet/chain/p/wallet/backend_visitor.go
  wallet/chain/p/wallet/wallet.go
  wallet/chain/p/wallet/with_options.go
  wallet/subnet/primary/examples/set-subnet-validator-weight/main.go
Labels: acp77

#3543 Rename error to be more generic
  vms/platformvm/txs/executor/create_chain_test.go
  vms/platformvm/txs/executor/proposal_tx_executor_test.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/txs/executor/subnet_tx_verification.go
Labels: cleanup, acp77

#3540 Add `platform.getSubnetOnlyValidator` API
  RELEASES.md
  tests/e2e/p/l1.go
  vms/platformvm/client.go
  vms/platformvm/service.go
  vms/platformvm/service.md
Labels: acp77

#3541 Add SoV deactivation owner support to the P-chain wallet
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/block/executor/verifier_test.go
  vms/platformvm/client.go
  vms/platformvm/txs/executor/helpers_test.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/txs/txstest/wallet.go
  vms/platformvm/vm_test.go
  wallet/chain/p/builder/builder.go
  wallet/chain/p/signer/signer.go
  wallet/chain/p/signer/visitor.go
  wallet/chain/p/wallet/backend.go
  wallet/chain/p/wallet/backend_visitor.go
  wallet/subnet/primary/wallet.go
Labels: acp77

#3423 ACP-77: Implement Warp message verification
  snow/snowtest/context.go
  vms/platformvm/block/builder/builder.go
  vms/platformvm/block/executor/block.go
  vms/platformvm/block/executor/manager.go
  vms/platformvm/block/executor/verifier_test.go
  vms/platformvm/block/executor/warp_verifier.go
  vms/platformvm/block/executor/warp_verifier_test.go
  vms/platformvm/txs/executor/warp_verifier.go
  vms/platformvm/txs/executor/warp_verifier_test.go
  vms/platformvm/vm.go
Labels: acp77

#3404 ACP-77: Current validators API for SoV
  proto/pb/validatorstate/validator_state.pb.go
  proto/pb/validatorstate/validator_state_grpc.pb.go
  proto/validatorstate/validator_state.proto
  snow/validators/gvalidators/validator_state_client.go
  snow/validators/gvalidators/validator_state_server.go
  snow/validators/state.go
  snow/validators/traced_state.go
  snow/validators/validator.go
  snow/validators/validatorsmock/state.go
  snow/validators/validatorstest/state.go
  vms/platformvm/state/mock_state.go
  vms/platformvm/state/state.go
  vms/platformvm/state/state_test.go
  vms/platformvm/validators/manager.go
  vms/platformvm/validators/validatorstest/manager.go
Labels: acp77, Uptime Tracking

#3428 ACP-77: Implement Warp message signing
  network/p2p/acp118/handler.go
  proto/pb/platformvm/platformvm.pb.go
  proto/platformvm/platformvm.proto
  tests/e2e/p/l1.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/network/network.go
  vms/platformvm/network/network_test.go
  vms/platformvm/network/warp.go
  vms/platformvm/network/warp_test.go
  vms/platformvm/state/state.go
  vms/platformvm/vm.go
  vms/platformvm/warp/message/payload.go
  vms/platformvm/warp/message/register_subnet_validator.go
  vms/platformvm/warp/message/subnet_conversion.go
  vms/platformvm/warp/message/subnet_validator_registration.go
  vms/platformvm/warp/message/subnet_validator_weight.go
  wallet/subnet/primary/examples/sign-subnet-conversion/main.go
  wallet/subnet/primary/examples/sign-subnet-validator-registration/main.go
  wallet/subnet/primary/examples/sign-subnet-validator-removal-genesis/main.go
  wallet/subnet/primary/examples/sign-subnet-validator-removal-registration/main.go
  wallet/subnet/primary/examples/sign-subnet-validator-weight/main.go
Labels: acp77

#3429 ACP-77: Implement IncreaseBalanceTx
  tests/e2e/p/l1.go
  vms/platformvm/metrics/tx_metrics.go
  vms/platformvm/txs/codec.go
  vms/platformvm/txs/executor/atomic_tx_executor.go
  vms/platformvm/txs/executor/proposal_tx_executor.go
  vms/platformvm/txs/executor/standard_tx_executor.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/txs/executor/warp_verifier.go
  vms/platformvm/txs/executor/warp_verifier_test.go
  vms/platformvm/txs/fee/calculator_test.go
  vms/platformvm/txs/fee/complexity.go
  vms/platformvm/txs/fee/static_calculator.go
  vms/platformvm/txs/increase_balance_tx.go
  vms/platformvm/txs/increase_balance_tx_test.go
  vms/platformvm/txs/increase_balance_tx_test.json
  vms/platformvm/txs/visitor.go
  wallet/chain/p/builder/builder.go
  wallet/chain/p/builder/with_options.go
  wallet/chain/p/builder_test.go
  wallet/chain/p/signer/visitor.go
  wallet/chain/p/wallet/backend_visitor.go
  wallet/chain/p/wallet/wallet.go
  wallet/chain/p/wallet/with_options.go
  wallet/subnet/primary/examples/increase-balance/main.go
Labels: acp77

#3440 ACP-77: Implement DisableSubnetValidatorTx
  tests/e2e/p/l1.go
  vms/platformvm/metrics/tx_metrics.go
  vms/platformvm/txs/codec.go
  vms/platformvm/txs/disable_subnet_validator_tx.go
  vms/platformvm/txs/disable_subnet_validator_tx_test.go
  vms/platformvm/txs/disable_subnet_validator_tx_test.json
  vms/platformvm/txs/executor/atomic_tx_executor.go
  vms/platformvm/txs/executor/proposal_tx_executor.go
  vms/platformvm/txs/executor/standard_tx_executor.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/txs/executor/warp_verifier.go
  vms/platformvm/txs/executor/warp_verifier_test.go
  vms/platformvm/txs/fee/calculator_test.go
  vms/platformvm/txs/fee/complexity.go
  vms/platformvm/txs/fee/static_calculator.go
  vms/platformvm/txs/visitor.go
  wallet/chain/p/builder/builder.go
  wallet/chain/p/builder/with_options.go
  wallet/chain/p/builder_test.go
  wallet/chain/p/signer/visitor.go
  wallet/chain/p/wallet/backend_visitor.go
  wallet/chain/p/wallet/wallet.go
  wallet/chain/p/wallet/with_options.go
  wallet/subnet/primary/examples/disable-subnet-validator/main.go
Labels: acp77

#3536 Improve P-Chain error messages
  vms/platformvm/block/executor/manager.go
  vms/platformvm/network/gossip.go
Labels: monitoring

#3454 Add Etna logging
  main/main.go
  vms/platformvm/block/executor/block.go
  vms/platformvm/vm.go
Labels: acp77

#3458 Add Etna P-chain metrics
  vms/platformvm/block/executor/acceptor.go
  vms/platformvm/block/executor/acceptor_test.go
  vms/platformvm/block/executor/block_state.go
  vms/platformvm/block/executor/verifier.go
  vms/platformvm/block/executor/verifier_test.go
  vms/platformvm/metrics/metrics.go
  vms/platformvm/metrics/no_op.go
Labels: acp77, acp103

#3545 Clarify benched field
  api/info/service.md
Labels: documentation

#3491 Allow non primary network validators to request all peers
  network/network.go
  network/network_test.go
Labels: acp77

#3530 Add `platform.getProposedHeight` API
  RELEASES.md
  vms/platformvm/client.go
  vms/platformvm/service.go
  vms/platformvm/service.md
  vms/platformvm/service_test.go
Labels: Warp Signature API

#3548 ACP-103: Finalize complexity calculations
  utils/crypto/bls/bls_benchmark_test.go
  vms/platformvm/signer/proof_of_possession_test.go
  vms/platformvm/txs/executor/standard_tx_executor_test.go
  vms/platformvm/txs/fee/calculator_test.go
  vms/platformvm/txs/fee/complexity.go
  vms/platformvm/txs/fee/complexity_test.go
Labels: acp103

#3549 ACP-103: Finalize parameterization
  genesis/genesis_fuji.go
  genesis/genesis_local.go
  genesis/genesis_mainnet.go
Labels: acp103

#3561 Refactor `logging.Format` to expose constants
  config/flags.go
  tests/fixture/bootstrapmonitor/cmd/main.go
  utils/logging/format.go
Labels: monitoring, cleanup

#3562 Use JSON logs during Antithesis runs
  tests/antithesis/compose.go
Labels: testing

#3563 Antithesis: Skip checks if tx confirmation fails
  tests/antithesis/avalanchego/main.go
Labels: testing, cleanup

#3558 update api docs
  api/admin/service.md
  api/health/service.md
  api/info/service.md
  api/keystore/service.md
  api/metrics/service.md
  indexer/service.md
  vms/platformvm/service.md
Labels: documentation

#3568 Remove unused wallet interface
  tests/antithesis/avalanchego/main.go
  tests/e2e/x/transfer/virtuous.go
  tests/fixture/e2e/helpers.go
  tests/fixture/tmpnet/subnet.go
  wallet/subnet/primary/wallet.go
Labels: cleanup

#3571 Remove redundant field in platformVM/network's Network
  vms/platformvm/network/network.go
Labels: cleanup
