Repository ava-labs/avalanchego, pull requests merged in 2025-03, with the labels that each got.

#3736 [ci] Simplify tmpnet monitoring action
  .github/actions/install-nix/action.yml
  .github/actions/run-monitored-tmpnet-cmd/action.yml
  .github/workflows/ci.yml
  tests/fixture/e2e/flags.go
Labels: ci

#3685 [tmpnet] Minimize duration of tx acceptance for e2e testing
  chains/manager.go
  config/config.go
  config/config.md
  config/config_test.go
  config/flags.go
  config/keys.go
  tests/e2e/x/transfer/virtuous.go
  tests/fixture/e2e/helpers.go
  tests/fixture/tmpnet/defaults.go
Labels: testing

#3692 [tmpnet] Deploy collectors with golang to simplify cross-repo use
  .github/actions/run-monitored-tmpnet-cmd/action.yml
  bin/tmpnetctl
  scripts/run_prometheus.sh
  scripts/run_promtail.sh
  tests/e2e/README.md
  tests/fixture/e2e/env.go
  tests/fixture/e2e/flags.go
  tests/fixture/e2e/metrics_link.go
  tests/fixture/tmpnet/README.md
  tests/fixture/tmpnet/cmd/main.go
  tests/fixture/tmpnet/monitor_processes.go
  tests/fixture/tmpnet/node_process.go
  tests/fixture/tmpnet/utils.go
  tests/upgrade/upgrade_test.go
Labels: testing, ci

#3740 [tmpnet] Add check for collection of logs and metrics to custom github action
  .github/actions/run-monitored-tmpnet-cmd/action.yml
  go.sum
  tests/fixture/tmpnet/README.md
  tests/fixture/tmpnet/check_monitoring.go
  tests/fixture/tmpnet/cmd/main.go
  tests/fixture/tmpnet/node_process.go
  tests/upgrade/upgrade_test.go
Labels: ci

#3747 Support caller-defined namespaces in merkledb
  x/merkledb/db.go
  x/merkledb/metrics.go
Labels: merkledb

#3775 Fix empty standard block check
  vms/platformvm/block/executor/standard_block_test.go
  vms/platformvm/block/executor/verifier.go
  vms/platformvm/block/executor/verifier_test.go
  vms/platformvm/vm_regression_test.go
  vms/platformvm/vm_test.go
Labels: incident response

#3777 Restrict ProposerVM P-chain height advancement
  vms/proposervm/block.go
  vms/proposervm/pre_fork_block.go
  vms/proposervm/vm.go
  vms/proposervm/vm_test.go
Labels: incident response

#3774 Remove support for AVM tx checksums
  vms/avm/block/executor/block.go
  vms/avm/block/executor/block_test.go
  vms/avm/state/state.go
  vms/avm/state/statemock/state.go
  vms/platformvm/block/executor/acceptor.go
Labels: good first issue, cleanup

#3767 [ci] Stop emitting grafana link as an annotation
  .github/actions/run-monitored-tmpnet-cmd/action.yml
  .github/actions/run-monitored-tmpnet-cmd/notify-metrics-availability.sh
  tests/fixture/tmpnet/README.md
Labels: ci

#3766 [ci] Move monitoring check from github action to code
  .github/actions/run-monitored-tmpnet-cmd/action.yml
  tests/fixture/e2e/env.go
  tests/fixture/e2e/flags.go
  tests/fixture/tmpnet/check_monitoring.go
  tests/fixture/tmpnet/network.go
  tests/upgrade/upgrade_test.go
Labels: ci

#3780 [tmpnet] Start kind cluster with golang
  bin/tmpnetctl
  scripts/tests.e2e.bootstrap_monitor.sh
  tests/fixture/bootstrapmonitor/common.go
  tests/fixture/bootstrapmonitor/e2e/e2e_test.go
  tests/fixture/tmpnet/README.md
  tests/fixture/tmpnet/cmd/main.go
  tests/fixture/tmpnet/kube.go
  tests/fixture/tmpnet/start_kind_cluster.go
Labels: testing

#3811 [ci] Source shellcheck from nix instead of installing via script
  .github/workflows/ci.yml
  flake.nix
  scripts/shellcheck.sh
Labels: testing, ci

#3822 [ci] Use SHAs instead of tags for 3rd-party github actions
  .github/actions/install-nix/action.yml
  .github/actions/run-monitored-tmpnet-cmd/action.yml
  .github/workflows/buf-push.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/labels.yml
  .github/workflows/publish_antithesis_images.yml
  .github/workflows/trigger-antithesis-avalanchego.yml
  .github/workflows/trigger-antithesis-xsvm.yml
Labels: ci

#3823 [tmpnet] Add collector log path to readiness check log output
  tests/fixture/tmpnet/monitor_processes.go
Labels: testing

#3820 [ci] Enable run-monitored-tmpnet-cmd to use a remote flake file
  .github/actions/run-monitored-tmpnet-cmd/action.yml
  .github/actions/run-monitored-tmpnet-cmd/nix-develop.sh
Labels: ci

#3694 update: platformvm config doc
  vms/platformvm/config/config.md
Labels: lifecycle/stale

#3830 [tmpnet] Update script to run instead of install
  bin/tmpnetctl
Labels: testing
