Repository ava-labs/avalanchego, pull requests merged in 2025-05, with the labels that each got.

#3705 Remove RequestBuildBlock on P-Chain Mempool
  vms/platformvm/block/builder/builder.go
  vms/platformvm/block/builder/helpers_test.go
  vms/platformvm/block/executor/backend.go
  vms/platformvm/block/executor/helpers_test.go
  vms/platformvm/block/executor/manager.go
  vms/platformvm/block/executor/rejector.go
  vms/platformvm/block/executor/rejector_test.go
  vms/platformvm/block/executor/verifier_test.go
  vms/platformvm/network/gossip.go
  vms/platformvm/network/gossip_test.go
  vms/platformvm/network/network.go
  vms/platformvm/network/network_test.go
  vms/platformvm/txs/mempool/mempool.go
  vms/platformvm/vm.go
Labels: cleanup

#2876 Add test for proposervm BuildBlock after bootstrapping
  vms/proposervm/vm_test.go
Labels: bug, lifecycle/frozen, antithesis

#3882 [tmpnet] Enable runtime-specific restart behavior
  tests/fixture/tmpnet/network.go
  tests/fixture/tmpnet/node.go
  tests/fixture/tmpnet/process_runtime.go
  tests/fixture/tmpnet/utils.go
Labels: tooling

#3918 Use libevm instead of coreth
  genesis/genesis_test.go
  go.mod
  go.sum
  tests/e2e/c/dynamic_fees.go
  tests/fixture/tmpnet/genesis.go
  tests/imports_test.go
  utils/packages/dependencies.go
Labels: libevm

#3945 [tmpnet] Define reusable flags for configuring kubernetes client access
  Taskfile.yml
  flake.lock
  flake.nix
  scripts/start_kind_cluster.sh
  scripts/tests.e2e.bootstrap_monitor.sh
  tests/fixture/bootstrapmonitor/common.go
  tests/fixture/bootstrapmonitor/e2e/e2e_test.go
  tests/fixture/tmpnet/flags/kubeconfig.go
  tests/fixture/tmpnet/tmpnetctl/main.go
Labels: tooling

#3960 Chore: Add Solidity compiler to Nix
  .github/workflows/ci.yml
  flake.nix
  tests/load/c/contracts/EVMLoadSimulator.bindings.go
  tests/load/c/contracts/EVMLoadSimulator.sol
  tests/load/c/contracts/generate_abi_bindings.sh
Labels: dependencies, ci

#3950 Update proposervm summary to roll forward only
  vms/proposervm/state_summary.go
  vms/proposervm/state_syncable_vm_test.go
Labels: bug

#3969 [ci] Update dependabot to only propose security updates for github actions
  .github/dependabot.yml
Labels: ci
