Repository ava-labs/avalanchego, pull requests merged in 2025-04, with the labels that each got.

#3872 Remove GetAddressTxs
  RELEASES.md
  vms/avm/block/builder/builder_test.go
  vms/avm/block/executor/block.go
  vms/avm/block/executor/manager.go
  vms/avm/config.go
  vms/avm/config.md
  vms/avm/config_test.go
  vms/avm/environment_test.go
  vms/avm/index_test.go
  vms/avm/service.go
  vms/avm/service.md
  vms/avm/service_test.go
  vms/avm/tx.go
  vms/avm/vm.go
  vms/avm/vm_test.go
  vms/components/index/index.go
  vms/components/index/metrics.go
Labels: cleanup

#3583 Fix typos and add missing hyphens in README files
  tests/fixture/bootstrapmonitor/README.md
  vms/platformvm/docs/mempool_gossiping.md
  vms/proposervm/README.md
  x/sync/README.md
Labels: lifecycle/stale

#3782 Use EstimateBaseFee in e2e tests
  tests/e2e/c/dynamic_fees.go
Labels: lifecycle/stale

#3910 fix rpcchainvm handling for arbitrary length http body
  proto/http/http.proto
  proto/pb/http/http.pb.go
  vms/rpcchainvm/ghttp/http_client.go
  vms/rpcchainvm/ghttp/http_server.go
  vms/rpcchainvm/ghttp/http_test.go
Labels: bug

#3584 chore: fix some comments
  x/merkledb/trie.go
Labels: lifecycle/stale

#3565 Support UnmarshalJSON for `ExporterType`
  RELEASES.md
  config/config.go
  config/config.md
  config/flags.go
  config/keys.go
  node/node.go
  trace/exporter.go
  trace/exporter_type.go
  trace/exporter_type_test.go
  trace/tracer.go
Labels: lifecycle/stale

#3688 Fix change/range proofs + simplify the code
  x/merkledb/db.go
  x/merkledb/db_test.go
  x/merkledb/helpers_test.go
  x/merkledb/proof.go
  x/merkledb/proof_test.go
  x/merkledb/trie.go
  x/sync/g_db/db_server.go
  x/sync/manager.go
  x/sync/network_server.go
  x/sync/network_server_test.go
  x/sync/sync_test.go
Labels: merkledb
