Repository ava-labs/avalanchego, pull requests merged in 2025-02, with the labels that each got.

#3713 [ci] Fix metrics link annotation emitted for e2e and upgrade jobs
  .github/actions/run-monitored-tmpnet-cmd/notify-metrics-availability.sh
  .github/workflows/ci.yml
  tests/fixture/tmpnet/README.md
Labels: ci

#3687 Remove Mock Mempool
  vms/avm/block/builder/builder_test.go
  vms/avm/block/executor/block_test.go
  vms/avm/network/network_test.go
  vms/avm/txs/mempool/mempoolmock/mempool.go
  vms/avm/txs/mempool/mocks_generate_test.go
  vms/platformvm/block/executor/rejector_test.go
  vms/platformvm/block/executor/verifier_test.go
  vms/platformvm/network/gossip_test.go
  vms/platformvm/network/network_test.go
  vms/platformvm/txs/mempool/mempoolmock/mempool.go
  vms/platformvm/txs/mempool/mocks_generate_test.go
Labels: cleanup

#3739 [ci] Update to golangci-lint version compatible with go 1.23
  .golangci.yml
  scripts/lint.sh
Labels: ci

#3751 [antithesis] Set AVAGO_PLUGIN_DIR for VM images
  config/flags.go
  tests/antithesis/compose.go
  tests/antithesis/xsvm/Dockerfile.node
  vms/example/xsvm/Dockerfile
Labels: testing

#3737 [ci] Drop support for Ubuntu 20.04
  .github/workflows/build-linux-binaries.yml
  .github/workflows/build-ubuntu-amd64-release.yml
  .github/workflows/ci.yml
  README.md
Labels: ci
