Repository ava-labs/avalanchego, pull requests merged in 2025-01, with the labels that each got.

#3636 Update x/net to v0.33.0
  go.mod
  go.sum
Labels: dependencies

#3574 move genesis docs to genesis package and add note on initial staker handling
  config/config.md
  genesis/README.md
Labels: lifecycle/stale

#3643 merkledb visualisations v1 (change proofs and range proofs)
  x/merkledb/README.md
Labels: documentation

#3403 Make snowman use snowflake directly instead of snowball
  chains/manager.go
  snow/consensus/snowball/tree.go
  snow/consensus/snowman/consensus_test.go
  snow/consensus/snowman/mixed_test.go
  snow/consensus/snowman/snowman_block.go
  snow/consensus/snowman/topological.go
  snow/consensus/snowman/topological_test.go
  snow/engine/snowman/config_test.go
  snow/engine/snowman/engine_test.go
  vms/platformvm/vm_test.go
Labels: consensus

#3659 Silence docker InvalidDefaultArgInFrom warnings
  Dockerfile
  tests/antithesis/Dockerfile.builder-instrumented
  tests/antithesis/Dockerfile.builder-uninstrumented
  tests/antithesis/avalanchego/Dockerfile.node
  tests/antithesis/avalanchego/Dockerfile.workload
  tests/antithesis/xsvm/Dockerfile.node
  tests/antithesis/xsvm/Dockerfile.workload
  vms/example/xsvm/Dockerfile
Labels: testing

#3651 [testing] Support direnv to simplify usage of test tooling
  .envrc
  bin/ginkgo
  scripts/build_antithesis_images.sh
  scripts/build_xsvm.sh
  scripts/ginkgo.sh
  scripts/tests.e2e.bootstrap_monitor.sh
  scripts/tests.e2e.existing.sh
  scripts/tests.e2e.sh
  scripts/tests.upgrade.sh
  tests/antithesis/compose.go
  tests/e2e/README.md
  tests/fixture/e2e/flags.go
  tests/fixture/tmpnet/README.md
  tests/fixture/tmpnet/cmd/main.go
  tests/fixture/tmpnet/network.go
  tests/fixture/tmpnet/node_process.go
Labels: testing

#3337 Implement traversal based early termination
  snow/consensus/snowman/consensus.go
  snow/consensus/snowman/poll/early_term_no_traversal.go
  snow/consensus/snowman/poll/early_term_no_traversal_test.go
  snow/consensus/snowman/poll/early_term_traversal.go
  snow/consensus/snowman/poll/early_term_traversal_test.go
  snow/consensus/snowman/poll/graph.go
  snow/consensus/snowman/poll/graph_test.go
  snow/consensus/snowman/poll/prefix.go
  snow/consensus/snowman/poll/prefix_test.go
  snow/consensus/snowman/topological.go
  snow/engine/snowman/engine.go
  utils/bag/bag.go
  utils/bag/bag_test.go
Labels: consensus

#3683 [docker] Optimize build time by copying and downloading deps first
  Dockerfile
Labels: testing

#3684 [docker] Silence remaining InvalidDefaultArgInFrom warnings
  .dockerignore
  tests/antithesis/avalanchego/Dockerfile.workload
  tests/antithesis/xsvm/Dockerfile.node
  tests/antithesis/xsvm/Dockerfile.workload
Labels: testing
